### ISSUE TITLE
crazy buffer-file-name: nil, file-modified-p: t 

### ISSUE THREAD

**Issue by dabrahams** [jrblevin/markdown-mode#115]
Create a file containing the following:

```markdown
---
x: x
---
`x`
```

then open it in markdown-mode in emacs-24.5.1

For me, the buffer loses its relationship to a file and is marked as modified.

**Comment by jrblevin** [comment]
Thanks for the report. I confirmed this on Emacs 24.5.1. Oddly, on Emacs 25.1 the buffer is still marked as modified but `buffer-file-name` remains intact.

**Comment by jrblevin** [comment]
I think @syohex fixed this, but please reopen if the issue persists for some reason. Thanks again for reporting. This was a strange bug indeed.
