### ISSUE TITLE
Lag when typing 

### ISSUE THREAD

**Issue by vonkempnz** [jrblevin/markdown-mode#119]
When I use the latest markdown-mode.el from master I'm experiencing some significant lag when typing and editing markdown files. Running top shows the CPU cores hitting 100% and staying there while I'm typing. 

I thought it might be my Emacs, so I tried editing the same files in fundamental mode, text mode, and finally org-mode (with equivalent markup) and they all show the same behaviour – no observable lag and <5% CPU usage when typing. I also tried Emacs 24.5 and pretest 25.0.92.1 with the same results.

The issue seems to become more apparent with relatively large files. One file I've recently had problems with is an academic transcript. It's about 1,400 lines long and has 47,000 words, with some lines up to 300–400 words long. Other than its line-length, it's a wholly unremarkable file – no code blocks, links, footnotes, tables or other markup. It only has six headings and the rest is running text. However, I notice that the lag becomes less severe the closer I am to the bottom of the file.

**Comment by syohex** [comment]
Could you upload the file which reproduces this issue anywhere ?

And could you show us profile result ? You can profile by following steps.
- `M-x profiler-start`(Mode CPU)
- Some operations...
- `M-x profiler-report`

**Comment by jrblevin** [comment]
One option is to obfuscate your file while preserving the syntax. Then we could see what is happening. For example, you could do this in Emacs to replace all letters and numbers by x and 1, respectively:

    M-x replace-regexp RET [[:alpha:]] RET x
    M-x replace-regexp RET [[:digit:]] RET 1

Obviously, back up your file first!

**Comment by vonkempnz** [comment]
Hi, thank you for following up so quickly.

I profiled Emacs while typing a few short sentences in the problematic file I mentioned and it gave this result:

```
- ...                                                            2470  49%
   Automatic GC                                                  2470  49%
- redisplay_internal (C function)                                2458  48%
 - jit-lock-function                                             2458  48%
  - jit-lock-fontify-now                                         2457  48%
   - jit-lock--run-functions                                     2457  48%
    - run-hook-wrapped                                           2457  48%
     - #<compiled 0x404cb5ed>                                    2457  48%
      - font-lock-fontify-region                                 2457  48%
       - font-lock-default-fontify-region                        2457  48%
        - font-lock-fontify-syntactically-region                 2438  48%
         - syntax-propertize                                     2404  47%
          - markdown-syntax-propertize                           1283  25%
           - markdown-syntax-propertize-pre-blocks                534  10%
            - save-excursion                                      534  10%
             - let                                                534  10%
              + while                                             523  10%
              + markdown-calculate-list-levels                      6   0%
           + markdown-syntax-propertize-headings                  246   4%
           + markdown-syntax-propertize-comments                  197   3%
           + markdown-syntax-propertize-fenced-block-constructs   147   2%
           + markdown-syntax-propertize-yaml-metadata             137   2%
           + markdown-syntax-propertize-blockquotes                21   0%
          + markdown-syntax-propertize-extend-region             1019  20%
            syntax-propertize-wholelines                           31   0%
           syntax-ppss                                              2   0%
        + font-lock-fontify-keywords-region                        18   0%
+ command-execute                                                 112   2%
```
I've also placed a suitably obfuscated copy of the problematic transcript file on my dropbox here [https://www.dropbox.com/s/wbyoajof4uxshb7/sample%20file.md?dl=0](https://www.dropbox.com/s/wbyoajof4uxshb7/sample%20file.md?dl=0).

Hope it's useful.

Nick

**Comment by vancleve** [comment]
I am also experiencing a lot of CPU usage in Aquamacs with version 2.1 of markdown-mode. My profiler report doesn't look nearly as useful:

```
- redisplay_internal (C function)                                1796  64%
 - or                                                            1719  61%
  - and                                                          1719  61%
   - or                                                          1719  61%
    - not                                                        1716  61%
     + verify-visited-file-modtime                                 17   0%
    - and                                                           3   0%
       file-remote-p                                                3   0%
```

**Comment by jrblevin** [comment]
@vancleve I don't recognize those functions (verify-visited-file-modtime and file-remote-p), so I do not think the lag you are experiencing is related to markdown-mode directly. Searching indicates that those functions may be used by helm (see, e.g., [this issue](https://github.com/emacs-helm/helm/issues/749)). Are you running helm and if so can you turn it off and see if that helps?

**Comment by jrblevin** [comment]
@vonkempnz I was able to verify the lag you were seeing with the sample file you posted. Thank you for sending that.

It seems that after inserting characters, the region for "syntax propertization" was being extended multiple times to finally include the remainder of the (very large) buffer. I think I have fixed this issue in commit 23e64f4 so that only a more local region needs to be re-parsed after inserting characters. Please let me know if this issue is fixed for you now as well.

**Comment by vancleve** [comment]
@jrblevin thanks for the info. I'm now seeing this issue with an HTML so I'm assuming its Aquamacs specific. Thanks for looking though and apologies for the diversion!

**Comment by vonkempnz** [comment]
@jrblevin I tested again with the latest master and the issue is gone – typing is snappy and CPU usage is normal in all the files that were previously giving me grief.
I think you nailed it. Thanks and well done.

**Comment by jrblevin** [comment]
Great! Thanks again for taking the time to report this.
