### ISSUE TITLE
[Question] How do you get the nice rendering in the .md buffer?

### ISSUE THREAD

**Issue by ihodes** [jrblevin/markdown-mode#121]
Seen in this screenshot on the left-hand side, things like headers have a larger font-size, etc. http://jblevins.org/projects/markdown-mode/screenshots/20160108-001.png

Also, is there a story for displaying images in markdown buffers in Emacs? I see no image in the *eww* buffer (nor, unfortunately, in the .md buffer).

Thanks!

**Comment by jrblevin** [comment]
I do the variable-height headings via `custom-set-faces`, like so, relative to the baseline `markdown-header-face`:

``` Emacs-Lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.8))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.2)))))
```

eww can render images, but it seems to give the alt text priority. In the following examples, the first renders as "alt" but for the second, eww shows the image. I don't use `eww` much, so does anyone know how to ask it to display images in the presence of alt text?

``` Markdown
![alt](http://jblevins.org/projects/markdown-mode/screenshots/20160108-001.png)

![](http://jblevins.org/projects/markdown-mode/screenshots/20160108-001.png)
```

**Comment by ihodes** [comment]
That custom-set-face code worked great, thank you!

I think my problem was that I'd left off the file:// schema... alas.

(I do with there were a way to get images to display inline in the emacs text buffer, like org-mode can [but better; org-mode doesn't, as far as I have been able to figure out, let you easily resize them in the buffer itself] but I think that'd take a bit more hacking; I'll file an issue here, and maybe one day get around to it ;))

Thank you!
