### ISSUE TITLE
Syntax highlighting in GFM code blocks

### ISSUE THREAD

**Issue by ihodes** [jrblevin/markdown-mode#123]
Is this best supported through markdown-mode or through something like multi-mode highlighting?

**Comment by jrblevin** [comment]
There are a few such modes already, including [mmm-mode](https://github.com/purcell/mmm-mode) and [polymode](https://github.com/vspinu/polymode).

**Comment by jrblevin** [comment]
For a while, I was using `mmm-mode` configured as described here: <http://jblevins.org/log/mmm>. I don't do this any more, though, and so I haven't followed these packages recently.

**Comment by ihodes** [comment]
Awesome, I hadn't seen polymode. That'll work for me! Thank you :)

**Comment by ntc2** [comment]
Using `polymode`, it's trivial to highlight fenced code blocks in `markdown-mode`. All I needed to do was add the following to Emacs config:

``` emacs-lisp
(require 'markdown-mode)
(require 'poly-markdown)
(add-to-list 'auto-mode-alist '("\\.md\\'" . poly-markdown-mode))
```

Docs I used:
- https://github.com/vspinu/polymode
- https://vxlabs.com/2014/04/08/syntax-highlighting-markdown-fenced-code-blocks-in-emacs/

**Comment by jrblevin** [comment]
Built-in support is in master now. See custom variable `markdown-fontify-code-blocks-natively` and interactive function `markdown-toggle-fontify-code-blocks-natively` (<kbd>C-c C-x C-f</kbd>).
