### ISSUE TITLE
How to open eww preview on the right?

### ISSUE THREAD

**Issue by angrybacon** [jrblevin/markdown-mode#129]
With one single buffer open, with `markdown-live-preview-mode`, where should I look if I want to split vertically and open the EWW buffer on the right?

**Comment by jrblevin** [comment]
I prefer the preview on the right also, when the screen is large enough. The way I handle it is to split prior to enabling live preview. Then the "other-window" type commands will use the existing other window.

1. <kbd>C-x 3</kbd>
2. <kbd>C-c C-c l</kbd>

**Comment by angrybacon** [comment]
Yeah exacty. That is how I do it as of now. I'm looking for a way to have this behavior by default.

**Comment by jrblevin** [comment]
I have been too lazy to look, but I realized that when the main window is sufficiently wide, Emacs *will* split vertically by default without any other changes. Digging deeper, I found that this is determined by two threshold variables. Something like this in your `init.el` might help:

``` emacs-lisp
(setq split-height-threshold nil)
(setq split-width-threshold 160)
```

Reduce the latter to suit your configuration.

**Comment by angrybacon** [comment]
I was hoping for something more specific to `markdown-mode`, kind of like what `helm` does.

I'll play a little with this a little and see if I can have something acceptable.

**Comment by peniblec** [comment]
Would this help?

```elisp
(defun prefer-horizontal-split ()
  (set-variable 'split-height-threshold nil t)
  (set-variable 'split-width-threshold 40 t)) ; make this as low as needed

(add-hook 'markdown-mode-hook 'prefer-horizontal-split)
```
The `t` in `set-variable` means "... and keep it buffer-local".

**Comment by angrybacon** [comment]
@peniblec It does the job, but will break other split-related behaviors (such as browsing source for a [company][10] candidates).

[10]: https://github.com/company-mode/company-mode

**Comment by syohex** [comment]
If you use [popwin](https://github.com/m2ym/popwin-el), you can always popup buffer on the right.

```lisp
(require 'popwin)
(custom-set-variables
 '(display-buffer-function 'popwin:display-buffer))

(defun my/markdown-mode-hook ()
  (make-local-variable 'popwin:special-display-config)
  (push '("*eww*"  :width 0.5 :position right :stick t) popwin:special-display-config))
(add-hook 'markdown-mode-hook #'my/markdown-mode-hook)
```

Or should we add customize variable like `helm-display-function` ?

**Comment by jrblevin** [comment]
Sorry for the extremely long delay–windowing isn't my elisp strong suit–but I took a shot at allowing the window split direction to be customized.  If you're still interested, take a look at PR #188.

**Comment by angrybacon** [comment]
@jrblevin Looks I had forgotten about this one! Thanks for the reminder.

I'll have a look on macOS tomorrow. Installing Markdown on Windows sounds a little too painful for the use I would make of it.

**Comment by jrblevin** [comment]
I went ahead and incorporated #188 (see fc96bef).  Let me know if for some reason it doesn't work for you.

**Comment by angrybacon** [comment]
@jrblevin That works. Just a heads-up though, it seems now windows are not reused.

```
+-----------------+
| MD              |
|                 |
|                 |
+-----------------+

markdown-live-preview-mode

+--------+--------+
| MD     | EWW    |
|        |        |
|        |        |
+--------+--------+
```

```
+--------+--------+
| MD     | A      |
|        |        |
|        |        |
+--------+--------+

markdown-live-preview-mode

+-----+-----+-----+            +--------+--------+
| MD  | A   | EWW |  Expected  | MD     | A      |
|     |     |     |            |        |        |
|     |     |     |            |        |        |
+-----+-----+-----+            +--------+--------+

```

Helm has `helm-always-two-windows` for that. If you think this is somewhat relevant or a missing feature, I can open another issue with these details.

**Comment by jrblevin** [comment]
When you have time, check out the above changes. I think it now exhibits the expected behavior, but please let me know if not.

**Comment by angrybacon** [comment]
👌 

Thanks a lot!

**Comment by jrblevin** [comment]
Great—thanks for confirming!
