### ISSUE TITLE
markdwon-set-faces didn't work for chinese

### ISSUE THREAD

**Issue by algking** [jrblevin/markdown-mode#131]
(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.8 :foundry "18" :family "YaHei Consolas Hybrid"))))

I set up the height and also the font family ,but just the english part work .

![image](https://cloud.githubusercontent.com/assets/1456351/14586150/78f642a0-04c1-11e6-9361-0f8065ef66eb.png)

**Comment by syohex** [comment]
![markdown-font](https://cloud.githubusercontent.com/assets/554281/14587331/79789d24-04ec-11e6-9b4f-c9de413cf026.png)

It looks that font configuration works on my platform and works well for Japanese characters. However my environment is Japanese and Japanese font is used for `做` and `笔`. I download Chinese font from [here](https://github.com/liangfeng/consolas-font-for-airline).

BTW, you can check font information by `C-u C-x =`.

**Comment by jrblevin** [comment]
Sounds like Emacs is falling back to a different font for glyphs not in the selected font. You can check using the suggestion above (`C-u C-x =` or `describe-char`). In any case, I don't think this is related to markdown-mode specifically.

**Comment by algking** [comment]
Thanks @syohex @jrblevin ，I have found out the reason. long time ago,I have change the font set,because of the chinease and english ‘word align‘ problem . As I use the `set-font` function,one chinese char's width equal to two english chars,which look more beutiful to me .

`(defun set-font (english chinese english-size chinese-size)
  (set-face-attribute 'default nil :font
                      (format "%s:pixelsize=%d" english english-size))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font) charset
                      (font-spec :family chinese :size chinese-size))))
(set-font "Monaco" "YaHei Consolas Hybrid" 14 16)
`
