### ISSUE TITLE
Setext Heading and List Formatting Glitch

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#139]
There's a formatting glitch when using checkbox lists. If you have a list item, go to a new line and start another one, when you type the first hyphen, the previous line changes font-locking (the font size increases like a heading). E.g., type the following into an empty `gfm-mode` buffer.

    - [x] foo
    -

It doesn't matter if the box in the first line is checked or not. When you type the space after the hyphen on the second line, the first line reverts to correct formatting. If you then delete the added space, the first line doesn't change.

**Comment by jrblevin** [comment]
I've seen this too. It's unrelated to checkboxes. The problem is that

```
- foo
-
```

is technically a setext heading "- foo". Possible solutions would be to require setext headings to have two or more hyphens or to prohibit a setext header from beginning with a hyphen. Neither one is a perfect solution though.

**Comment by hmelman** [comment]
I see.  As someone who never uses setext headings, having an option I could turn off would be a fine solution. It could disable them all together or enable one of the less than perfect solutions.

**Comment by jrblevin** [comment]
Let's go with the second approach above for now (don't allow setext headers to begin with hyphens).

**Comment by hmelman** [comment]
I agree that seems like the least onerous restriction of the choices.
