### ISSUE TITLE
An error in command `markdown-standalone' leads to the out-of-order html output.

### ISSUE THREAD

**Issue by galeo** [jrblevin/markdown-mode#14]
The code:
```elisp
 (unless (markdown-output-standalone-p)
    (markdown-add-xhtml-header-and-footer output-buffer-name))
 (goto-char (point-min))
```
in https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L4421-L4423 would lead to the out-of-order html output. The html content generated by `markdown-command` should be placed in the middle of the xhtml header and footer.

Here is the code fix:
```elisp
(goto-char (point-min))
(unless (markdown-output-standalone-p)
  (markdown-add-xhtml-header-and-footer output-buffer-name))
```

**Comment by jrblevin** [comment]
Thanks—fixed in e90472b.
