### ISSUE TITLE
Possible wrong indication about direct download in README.md

### ISSUE THREAD

**Issue by deb0ch** [jrblevin/markdown-mode#140]
At the **direct download** section you suggest to write `(autoload 'gfm-mode "gfm-mode" ...` in our .emacs, but should not it be more like `(autoload 'gfm-mode "markdown-mode" ...` ?

It is possible that my understanding is wrong, but the first gave me a "file not found" error when opening .md files while the second worked just fine.

Cheers.

**Comment by jrblevin** [comment]
Thanks, you're absolutely right: it should be `(autload function filename)`. I'll fix this soon.

**Comment by syohex** [comment]
Done
