### ISSUE TITLE
A Second Setext Heading and List Formatting Glitch

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#143]
Related to #139, there's still a formatting issue with lists if the previous item is indented. Create a list:
- foo
  - bar

If you begin a new item on the next line at the top level (a - in the first column) , then the bar item will be temporarily formatted as a setext heading (until you add a space after it). It seems setext headings should be prohibited from beginning with a hyphen or whitespace and a hyphen.

**Comment by jrblevin** [comment]
Easy enough. I think that should do the trick, but let me know if not.

**Comment by hmelman** [comment]
1. this does fix this case, but it breaks the case in #139, just top level lists. Seems it only "works" if there's whitespace before the -. 
2. should you also be checking for tabs and not just spaces?

**Comment by jrblevin** [comment]
I think the above patch should fix this, but let me know if not. I also added tab as a prohibited character as you suggested. Thanks for reporting these issues.

**Comment by hmelman** [comment]
All seems to be working fine for me (sorry for the delay). Thanks very much.
