### ISSUE TITLE
Add markdown-move-* Commands to Menu

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#147]
I use markdown mode for a lot of notes and lists to share with other devices which have apps that can edit and render markdown nicely. I envy some of the org-mode functionality but the format doesn't work on my other devices. I wanted some of the list reordering commands that org has bound on M-arrows and didn't find a minor-mode to use with markdown. It was only after some digging I found it already worked with the markdown-move-\* commands. Thank you!

I wondered why I didn't know about them already and realized they weren't in the Markdown menu. I think they should be. For completeness here are all the bound markdown commands that I think should be considered for the menu.

```
;; List editing
(define-key map (kbd "M-<up>") 'markdown-move-up)
(define-key map (kbd "M-<down>") 'markdown-move-down)
;; Subtree editing
(define-key map (kbd "M-S-<up>") 'markdown-move-subtree-up)
(define-key map (kbd "M-S-<down>") 'markdown-move-subtree-down)
(define-key map (kbd "M-S-<left>") 'markdown-promote-subtree)
(define-key map (kbd "M-S-<right>") 'markdown-demote-subtree)
;; Movement
(define-key map (kbd "M-{") 'markdown-backward-paragraph)
(define-key map (kbd "M-}") 'markdown-forward-paragraph)
(define-key map (kbd "M-n") 'markdown-next-link)
(define-key map (kbd "M-p") 'markdown-previous-link)
;; Element insertion
(define-key map "\C-c\C-aw" 'markdown-insert-wiki-link)
(define-key map "\C-c\C-sk" 'markdown-insert-kbd)
(define-key map "\C-c\C-s\C-b" 'markdown-blockquote-region)
(define-key map "\C-c\C-s\C-p" 'markdown-pre-region)
(define-key map "\C-c\C-sP" 'markdown-insert-gfm-code-block)
```

**Comment by jrblevin** [comment]
Thanks for pointing out these omissions. I finally got around to reorganizing the menu (which was getting rather long) and adding the missing commands. I hope the new menu layout is helpful, but let me know if you have any comments or suggestions to improve it.

**Comment by hmelman** [comment]
My one suggestion is to have the menu items show the arrow based keybindings instead of the C-c C-x prefixed ones. They're much easier to use and remember and org-mode does this so there's some precedent. So that would be for:
- Promote Header
- Demote Header
- Indent List Item
- Exdent List Item
- Move List Item Up
- Move List Item Down

**Comment by jrblevin** [comment]
Thanks—done! See 0337778 for details.
