### ISSUE TITLE
Installation: markdown-mode-20160610.1745.el: Not found

### ISSUE THREAD

**Issue by evergreentan** [jrblevin/markdown-mode#149]
I followed the first way to install markdown-mode. After adding the following 
```
    (require 'package)
    (add-to-list 'package-archives
                 '("melpa-stable" . "https://stable.melpa.org/packages/"))
    (package-initialize)
```

to my `init.el` startup file and restarting emacs, I got the following message

`package-install-from-archive: https://melpa.org/packages/markdown-mode-20160610.1745.el: Not found` by issuing the following command: <kbd>M-x package-install RET markdown-mode RET</kbd>.

I am wondering where went wrong.

**Comment by syohex** [comment]
Please do `M-x package-refresh-contents` and try again.

**Comment by evergreentan** [comment]
@syohex It works now! Thanks.

**Comment by EricAtPrendo** [comment]
This issue is still there, but the README.md has not been updated to add:

 the following command: M-x package-install RET markdown-mode RET
