### ISSUE TITLE
Markdown: not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by evergreentan** [jrblevin/markdown-mode#150]
I tried to compile and have a preview of a markdown file. However the buffers gave me the following error:

`'markdown' is not recognized as an internal or external command, operable program or batch file.`

I am wondering whether it has anything to do with a missing system path value in a Windows 10 system. If so, what path should be added to the system variables in the environment. If not, how shall I fix this problem.

**Comment by jrblevin** [comment]
markdown-mode expects that the executable for the Markdown processor of your choice can be found in the Emacs `exec-path`.  I haven't used Emacs on Windows in many years, but I expect that you can remedy this in one of the following ways: either set `markdown-command` to be the *full path* of  the Markdown executable on your system, add the Markdown path to `exec-path` (e.g., in your init.el file), or install the exec-path-from-shell package.

**Comment by evergreentan** [comment]
@jrblevin Thanks. With regard to your suggestion, could you be more specific about where to find the full path of the Markdown executable? Do you mean markdown-mode.el? I could not find anything like markdown.exe file.

I followed [this post](https://lists.gnu.org/archive/html/help-gnu-emacs/2016-05/msg00211.html) to fix this problem on my laptop (Mac OS X). However, I was not able to use the same trick on Windows system.

**Comment by syohex** [comment]
You need to install markdown command from somewhere. For example http://daringfireball.net/projects/markdown/. If your installed markdown command is not named `markdown`, then you need to change `markdown-command` variable as below.

```lisp
(custom-set-variables
 '(markdown-command "your-markdown-command"))
```

You can check whether you can use markdown-command from Emacs by `M-: (executable-find "your-markdown-command")`. If you get `nil`, then markdown command is not installed or your PATH configuration is wrong. If you get path of markdown command, then there is no problem.
