### ISSUE TITLE
markdown-insert-gfm-code-block default language

### ISSUE THREAD

**Issue by conal** [jrblevin/markdown-mode#152]
In `markdown-insert-gfm-code-block` (`C-c C-s P`), I'm offered a what looks like a default (e.g., "haskell"), but when I press `enter`, I don't get a language for the fenced code region. Intended behavior? I can fix the code easily enough to use `(car markdown-gfm-used-languages)` as the default in `completing-read`, instead of adding to the prompt string, i.e., change

``` lisp
                (completing-read
                 (format "Programming language [%s]: "
                         (or (car markdown-gfm-used-languages) "none"))
                 (markdown-gfm-get-corpus)
                 nil 'confirm (car markdown-gfm-used-languages)
                 'markdown-gfm-language-history)
```

to

``` lisp
                (completing-read
                 "Programming language: "
                 (markdown-gfm-get-corpus)
                 nil 'confirm (car markdown-gfm-used-languages)
                 'markdown-gfm-language-history)
```

I like this behavior, but I'm unsure it's the behavior you want. If it is, I'll submit a pull request.

**Comment by conal** [comment]
Oops. Now I see that the language offered is the most recently *added* language, not most recently chosen language. A simple fix in `markdown-gfm-add-used-language` is to replace

``` lisp
  (add-to-list 'markdown-gfm-used-languages
               (markdown-clean-language-string lang))
```

by

```
  (setq markdown-gfm-used-languages
        (cons lang (remove lang markdown-gfm-used-languages)))
```

**Comment by jrblevin** [comment]
Thanks for reporting and fixing this! Sorry it took me so long to take a closer look. I didn't want to trouble you for a PR this long after the fact, so I applied the patch by hand as 7d8f78b. It seems fine to me, but let me know if you see any issues.
