### ISSUE TITLE
Bug: This_shouldn't_be italic

### ISSUE THREAD

**Issue by itsafire** [jrblevin/markdown-mode#153]
Hi,

I see this being a bug with version 20160629.459 of markdown-mode which I got via melpa.

My test case:

``` 
This_shouldn't_be marked as italic.
Because variable_names_do_contain_underscores = 5
Only _this is italic_.
```
And is rendered here on github like:

This_shouldn't_be marked as italic.
Because variable_names_do_contain_underscores = 5
Only _this is italic_.

See attached output of emacs24-nox:

<img width="724" alt="screen shot 2016-07-20 at 11 46 51" src="https://cloud.githubusercontent.com/assets/2641417/16982389/bf3461f0-4e6f-11e6-8fb2-518755941fe8.png">

**Comment by syohex** [comment]
It is github markdown flavor. Markdown does not have specification about this.

**Comment by jrblevin** [comment]
This behavior is expected with Markdown. If you want underscores inside variable names to be ignored, you probably want GitHub Flavored Markdown, for which you can use `gfm-mode`.

**Comment by phst** [comment]
CommonMark now says that `_` doesn't add emphasis inside words: http://spec.commonmark.org/0.26/#example-336
Can we reopen this issue? (Assuming that markdown-mode wants to follow CommonMark.)

**Comment by syohex** [comment]
@phst Could you open as new issue ?

**Comment by jrblevin** [comment]
Actually, I do not think there is any need for a new issue. This is the intended behavior. As before, use `gfm-mode` for this type of underscore behavior and `markdown-mode` for the original behavior.

**Comment by phst** [comment]
Why is it intended? Shouldn't markdown-mode try to follow the CommonMark spec, now that it's available?

**Comment by jrblevin** [comment]
CommonMark is not the same as Markdown, so `markdown-mode` should implement Markdown not CommonMark. I wouldn't be opposed to someone adding a derived `commonmark-mode`, but it's not very compelling to add and maintain another derived mode since the main practical difference is how underscores are handled, and `gfm-mode` already implements the other underscore behavior. So, both options are available and you can use the one you prefer.

**Comment by phst** [comment]
Thanks for the clarification, I wasn't aware that "Gruber markdown" already specified the current behavior.
