### ISSUE TITLE
syntax class for " should be "?

### ISSUE THREAD

**Issue by plantarum** [jrblevin/markdown-mode#158]
Hi,

I use expand-region, and noticed it wasn't working properly for quoted strings in markdown-mode. This appears to be by design, as you've deliberately changed the syntax class of " from " (i.e., quote) to . (i.e., punctuation:

    (defvar markdown-mode-syntax-table
      (let ((tab (make-syntax-table text-mode-syntax-table)))
        (modify-syntax-entry ?\" "." tab)
        tab)
    "Syntax table for `markdown-mode'.")

[link to source](https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L3151-L3155)

Is there a reason for this? I'm currently over-riding this in my init, but maybe something unexpected will break?

Best,

Tyler

**Comment by syohex** [comment]
Markdown have no concept of string.

**Comment by jrblevin** [comment]
Markdown is not a programming language, it's just plain text. As an example, consider the quotation marks in the GPS coordinates 51° 24' 26.74" N, 116° 14' 24.76" W.

**Comment by plantarum** [comment]
> Markdown has no concept of string.

No, but *plain text* has a concept of quote for which the string character class is useful.

Quotes have special meaning in plain text - they signify quotations. That's why they're called "quotes". In Emacs' `text-mode` (which you inherit your syntax table from) the quote symbol is assigned to the string syntax class for this reason. The use of quotes in GPS coordinates is much rarer than using quotes for quotes. If it weren't, we'd call them "seconds" not "quotes". And leaving quotes in the "string" syntax class wouldn't stop them being used in coordinates as well.

So, is there a technical reason to make this one change from the text-mode table markdown-mode inherits from - does it break some feature in markdown-mode otherwise? If not,  it's breaking a feature that's useful when working with plain text documents (ie, marking quotations).

**Comment by jrblevin** [comment]
The "string quote" class in the Emacs syntax table is for literal expressions inside balanced, matching quotes. In plain text, quotation marks (single, double, or back) are not required to be balanced in any syntactical sense. As I understand it, this syntax class was intended for programming languages, which have clear syntax rules that distinguish quoted literal strings from actual code. In plain text, as soon as you have one lone quotation mark (") the balanced string expressions that follow would be incorrectly identified by the syntax table (which follows only very simple rules for balanced quotes, but these sufficient for most programming languages).

This is not just my opinion. Here is the official word on the "string quote" syntax class from the [Emacs Lisp Reference Manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html#Syntax-Class-Table):

> Human text has no string quote characters. We do not want quotation marks to turn off the usual syntactic properties of other characters in the quotation.

Also, on my Emacs (I checked 25 and 24.2), the syntax class of " is . (punctuation) in `text-mode`, so perhaps I don't even need to change the class any more? It's possible that the line in question is a remnant from when markdown-mode inherited from the default syntax table (33a0326).

**Comment by plantarum** [comment]
I stand corrected! After grepping through my .emacs.d, I see that **I** changed the syntax class of the quote from punctuation to string, that isn't the default value after all. Which explains a lot of odd little inconsistencies I've been encountering among various text modes (i.e., `"` is punctuation in markdown, rmarkdown, but string in org, by default, and text, by my intervention).

Thanks for your patience.
