### ISSUE TITLE
indentation of multi-line list items after pressing Enter on Emacs 24.5.1

### ISSUE THREAD

**Issue by dlukes** [jrblevin/markdown-mode#16]
I regularly use two different versions of Emacs (24.3.1 and 24.5.1) and I've noticed that between them, the behavior of `newline-and-indent` has changed:

```diff
 (defun newline-and-indent ()
   (interactive "*")
   (delete-horizontal-space t)
-  (newline)
+  (newline nil t)
   (indent-according-to-mode))
```

By extension, this means that the behavior of `markdown-enter-key` has changed as well. Whereas in Emacs 24.3.1, when I press <kbd>Enter</kbd> at the end of a multi-line list element, this happens:

```
- list
  - nested list with long lines which need to be
    hard wrapped
    █
```

... in Emacs 24.5.1, this happens instead:

```
- list
  - nested list with long lines which need to be
  hard wrapped
  █
```

(In both cases, `markdown-indent-on-enter` is set to `t`.)

What is the intended behavior? Personally, I think the first one is more desirable, because it preserves the nice formatting (with hanging indentation) of multi-line list elements, but irrespective of what I think, would it be possible to make it consistent either way?

And cheers for all the great work on `markdown-mode` by the way, thank you ever so much :)

**Comment by vyp** [comment]
If a choice needs to be made between the two, I also vote for the first behaviour for the same reason.

**Comment by jrblevin** [comment]
Thanks for reporting this. The first behavior is intended. Just an update: I took a look at the documentation for the arguments to `newline` but it led me down a couple of levels deeper to some obscure hooks. I haven't figured out exactly why the behavior is different or determined how to best handle this in a way that is backwards compatible. If anyone knows more about the `newline-and-indent` change or has thoughts on how to handle this, feel free to chime in.
