### ISSUE TITLE
fill-paragraph shoudn't break inline R code chunks

### ISSUE THREAD

**Issue by lgatto** [jrblevin/markdown-mode#160]
When using `markdown-mode` with R, `fill-paragraph` breaks in-line code. For example

```
These data are directly available from the `r Biocexptpkg("pRolocdata")` package.
```
produces

```
These data are directly available from the `r
Biocexptpkg("pRolocdata")` package
```
which is then simply formatted as in-line code, rather then being interpreted, as illustrated below

![2016-06-01-095008_851x204_scrot](https://cloud.githubusercontent.com/assets/384198/17938859/addd2b82-6a1f-11e6-8111-bf2cd40fc6ab.png)

This is possibly related to #159.

I would be happy to try to fix this with some help to get started.

I am currently using

```
     Status: Installed in `~/.emacs.d/elpa/markdown-mode-20160803.1848/' (unsigned).
    Archive: n/a
    Version: 20160803.1848
   Requires: emacs-24, cl-lib-0.5
    Summary: Major mode for Markdown-formatted text
   Homepage: http://jblevins.org/projects/markdown-mode/
   Keywords: markdown github flavored markdown itex 
    Other versions: 20160803.1848 (melpa), 2.1 (melpa-stable).
```

**Comment by jrblevin** [comment]
Markdown allows line breaks in inline code fragments, so this isn't exactly a bug. I recognize that it's not the desired behavior in the case of linking to R packages, but that's a rather special case. Perhaps this should be fixed on the R side: why not parse the links across line breaks when that's perfectly valid Markdown?

**Comment by lgatto** [comment]
It's not really a link parsing issue. The problem is that when inline code fragments are line-broken, the R code is not interpreted any more. But, yes, if markdown supports line breaks in inline code, I suppose the code evaluation should do too. I'll try to investigate further. Thanks!
