### ISSUE TITLE
Add support for Liquid tags embedded in Markdown file

### ISSUE THREAD

**Issue by fusion809** [jrblevin/markdown-mode#163]
Hi,

I'd like to request that support for Shopify's Liquid templating engine (used by the static site generator, Jekyll) be added to this mode. `{%` is used to denote the starting of a Liquid tag. Likewise `%}` denotes the closing of a Liquid tag. `{{` denotes the start of a variable inclusion and `}}` denotes the end of a variable inclusion. I'm mentioning this as it should allow ya to adjust the grammars of this package. Underscores (`_`) can be used between Liquid tags! In this context they are not being used to italicize text. At the moment, however, this mode causes them to italicize everything after the underscore, which is getting irritating when I use this mode to edit my Jekyll site. 

Thanks for your time,
Brenton

**Comment by syohex** [comment]
Sorry too late reply. I think this proposal should be implemented in minor-mode like `liquid-mode` etc.
