### ISSUE TITLE
Consider making all top level bindings non-default

### ISSUE THREAD

**Issue by jasonm23** [jrblevin/markdown-mode#164]
There's a few top level bindings in markdown-mode e.g. `C-<left>` and `C-<right>`

These have annoyed me somewhat over the years, but I noticed people having issues with these bindings, so I think it's worth opening discussion at least.

While disabling some of these might cause problems for some existing users, a command or customizable setting to enable these top level bindings, could be provided.

Since markdown-mode otherwise does a fantastic job of keeping bindings on `C-c ...` it would be nice if it always avoided stepping on the top level keymap.

**Comment by syohex** [comment]
markdown-mode does not assign any commands to `C-<left>`, `C-<right>`. What commands did you say about ?

**Comment by jasonm23** [comment]
> See my edit - M-<left> & M-<right>

But the suggestion isn't really about any specific binding.

Just suggesting to remove top level bindings, and have them enabled on demand instead.

**Comment by syohex** [comment]
Hmm, I suppose top level bindings are inspired by org-mode. However org-mode does not have such configuration.

**Comment by jasonm23** [comment]
That shouldn't really have relevance to Markdown mode.  It's supposed to be a text markup format, not a wide reaching app like Org

That said, there are certainly a few top level org-mode bindings which are also obtrusive.  But given that Org has such a broad scope it's not so straight forward to know where to draw the line.

Markdown isn't ambiguous in that way, so it's best to avoid trying to draw tenuous parallels.

Uniformity of the users chosen editing experience, and default and user defined top level bindings should be respected.

**Comment by syohex** [comment]
IMO, I disagree this suggestion. I think the user should disable such key bindings by himself/herself, if he/she annoys them.

**Comment by jasonm23** [comment]
The problem with this is that there are extensive bindings on C-c etc. which is IMO where they belong.

Markdown is as close to plain text as we can be.  

Please reconsider the suggestion thoughtfully.

**Comment by jrblevin** [comment]
Sorry for the long delay in responding.  Just a quick update...

When I added the keybindings in question, they were indeed inspired by Org mode.  Until you opened this issue I didn't know that <kbd>M-&lt;left&gt;</kbd> and <kbd>M-&lt;right&gt;</kbd> were even bound (I've always used <kbd>M-f</kbd> and <kbd>M-b</kbd>).  I'm closing in on a v2.3 stable release and after that I'm planning to add some new features which will involve re-thinking the existing keybindings anyway.  So, I understand the concern and will either change the keybindings (e.g., by combining the functionality into other keys) or add a custom variable to enable/disable the toplevel keys.

**Comment by jrblevin** [comment]
The list/outline editing commands and the promotion/demotion commands have now been removed from the top-level positions.  Previously they were at:

```
M-<left>    M-S-<left>
M-<right>   M-S-<right>
M-<up>      M-S-<up>
M-<down>    M-S-<down>
```

The commands have been consolidated so that they work on list or heading subtrees, depending on context, and are now bound under <kbd>C-c</kbd>:

```
C-c <left>
C-c <right>
C-c <up>
C-c <down>
```
