### ISSUE TITLE
Backspace doesn't delete region

### ISSUE THREAD

**Issue by cpitclaudel** [jrblevin/markdown-mode#166]
Markdown mode's redefinition of `<backspace>` doesn't handle the case in which a region is selected before pressing backspace.  In that case, the plain Emacs implementation deletes the full region, whereas markdown-mode only unindents.

To reproduce, create a new md file and insert three blank lines, followed by a line containing 8 spaces. Select all text, then press backspace.  The issue only exists when the last line contains whitespace.

**Comment by syohex** [comment]
#167 have been merged. Could you check latest version ?

**Comment by jrblevin** [comment]
Seems fixed to me, so I'm closing this.  Please reopen if not.  As always, thanks for the report!
