### ISSUE TITLE
Don't fill code blocks

### ISSUE THREAD

**Issue by vermiculus** [jrblevin/markdown-mode#169]
Code is usually line-sensitive – it's inappropriate to fill them with `fill-paragraph`.

**Comment by syohex** [comment]
Could you show us example code which reproduces your issue ?

**Comment by vermiculus** [comment]
```elisp
(insert "```
hello
world
```")
(fill-region 0 (point-max))
```

**Comment by xiongtx** [comment]
This actually seems like a hard problem. 

It's easy to modify `paragraph-start` to stop filling code blocks formed by lines that begin with 4 or more spaces with the regexp `"    .*"`.

The trickier part is recognizing code blocks between two sets of triple tick marks. The `paragraph-start` and `paragraph-separate` regexps only apply to a single line, so in the following situation (where `|` indicates point):

    ```
    |foo
    bar
    ```
    
you have no way of knowing that you're in a code block and not a regular paragraph.

GitHub also stupidly chose start and end delimiters to be the same, so regexp-based solutions are in for a world of pain. The syntax was clearly designed for parsing, not text matching.

**Comment by vermiculus** [comment]
Yep – I encountered the same complications when I tried to implement. I think the solution is going to have to re-implement commands like `fill-paragraph` entirely.

**Comment by jrblevin** [comment]
I was able to fix this without reimplementing `fill-paragraph` entirely.  Instead, a custom `fill-paragraph-function` blocks filling when in a code block.  There is a test case, but bet me know if you see any problems.

**Comment by jrblevin** [comment]
Actually, I just realized that the original report was about `fill-region` not `fill-paragraph`.  This only fixes the latter.  Oddly, `fill-region` seems to work on its own, via `fill-region-as-paragraph`, without calling out to `fill-paragraph`.

Even in `emacs-lisp-mode`, if one uses `fill-region` it fills code as paragraphs.  For example, start with this in the buffer:

``` lisp
(defun markdown-show-version ()
  "Show the version number in the minibuffer."
  (interactive)
  (message "markdown-mode, version %s" markdown-mode-version))
```

Then issue `(fill-region (point-min) (point-max))` and you're left with a jumbled mess:

```
(defun markdown-show-version () "Show the version number in the
minibuffer."  (interactive) (message "markdown-mode, version %s"
markdown-mode-version))
```

**Comment by vermiculus** [comment]
I would've thought `fill-region` would be based on `fill-paragraph` (or perhaps vice-versa). Should this be reported as an Emacs bug?

**Comment by jrblevin** [comment]
I agree--I'm surprised too.  It does seem to be a common issue, so maybe a bug report is warranted.  For example, I checked `latex-mode`.  It rightly won't fill a `verbatim` environment when `fill-paragraph` (`M-q`) is called directly, but `fill-region` doesn't respect `verbatim`.
