### ISSUE TITLE
Add table-editing features akin to orgtbl

### ISSUE THREAD

**Issue by Ambrevar** [jrblevin/markdown-mode#171]
Markdown table extension is frustratingly close to orgtbl: only the `+` differs at intersections.

orgtbl is terrifically convenient in my opinion, I would love to see similar editing features for markdown-mode.

I found a few similar discussions:
- http://stackoverflow.com/questions/14275122/editing-markdown-pipe-tables-in-emacs
- jgm/pandoc#519.

**Comment by jrblevin** [comment]
I'm also interested in this, but after looking into it I'm not sure of the best way to proceed.  My first thought was to add an option for `markdown-mode` to automatically load `orgtbl-mode`.  Then we could either 1) "advise" the realignment functions to reformat the tables (i.e., changing `-+-` to `-|-` for starters) or 2) rebind the most important `orgtbl-mode` keys like `C-c |` and `C-c C-c` to wrappers that call out to `orgtbl` and then do the reformatting.

What I realized quickly is that when loading `orgtbl-mode`, the minor mode keymap overrides the `markdown-mode` keymap, so a lot of things are unavailable.  For example, `markdown-mode` defines several keys under the `C-c C-c` prefix.  Yet, if I change `orgtbl-mode-map` directly to remove `C-c C-c`, then it would be changed everywhere `orgtbl-mode` is used (not just in the `markdown-mode` buffer).  Does anyone know the best way to handle this?

**Comment by Ambrevar** [comment]
I don't think making use of the high-level org-mode functions is a good idea.
I guess going lower level is the way to go. If org-mode's API is poorly design, that might mean reimplementing everything from scratch...

**Comment by jrblevin** [comment]
Yeah, I also don't like the idea, but it seemed like the fastest way to get something working for people. If it means re-implementing it, then I likely won't be doing that in the foreseeable future (too many more fundamental things to do on `markdown-mode`). Perhaps for now I'll write up some directions about a simple setup with `advice` that does 90% of what most people need through `orgtbl`, which can be toggled on and off as needed.
