### ISSUE TITLE
Spurious bold/italic in inline code

### ISSUE THREAD

**Issue by peniblec** [jrblevin/markdown-mode#172]
Hi! I have noticed that in blocks such as headers or blockquotes,
inline code containing bold/italic markers will behave as if the
inline code markers were not here. IOW text between asterisks or
underscores will be shown as bold/italic.

Some test cases I wrote:

``` lisp
(ert-deftest test-markdown-font-lock/snake-case-in-code-in-heading ()
  "Test underscores in inline code in headings"
  (markdown-test-string
   "# Title with `snake_case_code`"
   (should-error (markdown-test-range-has-face 21 24 markdown-italic-face))))

(ert-deftest test-markdown-font-lock/stars-in-code-in-heading ()
  "Test asterisks in inline code in headings"
  (markdown-test-string
   "# Title with `char** foo, int* bar`"
   (should-error (markdown-test-range-has-face 20 29 markdown-italic-face))))

(ert-deftest test-markdown-font-lock/stars-in-code-in-blockquote ()
  "Test asterisks in inline code in blockquote"
  (markdown-test-string
   "> Quote with `**stars**`"
   (should-error (markdown-test-range-has-face 17 21 markdown-bold-face))))
```

(Not sure that `(should-error (markdown-test-range-has-face …))` is
the most idiomatic way to test this, though I do mean to check the
_absence_ of bold/italic fontification)

I tried poking around in the code, but I could not pinpoint the cause
of the issue. Some things I noticed, which may or may not be related:
- `(markdown-match-bold (point-at-eol))` will match these strings when
  the point is at the beginning of each line:
  
  ```
    # Title with **bold**
    > Blockquote with **bold**
  ```
- In similar conditions, `(markdown-match-code (point-at-eol))` fails
  to match, though `(markdown-match-code (point-max))` does match:
  
  ```
    # Title with `inline`
    > Blockquote with `inline`
  ```

That's all I have for now.

**Comment by jrblevin** [comment]
Thank you. I have added these test cases (although I screwed them up the first time) and am working on a fix.

I'm not sure which way best, but previously in such cases I used `(should-not (markdown-range-property-any …))`, so that's the approach I used again.

**Comment by jrblevin** [comment]
I think these should be fixed now, but please let me know if not.

**Comment by peniblec** [comment]
As far as I can tell, these bugs are now fixed. Thanks a lot!

I just have a comment about one of the tests: while fixing `test-markdown-font-lock/stars-in-code-in-blockquote` in c812747afe08e328a8ec918cc911bcc72b6a7856, a check changed from `(markdown-test-range-has-face 17 21 markdown-bold-face)` to `(markdown-range-property-any 17 21 'face '(markdown-italic-face))`; I think the check should still read `markdown-bold-face`. If I checkout 2.2 to reproduce the issue, and <kbd>C-u C-x =</kbd> on the word "stars", the faces applied are `(markdown-blockquote-face markdown-bold-face)`.

I watched the commit log this past month and I have to say, the amount of work you have put on markdown-mode is incredible! Thank you for working so hard on this package. Clickable links, code block fontification/edition are wonderful quality-of-life improvements; I played around with markup-hiding and even though I do not see myself using it all that much, it does look very polished!

**Comment by jrblevin** [comment]
Thanks for spotting that! I was fixing several problems related to italics last night and that slipped through. It shouldn't be italic *or* bold, so I updated the test to check the absence of both.

I'm glad you like the recent changes. I'm glad to be able to give the package some needed attention lately!
