### ISSUE TITLE
Bug in strong font-locking

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#176]
I create a list item as follows, can be a brand new list:
- **foo** **bar**

foo is shown in bold, bar is shown in italics. The first 7 asterisks are shown in markdown-markup-face the last one in regular font. As shown:
![screen shot 2016-11-15 at 1 23 43 pm](https://cloud.githubusercontent.com/assets/1999190/20318536/9aadd804-ab38-11e6-8db7-60754c72c75a.png)

I'm using the latest, markdown-mode-version is 2.1

**Comment by jrblevin** [comment]
I think this should be fixed now, but please let me know if not.
