### ISSUE TITLE
How can I preview markdown with table and code~~

### ISSUE THREAD

**Issue by jaylinwang** [jrblevin/markdown-mode#177]
## table

raw txt :

![image](https://cloud.githubusercontent.com/assets/4530355/21000633/edd17f60-bd56-11e6-9af9-5c5121857760.png)

preview result:

![image](https://cloud.githubusercontent.com/assets/4530355/21000644/0d23fda2-bd57-11e6-88ab-4171f8dbddf9.png)

## code

raw text:
![image](https://cloud.githubusercontent.com/assets/4530355/21000664/232c2d54-bd57-11e6-97e7-9886bdff456f.png)

preview result:
![image](https://cloud.githubusercontent.com/assets/4530355/21000706/4f598fde-bd57-11e6-9a70-62c47096b686.png)

how can i have a preview result like that:
![image](https://cloud.githubusercontent.com/assets/4530355/21000745/80b4d28c-bd57-11e6-9ecb-a4b2858fa45a.png)

![image](https://cloud.githubusercontent.com/assets/4530355/21000761/8f34fd00-bd57-11e6-8a88-7592c5254a2d.png)

**Comment by cmal** [comment]
I have the same problem.
Does it need some plugins/extensions? Such as plugins to show table, do syntax highlighting and show toc?
Thanks!

**Comment by jaylinwang** [comment]
@cmal I fixed it use pandoc , you can try it

**Comment by cmal** [comment]
@jaylinwang Thanks. So you use pandoc to generate html? And what about theme rendering and syntax highlighting? I build a working version of my .emacs.d this afternoon. [here](https://github.com/cmal/.emacs.d)

**Comment by jaylinwang** [comment]
add the config:

```lisp
(setq markdown-command "pandoc -s -c {yourstyle.css} -f markdown -t html5 --mathjax --highlight-style pygments --standalone")
```
and you can see preview result for your want~~

@cmal

**Comment by cmal** [comment]
@jaylinwang  oh, good. Thanks! That's pretty clean.

**Comment by syohex** [comment]
Sorry late response.
Did you resolve this issue by yourself ?

If you still not resolve this issue ?
- How did you preview ? `M-x markdown-preview` ?

**Comment by jaylinwang** [comment]
@syohex thanks for your response.it's fixed 😄

**Comment by syohex** [comment]
Good.

**Comment by cmal** [comment]
I think this one also helps. https://github.com/shime/emacs-livedown
