### ISSUE TITLE
Preserve list indentation after RET

### ISSUE THREAD

**Issue by steckerhalter** [jrblevin/markdown-mode#179]
I have this code now mapped on <kbd>RET</kbd> in markdown-mode:

```cl
  (defun my-markdown-ret ()
    "Preserve list indentation after RET in markdown-mode."
    ;; improved version of http://emacs.stackexchange.com/a/14642
    (interactive)
    (if-let ((bounds (markdown-cur-list-item-bounds))
             (beg (car bounds))
             (end (cadr bounds))
             (indent (cadddr bounds))
             (text (buffer-substring beg end)))
        (if (= (- end beg)
               indent)
            (progn
              (kill-region beg end)
              (markdown-enter-key))
          (call-interactively #'markdown-insert-list-item))
      (markdown-enter-key)))
```

I think it is quite convenient... maybe you would like to integrate it in some way?

**Comment by steckerhalter** [comment]
@jrblevin nice, thanks for adding this

**Comment by jrblevin** [comment]
An update: I realized that this is not what you want to happen if you wrap lines yourself using <kbd>RET</kbd>.  You might want a multi-line list item, for example.  So, I added a new setting
to `markdown-indent-on-enter` in 9e10d57: it can be `nil`, `indent`, or `indent-and-new-item`.  You'll want it set to the latter:

```
(setq markdown-indent-on-enter 'indent-and-new-item)
```

**Comment by steckerhalter** [comment]
ok thanks for the notice
