### ISSUE TITLE
option to not surround header in atx hashes

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#18]
It'd be nice if we could choose not to surround a header with atx hashes, e.g.

```
## this is my header

instead of

## this is my header ##
```

However, markdown-mode seems to force it as you can see on [this line](https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L2594).

**Comment by jrblevin** [comment]
I've noted this as a feature request.

**Comment by blaenk** [comment]
Thanks!

**Comment by jonmountjoy** [comment]
See https://github.com/jrblevin/markdown-mode/pull/32, which provides this functionality.
