### ISSUE TITLE
Slow saving time

### ISSUE THREAD

**Issue by Ambrevar** [jrblevin/markdown-mode#182]
Version 2.1.

Working on a 400KiB+ document leads to slow saving times for me.
I sometime experience saving times as high as 1-2 seconds. For some reason, it only take 0.5s at the moment. It might depend on the content.

I have an old computer with a Code Duo and an SSD.

**Comment by syohex** [comment]
Do you enable live preview mode ? `markdown-mode`  uses `after-save-hook` for only live preview. So if you don't enable live preview mode, it is not markdown-mode issue.

**Comment by Ambrevar** [comment]
My bad, I did not test properly before submitting this issue. I had this left behind:
```
(add-hook 'before-save-hook 'delete-trailing-whitespace)
```
So it's not Markdown-mode related. Any idea how to speed this up though?

**Comment by syohex** [comment]
0. Modify buffer
1. `M-x profiler-start`
2. `M-x save-buffer`
3. `M-x profiler-report`
4. Find bottle neck

**Comment by Ambrevar** [comment]
I did not know emacs had a profiler, thanks for this great tip!
That being said, I know the bottleneck, it's `delete-trailing-whitespace` since it has to parse a 400k+ file.
I was just wondering if there is a way to achieve the same effect without a performance hit, but I might just ask for the impossible...
