### ISSUE TITLE
Any options to embed CSS in HTML in export

### ISSUE THREAD

**Issue by oracleyue** [jrblevin/markdown-mode#183]
Are there options that allows me to export `.md` into HTML with CSS embedded? (I mean, copying the CSS sources into HTML, instead of a link.)
If not, any easy idea to hack it? Just certain hints. Many thanks!

**Comment by jrblevin** [comment]
Are you aware of the `markdown-css-paths` setting? It is a list of CSS files to link to in XHTML output.  Also, there is `markdown-xhtml-header-content`, for additional content to include in the XHTML `<head>`. You can include a style block there if needed.

**Comment by jrblevin** [comment]
Just to be clear, to use `markdown-xhtml-header-content` you can add something like this to your init file (or customize the variable with <kbd>M-x customize</kbd>):

``` lisp
(setq markdown-xhtml-header-content
      "<style type='text/css'>
a { text-decoration: none; }
a:hover { text-decoration: underline; }
</style>")
```

This will work as long as your Markdown processor produces "snippets" (to which `markdown-mode` adds a header, etc.), as opposed to a complete XHTML document.

If you want to do something more advanced, you can use the export hooks: `markdown-before-export-hook` and `markdown-after-export-hook`.
