### ISSUE TITLE
Font-locking code blocks

### ISSUE THREAD

**Issue by xiongtx** [jrblevin/markdown-mode#185]
## Expected behavior

There should be a way to font-lock code blocks for supported languages, similar to Orgmode's `org-src-font-lock-fontify-block`.

This *may* be particular to `gfm-mode`.

## Actual behavior

There is no such feature.

## Steps to reproduce (recipe)

N/A

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Versions of `markdown-mode`, Emacs, OS, etc.

- `markdown-mode`: `2.1`
- Emacs: `25.1.50.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by Fuco1** [comment]
I've actually come looking for exactly this feature.

This is extremly simple to implement, I've done it for sphinx: https://github.com/Fuco1/sphinx-mode/blob/master/sphinx-src.el  The code could be copied 1:1 or extracted as an extra dependency.

**Comment by jrblevin** [comment]
Thanks for the pointer @Fuco1! I have something working and hope to push it soon...

<img width="339" alt="screen shot 2017-06-08 at 11 03 09 am" src="https://user-images.githubusercontent.com/12706530/26935547-418a02ae-4c3a-11e7-8eeb-67ab29e75c3b.png">

**Comment by jrblevin** [comment]
This is in the `master` branch now. The main commit is 76ccd82. It's disabled by default, but set `markdown-fontify-code-blocks-natively` to `t` and reload to see it. I'll add a toggle key and command soon...

**Comment by jrblevin** [comment]
Update:

* Toggle added in 7e37293, bound to <kbd>C-c C-x C-f</kbd>.
* Typo in comment found by @xiongtx fixed in 1d77e06.
* Compatibility with Emacs < 24.4 fixed in ef314c8 and 5570cfc.

**Comment by jrblevin** [comment]
I closed this accidentally, but I'll leave it that way for now. Let me know if you have any other comments or if anything doesn't work right.

**Comment by jrblevin** [comment]
Update: With 740bd6a, native fontification works for tilde-fenced code blocks too.
