### ISSUE TITLE
Meta-q collapses paragraphs within blockquote

### ISSUE THREAD

**Issue by meygerjos** [jrblevin/markdown-mode#186]
### Minimal example

Initial file:
```
> Foo
>
> Bar
```

After <kbd>M-q</kbd>, this becomes:
```
> Foo Bar
```

This shouldn't happen, because, according to [this guide](http://brettterpstra.com/2015/08/24/write-better-markdown/), "the most common way to make a multi-paragraph block quote is to use a greater than symbol on each blank line".

**Comment by jrblevin** [comment]
Fixed in 858a9bd6a33bcecdb99fae71f44a811ddcb737cb.
