### ISSUE TITLE
Wrong-type-argument stringp nil for live preview

### ISSUE THREAD

**Issue by piojanu** [jrblevin/markdown-mode#187]
Hi!
I get error from title when I turn emacs to fullscreen (1) or I split window (2) and try to execute any of markdown-live-preview command.
It works properly only once when I start fresh emacs and immediately execute command.

Debug:
(1) When executed with name from minibuffer (M-x)
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
expand-file-name(nil)
eww-open-file(nil)
markdown-live-preview-window-eww(nil)
markdown-live-preview-export()
markdown-live-preview-mode(toggle)
call-interactively(markdown-live-preview-mode record nil)
command-execute(markdown-live-preview-mode record)
helm-M-x(nil #("markdown-live-preview-mode" 0 26 (match-part "markdown-live-preview-mode")))
call-interactively(helm-M-x nil nil)
command-execute(helm-M-x)

(2) When execute with shortcut
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  markdown-live-preview-remove()
  markdown-live-preview-mode(toggle)
  call-interactively(markdown-live-preview-mode nil nil)
  command-execute(markdown-live-preview-mode)

or when execute with name from minibuffer (M-x)

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  markdown-live-preview-remove()
  markdown-live-preview-mode(toggle)
  call-interactively(markdown-live-preview-mode record nil)
  command-execute(markdown-live-preview-mode record)
  helm-M-x(nil "markdown-live-preview-mode")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

Anyone has an idea what is wrong?

Thanks!

**Comment by piojanu** [comment]
I'm using pandoc and it turned out, that I had missing packages for LaTeX (which is used in my markdown files). After installing texlive-base, texlive-fonts-recommended and texlive-latex-recommended everything works just fine!

**Comment by jrblevin** [comment]
Great, glad to hear it's working! Thanks for following up.
