### ISSUE TITLE
(wrong-type-argument sequencep variable-pitch)

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#193]
Just upgraded from melpa and now I get the following error entering markdown-mode:

Debugger entered--Lisp error: (wrong-type-argument sequencep variable-pitch)
  append(variable-pitch (font-lock-function-name-face))
  markdown-make-header-faces()
  markdown-mode()

It fails for me when markdown-header-scaling is t.

**Comment by jrblevin** [comment]
Thanks for this report. The problem was introduced a couple of days ago in d587180, but it slipped past me at the time.

**Comment by galeo** [comment]
I'm sorry to introduce this bug by mistake, the code fix I use privately is 
```elisp
  (defface markdown-header-face
    `((t (:inherit (font-lock-function-name-face
                    ,@(when markdown-header-scaling 'variable-pitch))
                   :weight bold)))
    "Base face for headers."
    :group 'markdown-faces)
```
Also, thanks for this report.

**Comment by jrblevin** [comment]
No problem, @galeo. It looked fine to me at the time! Thanks again for your patch.
