### ISSUE TITLE
`markdown-reload-extensions` should ensure fontification

### ISSUE THREAD

**Issue by xiongtx** [jrblevin/markdown-mode#195]
## Expected behavior

Refontifying `markdown-mode` buffer should ensure that fontification completes.

## Actual behavior

Due to a lack of `font-lock-ensure` in `markdown-reload-extensions`, sometimes markdown buffers are not completely fontified before being displayed.

E.g.

![image](https://user-images.githubusercontent.com/1624090/26999687-9f7ae9ee-4d54-11e7-84b1-f7e4b0b0e6f9.png)

Note that the beginning of the fence is not fontified.

This can be prevented by calling `font-lock-ensure` after `font-lock-refresh-defaults` in `markdown-reload-extensions`.

## Versions of `markdown-mode`, Emacs, OS, etc.

- `markdown-mode`: `20170609.942`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by jrblevin** [comment]
Thanks for reporting this. I'm aware and will investigate. Seems to be due to an inconsistency in setting the block open properties--whether the newline gets or not.

**Comment by jrblevin** [comment]
I think that should do it, but let me know if you still see this.
