### ISSUE TITLE
Comments and file variables

### ISSUE THREAD

**Issue by vincentb1** [jrblevin/markdown-mode#198]
Hello,
I tried to make some comment in order to set some file variables like this:

```
[comment]: # ( Local Variables: )
[comment]: # ( coding: utf-8	)
[comment]: # ( End:		)
```
But it did not work, my default encoding was applied instead of the required utf-8.
I saw that you configure `comment-start` and `comment-end` like in HTML (however see this [stackoverflow discussion](https://stackoverflow.com/questions/4823468/comments-in-markdown)), so tried this then :

```
<!-- Local Variables: -->
<!-- coding: utf-8	-->
<!-- End:		-->
```

And it did not work either, finally I had to make this in my init file:
``` elisp
(modify-coding-system-alist 'file "\\.m\\(d\\|arkdown\\)\\'" 'prefer-utf-8)
```
Maybe I am wrong in using file variables, I know that this should not be used to make person specific settings, but in this case coding scheme is file specific, not user specific, so I guess that I am not overusing this feature.

**Comment by jrblevin** [comment]
Indeed, HTML comments should work.  Your example above works fine for me. It has to be at the end of the file.  Or you can put this at the beginning:

``` HTML
<!-- -*- coding: utf-8 -*- -->
```

Either way I do it, it is effective as soon as I save the file and is recognized when I open the file.

**Comment by vincentb1** [comment]
It is quite strange indeed.  I commented out this line

```elisp
(modify-coding-system-alist 'file "\\.m\\(d\\|arkdown\\)\\'" 'prefer-utf-8)
```
from my init file, and then I tried this with re-opening an Emacs :

```
[comment]: # ( Local Variables: )
[comment]: # ( coding: utf-8	)
[comment]: # ( eval: (message "Coucou")	)
[comment]: # ( End:		)
```

(Coucou is like Hello in French), and I got the message Coucou &mdash; which means that actually the file variables are read, however, the file encoding was wrong.

I am having a development Emacs (GNU Emacs 25.2.1 (i686-pc-mingw32) of 2017-02-06), so I will re-build it, and try again to see what happens, 

What is your default encoding for reading files, is that latin1 like me ?
Do you have correct encoding on this [file](https://framagit.org/latex-pourquoi-comment/lpc-articles/blob/develop/CONTRIBUTING.md) ? This file is the one on which I me the issue.

**Comment by jrblevin** [comment]
My default is utf-8 everywhere, so I tested with `coding: latin-1` to verify that the coding was indeed changed by the local variable.

I cannot reproduce this, so can you please try testing the file-local `coding` setting with another mode and also try reproducing the issue with `emacs --no-init`?  It could be related to part of your local configuration.

**Comment by vincentb1** [comment]
I tried to open [the file](https://framagit.org/latex-pourquoi-comment/lpc-articles/blob/develop/CONTRIBUTING.md) with `emacs -q`, and I got the same problem.
So, my conclusion is that your package is not to blame.

Sorry for the disturbance. Because the `comment-start` and `comment-end` variables set to HTML style, and because the `[comment]: # (`&hellip;`)` style of comment is not fontified like comments, I thought that there was some interaction with markdown-mode package.

**Comment by jrblevin** [comment]
Loading the test file in `fundamental-mode`, the issue seems to be related to the presence of the `[` character. If you remove that character from each line, it works fine. Perhaps bug in `hack-local-variables` in files.el? I'm sorry, but I don't have time to look into it further, but I'd be curious to know if you do manage to fully track it down.

**Comment by vincentb1** [comment]
I will keep you informed of the outcome. Yes this is a bug in Emacs, I have rebuilt it today, and it is still there.

**Comment by vincentb1** [comment]
Hello Jason,

The bug in Emacs is fixed. See [Emacs bug 27391](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27391).

The correction is [here](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c3813b2aa8d2f5a625195fdbbfe6a01a602d7735).

**Comment by jrblevin** [comment]
Great, thanks for following up. That was very fast!

So it was indeed a square bracket problem, in the regex. I was even looking for something like that, but I totally missed it.  For some reason I thought the problem was further along in the code, when processing the variables. Glad to hear it's fixed!
