### ISSUE TITLE
Edit link url in place

### ISSUE THREAD

**Issue by novakboskov** [jrblevin/markdown-mode#199]
First things first, thank you for all the job you've done lately on `markdown-mode`. :)

Links are now rendered on a different way. They use link simbol between `()` instead of plain text. How can I view/edit link url now?

**Comment by jrblevin** [comment]
Thanks!

An interactive link editing function is coming soon, but for now there are two options:

1. Toggle off URL hiding (<kbd>C-c C-x C-l</kbd>) and then edit the URL as usual.

2. Delete one of the parentheses or square brackets around the link, at which point the URL will be visible, then add it back.

**Comment by jrblevin** [comment]
I added `markdown-insert-link`, which is a general function for inserting and editing several link types.  For now, it replaces the old link insertion commands (separate for each type) such as <kbd>C-c C-a l</kbd>.  Soon, I'll be revising the keybindings and will give it a more prominent placement.
