### ISSUE TITLE
Recognize definition list definitions as paragraph starts

### ISSUE THREAD

**Issue by marijnh** [jrblevin/markdown-mode#20]
Using a line starting with a colon to denote a definition list is a widely used Markdown extension. Adding the following line to `paragraph-start` allows one to fill such definition paragraphs without having them collapse with the previous line (the defined term).

```patch
diff --git a/markdown-mode.el b/markdown-mode.el
index e61ef78..7ef0889 100644
--- a/markdown-mode.el
+++ b/markdown-mode.el
@@ -5090,6 +5090,7 @@ before regenerating font-lock rules for extensions."
                     "[ \t]*[*+-][ \t]+" ; unordered list item
                     "[ \t]*\\(?:[0-9]+\\|#\\)\\.[ \t]+" ; ordered list item
                     "[ \t]*\\[\\S-*\\]:[ \t]+" ; link ref def
+                    "[ \t]*:[ \t]+" ; definition
                     )
                   "\\|"))
   (set
```

**Comment by vyp** [comment]
+1 The relevant reference if you didn't already know: http://pandoc.org/README.html#definition-lists.

**Comment by jrblevin** [comment]
Applied--thanks for the patch.
