### ISSUE TITLE
`markdown-live-preview-mode` errors for buffers without file

### ISSUE THREAD

**Issue by xiongtx** [jrblevin/markdown-mode#200]
## Expected behavior

`markdown-live-preview-mode` should gracefully fail for markdown buffers with no backing file.

## Actual behavior

`markdown-live-preview-mode` throws a `wrong-type-argument` error.

This is because `(markdown-live-preview-get-filename)` is nil for such buffers, which causes `markdown-live-preview-remove` to call `file-exists-p` on nil.

## Steps to reproduce (recipe)

1. Create a `markdown-mode` buffer without a backing file.
2. Call `markdown-live-preview-mode`

## Backtraces if necessary (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  (if (file-exists-p outfile-name) (progn (delete-file outfile-name)))
  (let ((outfile-name (markdown-live-preview-get-filename))) (if (file-exists-p outfile-name) (progn (delete-file outfile-name))))
  (progn (let ((outfile-name (markdown-live-preview-get-filename))) (if (file-exists-p outfile-name) (progn (delete-file outfile-name)))))
  (if (eq markdown-live-preview-delete-export (quote delete-on-destroy)) (progn (let ((outfile-name (markdown-live-preview-get-filename))) (if (file-exists-p outfile-name) (progn (delete-file outfile-name))))))
  markdown-live-preview-remove()
  (if markdown-live-preview-mode (markdown-display-buffer-other-window (markdown-live-preview-export)) (markdown-live-preview-remove))
  ...  
```

## Describe versions of `markdown-mode`, Emacs, OS, etc.

- `markdown-mode`: `20170614.1152`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by jrblevin** [comment]
Merged. Thanks for the report and patch!
