### ISSUE TITLE
Infinity sign in place of image path and url address

### ISSUE THREAD

**Issue by piojanu** [jrblevin/markdown-mode#202]
Hi!

I've reinstalled markdown-mode yesterday and I have problem with strange behavior. It changes all image paths and url addresses to infinity sign, so instead of `![some image](path/to/image/)` I got `![some image](∞)`. The same for links: `[some link](∞)`. Because of this, I'm unable to edit path/address because I can't see it.

Please help,
Piotr

**Comment by jrblevin** [comment]
You are on the development branch and URL hiding is a new feature. You can toggle it with <kbd>C-c C-x C-l<kbd>. Try upgrading again today, just to be sure you have the necessary commits, and pressing <kbd>C-c C-l</kbd> when the point is at the link to edit interactively.  Also see #199 for other options.

**Comment by piojanu** [comment]
It's a feature not a bug :) Thanks!

But shouldn't be hiding turned off by default? When I open emacs links are hidden, even if I left them visible.

**Comment by jrblevin** [comment]
I wasn't sure, so I followed the precedent of `org-mode` and created a `defcustom` (`markdown-hide-urls`) and turned it on by default.  The state isn't tracked persistently on a file-by-file basis, rather, it's just the default state on open.

I was on the fence about enabling it by default, so I'll re-evaluate.  I'm playing around with ways to display a helpful message in the minibuffer. I'll either do that, disable it by default, or maybe both. If anyone feels strongly about the best approach here, feel free to chime in and discuss.

**Comment by piojanu** [comment]
Can you tell me if there is a way to disable it? What could I add to my configuration?

If you ask me, I'd rather go for opt-in policy. Turn it off by default and if anyone want it, it should be somehow configurable.
I was very confused when I saw those infinity symbols and google didn't help. Panic mode enabled :D
