### ISSUE TITLE
Feature request: display URLs in minibuffer

### ISSUE THREAD

**Issue by paxperscientiam** [jrblevin/markdown-mode#203]
Hello @jrblevin, I have a feature request.

Provide a setting that allows for the display of obfuscated URLs in minibuffer when the following conditions met:
* cursor at link
* `markdown-hide-urls` set to true

What do you think?

Thanks for the mode!

**Comment by jrblevin** [comment]
Thanks, I like that idea. In fact, I'm already working on it! Hopefully it will be ready in the next few days...

**Comment by jrblevin** [comment]
I found an easier way to do it than what I was originally trying, so it was faster than expected.  Let me know if you have comments or suggestions.

Since it is based on `eldoc`, if you're running Emacs 25.1 or later `eldoc` can be disabled globally by adding this to your init file:

``` emacs-lisp
(global-eldoc-mode -1)
```

Alternatively, you could disable `eldoc` only in `markdown-mode` like so:

``` emacs-lisp
(defun my-markdown-mode-hook ()
  (setq-local eldoc-documentation-function #'ignore))
(add-hook 'markdown-mode-hook 'my-markdown-mode-hook)
```

I should also note that hidden URLs and references can be seen by hovering over the link with the mouse pointer.

**Comment by paxperscientiam** [comment]
@jrblevin Nice work!

Trying it out now. I love how markdown-mode will now indicate the shortcut for editing the URL as well as displaying the URL. Neat.

Is editing the URL from the minibuffer new? I may have just overlooked that feature.

> I should also note that hidden URLs and references can be seen by hovering over the link with the mouse pointer.

I could be wrong, but I don't think that works in text terminals (what I use).

**Comment by jrblevin** [comment]
> Is editing the URL from the minibuffer new? I may have just overlooked that feature.

Only a couple of days old; I added it to help with editing when URLs are hidden.

> > I should also note that hidden URLs and references can be seen by hovering over the link with the mouse pointer.
> I could be wrong, but I don't think that works in text terminals (what I use).

You're not wrong there. Mainly I just mentioned it for the benefit of any future readers looking into the new features.

**Comment by paxperscientiam** [comment]
> You're not wrong there. Mainly I just mentioned it for the benefit of any future readers looking into the new features.

Ah, for posterity. Nice work 👍
