### ISSUE TITLE
Installing markdown-mode with MELPA package manager

### ISSUE THREAD

**Issue by bphiett** [jrblevin/markdown-mode#204]
I've attempted to install markdown-mode using the MELPA package manager

I added the following to my .emacs:

(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/"))
(package-initialize)

and then ran M-x package-install RET markdown-mode RET

But got the following error message:

https://stable.melpa.org/packages/markdown-mode-2.1.el: Not found

Looks like its looking for ver 2.1 where it should be looking for ver 2.2, but I'm not sure how to correct for that?

**Comment by jrblevin** [comment]
I haven't changed the release workflow, and the correct version is linked to when I visit the webpage: <https://stable.melpa.org/#/markdown-mode>. Did you `M-x package-refresh-contents` first?

**Comment by bphiett** [comment]
brilliant! package-refresh-contents did the trick..
many thanks
 

    On Tuesday, 20 June 2017, 16:20, Jason Blevins <notifications@github.com> wrote:
 

 I haven't changed the release workflow, and the correct version is linked to when I visit the webpage: https://stable.melpa.org/#/markdown-mode. Did you M-x package-refresh-contents first?—
