### ISSUE TITLE
function made obsolete and removed, without a defalias

### ISSUE THREAD

**Issue by duianto** [jrblevin/markdown-mode#206]
I learned about the `make-obsolete` function recently, so correct me if I'm wrong, but it seems like 
a `defalias` should be added when a function is removed and made obsolete.

These functions were made obsolete recently:
```elisp
(make-obsolete 'markdown-insert-inline-link-dwim 'markdown-insert-link "v2.3")
(make-obsolete 'markdown-insert-reference-link-dwim 'markdown-insert-link "v2.3")
```
source: https://github.com/jrblevin/markdown-mode/commit/c1408d2b9ef2fba4723302e72f23eddaf1d3ecf4#diff-278f54adc40fe5d8df000a8bd99c36e1R4209

When `markdown-insert-inline-link-dwim` is called:
- In Spacemacs:
`command-execute: Wrong type argument: commandp, markdown-insert-inline-link-dwim`
- In Emacs with `markdown-mode` enabled:
`Debugger entered--Lisp error: (void-function markdown-insert-inline-link-dwim)`

Here's an example of how the which-key package made this function obsolete:
```elisp
(defalias 'which-key-declare-prefixes 'which-key-add-key-based-replacements)
(make-obsolete 'which-key-declare-prefixes
               'which-key-add-key-based-replacements
               "2016-10-05")
```
source: https://github.com/justbur/emacs-which-key/commit/458c8d97fb03e926422516ea79198ee18a75dd18#diff-7853a5b2c77b7d409086497a8fc18fdeR773

The obsolete function `which-key-declare-prefixes` works as expected since it's calling the defalias'ed `which-key-add-key-based-replacements` function. And when the obsolete function is described, then it states that the function is obsolete since that date, and it suggests that one should use the new function.

I noticed that there also is a combined function: `define-obsolete-function-alias` that defines an alias and makes it obsolete.
source: http://www.gnu.org/software/emacs/manual/html_node/elisp/Obsolete-Functions.html

**Comment by jrblevin** [comment]
Good catch, thanks!
