### ISSUE TITLE
ps-print-buffer-with-faces prints hidden markup

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#208]
So I have markup hidden and am using proportional heading fonts and the buffer looks nice. I call ps-print-buffer-with-faces and what prints includes the # in headers and - in lists instead of pretty bullets. Headings were shown in a different color that matched the face correctly but the size of the font was the same as other text. A link prints as just the link text and not the URL or the square brackets or parens so that's nice. I'm not sure if this is expected or not but it would have been nice to see the prettified hidden markup version.

I'm on a mac using the macport and I know printing is usually complicated. I don't normally care, but I hit the print keybinding by accident and saw what came out of the printer. I thought I'd mention it to see if someone could reproduce.

I suspect this is a limitation/bug of ps-print, that it doesn't know how to deal with display properties. Comments say it supports not printing invisible text, but it doesn't appear to be in the code other than in ps-plot-with-face which I don't see called. Maybe it's worth some text in a comment or help string to say printing of hidden markup doesn't work.

**Comment by jrblevin** [comment]
Thanks for letting me know. Indeed, the markup hiding is really intended only for display. `ps-print` seems to be long out of date, at least in terms of checking text properties (`display`, `invisible`, and so on).  I also checked `htmlfontify-buffer` and it also includes the invisible text. Maybe one day `markdown-mode` will produce output based on it's own parsing of the buffer, but until then the best way to print would seem to be Markdown -> LaTeX -> PDF (e.g., via Pandoc) or Markdown -> HTML with a nice stylesheet.
