### ISSUE TITLE
Editing "hidden" URL block causes adjacent blocks to be revealed

### ISSUE THREAD

**Issue by paxperscientiam** [jrblevin/markdown-mode#209]
Here's an interesting bug:

Consider a buffer with this text:
````markdown
[site1](http://site1.com)
[site2](http://site2.com)
[site3](http://site3.com)
````

Given the above content and given markdown-mode is configured such that `markdown-hide-urls` is set to true, removing the closing parenthesis on the first block will cause said block *and* all subsequent blocks to "open". That is, the URLs will no longer be hidden for blocks that otherwise should be.

This appears to be the case regardless of what other content is on the lines.

**Comment by jrblevin** [comment]
Interesting. It's a question of how to parse this:

```
[site1](http://site1.com
[site2](http://site2.com)
[site3](http://site3.com)
```

If you run it through the [Markdown dingus](https://daringfireball.net/projects/markdown/dingus), for example, you get a link with text `site1` and URL `http://site1.com
[site2](http://site2.com`. So, the current behavior is probably better than the alternative of gobbling up and hiding the second link automatically.  That being said, other implementations will keep the second two links intact, which is perhaps what `markdown-mode` should do for editing purposes.

**Comment by jrblevin** [comment]
Well, this part is a bug no question. When the broken link is present, I'm getting a font-lock error:

```
Error during redisplay: (jit-lock-function 527) signaled (wrong-type-argument number-or-marker-p nil)
```

**Comment by paxperscientiam** [comment]
I can confirm that this fix works on my end 👍 💯
