### ISSUE TITLE
Display property getting set to nil in EIN buffers with markdown cells

### ISSUE THREAD

**Issue by millejoh** [jrblevin/markdown-mode#212]
Honestly this one has me totally baffled, so I opening this issue in the hopes that someone who understands Emacs and markdown-mode better than I can provide some useful comments.

For background see millejoh/emacs-ipython-notebook#221. The problem occurs when `ein:notebook-modes` is set to `ein:notebook-multilang-mode` and when markdown-mode installed.

I didn't write or design the code for ein:notebook-multilang-mode, but it appears it works similar to `org-src-font-lock-fontify-block` and works as follows (if I understand the code correctly):

 1. Copies the contents of the cell to a temporary buffer.
 2. Sets the appropriate major mode (which in the case of a markdown cell is markdown-mode).
 3. Fontify's the buffer using `font-lock-ensure` (actually it currently uses `font-lock-fontify-buffer` but I plan to change that soon). 
 4. Put the font-lock-face properties of the fontified text back into the original cell in the notebook buffer.

The code in ein modifies the face property, but does not do anything to the display property.

I've tried calling `markdown-display-inline-images` and `markdown-toggle-inline-images` in the notebook buffer but neither of those does anything to help.

One user noted that commenting out the"Font lock" section seems to resolve the problem.

Any thoughts?

**Comment by jrblevin** [comment]
I don't use EIN, so I can't really test this, but I do have a hunch. Can you please try the following:

1. Update to the latest version of markdown-mode.el
2. Find line 8523, which reads `(add-to-list 'font-lock-extra-managed-props 'composition)`.  This is inside the mode definition.
3. Insert the following line just before the one above: `(make-local-variable 'font-lock-extra-managed-props)`.
4. Reload and see if the problem still happens.

**Comment by millejoh** [comment]
I did and it looks to have solved the problem. Good hunch. Thank you very much! I doubt i would have ever figured this out on my own.

**Comment by jrblevin** [comment]
Thanks for confirming—I'll push it to `master` soon.
