### ISSUE TITLE
quickly edit pipe tables in Emacs markdown-mode

### ISSUE THREAD

**Issue by yuanbohan** [jrblevin/markdown-mode#217]
Any plan for pipe table? [pipe table](https://stackoverflow.com/questions/14275122/editing-markdown-pipe-tables-in-emacs) exactly describe what I mean.

**Comment by jrblevin** [comment]
I think this is more or less the same request as #171 (although I'm not sure it mentions pipe tables specifically), so I think it's better to keep the discussion there. In short, this is a large, complex feature and I'm not likely to have time to implement it any time soon.  I'm happy to discuss and review patches if others want to contribute something though.
