### ISSUE TITLE
Markdown breaks some text properties

### ISSUE THREAD

**Issue by NicolasPetton** [jrblevin/markdown-mode#218]
This issue can be reproduced with for example `dired-hide-details`:

- Open a dired buffer
- Enable `dired-hide-details-mode`
- Open a markdown file (or turn on `markdown-mode` on any buffer)
- Invisible text is now displayed

I think it also affects strings with a `display` property.

The problem apparently comes from Line 8443 of `markdown-mode.el`, which globally adds `invisible` and `display` to `font-lock-extra-managed-props`.

**Comment by jrblevin** [comment]
Thanks for taking the time to report this. I just realized it myself. Does the proposed fix in #212 (making the variable buffer local) seem correct to you?

**Comment by DamienCassou** [comment]
I have the same problem.

**Comment by DamienCassou** [comment]
#212 fixes the problem for me.

**Comment by NicolasPetton** [comment]
@jrblevin I would rather use `setq-local`, instead of making `font-lock-extra-managed-props` buffer-local, which will have side-effects outside of markdown-mode and probably break other things.

What about something like this:

``` emacs-lisp
(setq-local font-lock-extra-managed-props
            (append font-lock-extra-managed-props
                    '(composition disiplay invisible)))
```

**Comment by NicolasPetton** [comment]
BTW, I saw a few

```emacs-lisp
(set (make-local-variable 'foo) 'bar)
```

In the definition of `markdown-mode`, which could be replace with `setq-local`.

**Comment by jrblevin** [comment]
> I would rather use setq-local, instead of making font-lock-extra-managed-props buffer-local, which will have side-effects outside of markdown-mode and probably break other things.

Thanks, indeed I meant to say "local" not "buffer local".

I had been avoiding `setq-local` for backwards compatibility, but I suppose it's probably time to give up support for Emacs 24.1 and 24.2 anyway.

**Comment by jrblevin** [comment]
This should be fixed now, but let me know if not. Thanks again for letting me know.

**Comment by NicolasPetton** [comment]
@jrblevin Thanks!
