### ISSUE TITLE
Make space after ``` customizable

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#219]
https://github.com/jrblevin/markdown-mode/commit/59a498618d9da3e9a938d7ee4013bf66056623c4 introduced a space after ```` ``` ````, which is valid but uncommon (e.g. https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) doesn't have it. Would be great if this behavior were customizable.

**Comment by insaneinside** [comment]
Additionally, the CommonMark specification allows [arbitrary meta-data](http://spec.commonmark.org/0.27/#info-string) after the opening code fence:

> The first word of the info string is typically used to specify the language of
> the code sample ... However, this spec does not mandate any particular
> treatment of the info string.

I personally use this to specify how a particular block of code should be rendered, for example ("this code block is erroneous" or "this code block is pretty okay"). 

A minor change to `markdown-regex-gfm-code-block-open` allows specification of metadata after the language without de-fontifying the entire code block, but better coloring and fontification of the metadata would be nice.

**Comment by jrblevin** [comment]
The development version (and possibly earlier ones to some extent) supports such arbitrary "info strings".
