### ISSUE TITLE
option to add space after gfm codeblocks

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#22]
Similar to #18, I would really really really appreciate it if we could set an option to add a space between the codeblock delimiter and the language, like this:

    ``` language

instead of:

    ```language

I know it's such a minor thing but this and #18 are the only things that really throw me off from this otherwise amazing markdown package (coming from vim, it's lightyears ahead). I love that I can type the three backticks and then it prompts me for the language automatically, as well as there being the other bind, but I always have to go and add the space manually to remain consistent with the rest of my documents, which breaks my rhythm.

I hope it's not that big of a deal to implement that you wouldn't mind to. I would _reaaally_ appreciate it!

**Comment by vyp** [comment]
Big +1, I know it's minor, but I much prefer the space as well.

**Comment by jrblevin** [comment]
This is fine by me. I wrote the code based on the GFM guide but the examples there don't use spaces. However, I verified that it does in fact allow spaces and so do other major processors like PHP Markdown Extra.

**Comment by jrblevin** [comment]
I changed things so that 1) a space is allowed for syntax highlighting and 2) a space is added for newly created gfm code blocks. See 59a4986.

**Comment by vyp** [comment]
Thanks!

**Comment by blaenk** [comment]
Amazing. Thanks!
