### ISSUE TITLE
Bold markers mess up italics detection

### ISSUE THREAD

**Issue by peniblec** [jrblevin/markdown-mode#223]
Hi!

I have been trying to cook up a patch for a fontification issue I have with lines containing, in order, bold, then regular, then italic text. Everything from the last bold marker to the last matching italic marker gets fontified as italic:

![bold-italics](https://user-images.githubusercontent.com/1415037/28105745-1504e62e-66e1-11e7-80e5-6efc246d5552.png)

The recipe for this screenshot was:

- `emacs -Q bold-italics.md`
- <kbd>M-x</kbd> `load-file markdown-mode/markdown-mode.el`
- <kbd>M-x</kbd> `revert-buffer`

The left window loaded the current master as of this writing, the right window loaded [my branch]. I added those lines to the test suite.

`make test` tells me I broke italic links (`test-markdown-font-lock/italics-link`), so my approach was too simplistic. I took a look at `markdown-inline-code-at-pos` and AFAICT, an equivalent function for bold text would allow `markdown-match-italic` to distinguish between end-of-bold and start-of-italic asterisks.

At this point I figured it would be more productive to post an issue and get informed opinions and/or an actual fix before digging any further and breaking more things.

[my branch]: https://github.com/peniblec/markdown-mode/commit/e6a0def7de443c898335518285d199d2620817ee

**Comment by jrblevin** [comment]
Yes, unfortunately bold and italics are tricky. I haven't had time to look closer myself, but what you suggested sounds like a reasonable way to proceed.

In the long run, my hope is overhaul the entire fontification approach so that it handles blocks first, then inline elements and with an inline parser that handles bold and italics simultaneously. Fletcher Penney [wrote up his thoughts about parsing Markdown](https://github.com/fletcher/MultiMarkdown-6/blob/master/DevelopmentNotes/DevelopmentNotes.pdf) and it seems like a good way to proceed.

**Comment by peniblec** [comment]
Sorry for not answering sooner. I glanced over this link and concluded
two things:

1. Overhauling fontification sounds like it could solve a bunch of
   corner cases in one fell swoop.

2. It also sounds like a formidable nerd-sniping trap 😃

It doesn't sound like there is anything impossible about it, and it
looks like an opportunity to learn a lot about a bunch of concepts
(which I guess include, but are not limited to: AST parsing with
Elisp, Markdown syntax, Emacs fontification). I mainly hack during
one-hour bus rides though, and I find those too frustratingly short to
successfully learn new stuff.

Hence the silence so far. I am reluctant to go on with the approach
I suggested, since I am not particularly fond of piling workarounds on
top of workarounds 😕

**Comment by cacology** [comment]
I've fixed this for my local copy by telling `markdown-regex-italic` not to include strings that begin with an asterisk. That is:

```
(defconst markdown-regex-italic
  "\\(?:^\\|[^\\]\\)\\(\\([*_]\\)\\([^ \n\t\\]\\|[^ \n\t*]\\(?:.\\|\n[^\n]\\)*?[^\\ ]\\)\\(\\2\\)\\)"
  "Regular expression for matching italic text.
The leading unnumbered matches the character before the opening
asterisk or underscore, if any, ensuring that it is not a
backslash escape.
Group 1 matches the entire expression, including delimiters.
Groups 2 and 4 matches the opening and closing delimiters.
Group 3 matches the text inside the delimiters.")
```

There's one character added in `[^\n\t*]`.  This has two failures

```
2 unexpected results:
   FAILED  test-markdown-font-lock/bold-2
   FAILED  test-markdown-font-lock/italics-4
```

but I don't think those tests represent situations I'm worried about.  The test `italic **\**` has an extra asterisk at the beginning, so I think is ambiguous to parse anyhow.  The test `This is ** not bold**, nor __ is this__ (but they match italics)` is wrong to my understanding, both should be bold.

**Comment by phst** [comment]
Tangential remark: It might make sense to switch the regexes to `rx` form, I think these forms are much more readable.

**Comment by jrblevin** [comment]
Thanks @cacology, this is a good idea. The second test you mentioned is based on Markdown.pl's behavior.  It produces

```
<p>This is <em>* not bold</em>*, nor <em>_ is this</em>_ (but they match italics)</p>
```

But I agree this is a strange case and it might be worth deviating from that behavior to improve font-lock in more relevant cases. I'll take a closer look at this.

**Comment by hartzell** [comment]
Just a "me too", I ran into this also:

<img width="170" alt="screen shot 2017-11-08 at 8 40 34 am" src="https://user-images.githubusercontent.com/312978/32561469-2a3d24f6-c461-11e7-8543-ceec18109318.png">

and found this issue while considering filing one.
