### ISSUE TITLE
delete html editing buffer for markdown-export

### ISSUE THREAD

**Issue by berquist** [jrblevin/markdown-mode#224]
It would be nice to at least have a toggle or setting for this. For example, it messes with with ido matching precedence in other panes.

**Comment by jrblevin** [comment]
I see three options, roughly in order of my preference at the moment:

1. Always kill the HTML output buffer after exporting to a file.
2. Use `bury-buffer` to put it at the end of the list, but keep it around just in case.
3. Add a customizable variable for whether to kill it or not.

Anyone have thoughts or comments on this?

**Comment by berquist** [comment]
Unless you're averse to adding options, another possibility is a combination of 3 and a variable for 2. This would be the most flexible.

Personally, I have no need to ever look at the file unless I'm debugging.

**Comment by jrblevin** [comment]
To avoid overcomplicating things, I added an option to kill the buffer which defaults to `t`.  The new variable is `markdown-export-kill-buffer`.
