### ISSUE TITLE
markdown-insert-hr spits 79 (and not 80) hypens

### ISSUE THREAD

**Issue by legends2k** [jrblevin/markdown-mode#225]
Doing <kbd>C-c -</kbd> prints out 79 dashes.  Isn't the standard old-style, column-width 80?  Why have one less?

**Comment by jrblevin** [comment]
Depending on settings, if you have an 80 column window with 80 characters followed by a newline (81 characters), you'll see the line wrap indicator in the right fringe. To avoid that, my personal preference is to have lines no longer than 79 characters.

However, this is fully customizable: `markdown-hr-strings` is actually a _list_ of HR strings that you can cycle through. So, if you prefer a string of 80 hyphens, you can set this variable in your local configuration.

**Comment by legends2k** [comment]
Thanks for the reply.  Since I'm not using Emacs on a true 80-column terminal I missed seeing this.  Thanks for letting me know.  I'll close this now.
