### ISSUE TITLE
Markdown mode makes scroll jump

### ISSUE THREAD

**Issue by sudhirkhanger** [jrblevin/markdown-mode#226]
Hello,

I have following in my `init.el`. When I use `markdown-mode` the cursor jumps. Is this some feature in markdown-mode that makes the cursor prompt jump at certain places. How do I disable it?

```
;; scroll one line at a time (less "jumpy" than defaults)
;; https://www.emacswiki.org/emacs/SmoothScrolling
;;
(setq mouse-wheel-scroll-amount '(1 ((shift) . 1))) ;; one line at a time
(setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
(setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
(setq scroll-step 1) ;; keyboard scroll one line at a time
```
Thank you.

**Comment by jrblevin** [comment]
markdown-mode doesn't do anything to move the point when scrolling—if I understand your question—so the short answer is no, there is nothing to disable.

However, it would be unusual if this is a behavior you see in markdown-mode but not other modes. I need a few more details before I can help, though:

  * What version of markdown-mode are you using (development/git or stable is sufficient)
  * What, exactly, are you doing (i.e., scrolling with mouse wheel?) and what do you mean by the cursor jumps? It *should* move when scrolling, right? So is it moving in an unexpected way?

**Comment by sudhirkhanger** [comment]
Hello @jrblevin,

Thanks for the reply.

* I am using markdown-mode 20170712.1703 from Melpa.
* I am using C-n to scroll line by line. It should move line by line but it seems to skip some lines. I have shot a video to explain the issue. Let me know if you are able to notice the cursor jumps. https://www.youtube.com/watch?v=Ra0UQBX_i9E

My full `init.el` is [here][2]. The markdown file that seems to have this issue is [here](https://github.com/sudhirkhanger/Fedora).

[1]: https://gist.github.com/sudhirkhanger/02afa15437c1daf46f7e9261496bb5c5

**Comment by jrblevin** [comment]
I wasn't able to reproduce the issue with "emacs --no-init" and the original configuration snippet you posted (regarding scrolling). I used the README.md file at the link you gave. I didn't try with your full init.el file, but if you want me to consider this a bug against markdown-mode, please try to find a minimal example of the behavior without other packages loaded, or other local configuration settings, that might interfere.

I'm closing this issue for now, but if you find such an example please let me know and I'll reopen it.
