### ISSUE TITLE
M-x indent-region suppress indentation of code block

### ISSUE THREAD

**Issue by maanuair** [jrblevin/markdown-mode#228]
Hello there,

Thank-you for mardown-mode!
Given this sample markdown file in Emacs (v25.1.1, macOS 10.12, mardown-mode 2.1):

```
Here follows a code sample:

    #!/bin/bash
    echo foobar

Nice sample, isn't it ?
```

When I run `M-x indent-region`, the indentation of the code block disappears, turning it back to regular text, as follows:

```
Here follows a code sample:

#!/bin/bash
echo foobar

Nice sample, isn't it ?
```

In my case, I did remove my `(add-hook 'before-save-hook 'reformat)` from my init file (`reformat` is a function that invokes `indent-region`), but I guess this is unexpected behavior.

Unless I miss something here?

**Comment by syohex** [comment]
I have merged #480. Please check latest version.
