### ISSUE TITLE
backquote syntax for code blocks breaks newlines in preview

### ISSUE THREAD

**Issue by nitingupta910** [jrblevin/markdown-mode#231]
When newlines are present in code block delimited by triple quotes, the preview destroys these newlines and everything within the code block appears as a single line in generated html.

markdown-mode: 20170724.2018
emacs: 25.2.1

**Comment by jrblevin** [comment]
This sounds like an issue with your Markdown processor (see the variable `markdown-command`). Perhaps it doesn't support GFM code block syntax? Can you verify how your processor parses the code block you described outside of markdown-mode?

**Comment by nitingupta910** [comment]
Yes, you are correct. The backend processor is generating `<code>...<code>` blocks for stuff in triple  backquotes and `<pre><code>..</code></pre>` for stuff indented by four spaces. So, the former loses all whitespace formatting while the latter preserves it. Anyhow, this is not a bug in `markdown-mode` so closing the issue.

Thanks for creating this package.

**Comment by nitingupta910** [comment]
Just for reference, the bad markdown parser I had was this one (https://daringfireball.net/projects/markdown/) which I got from `brew install markdown`. The `remarkable` markdown parser (`npm install markdown -g`) generates correct `<pre><code>...</code></pre>` blocks for both triple backticks and indent versions. So, I recommend symlinking remarkable to markdown when using with markdown-mode.
