### ISSUE TITLE
add footnotes to imenu

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#235]
It would be nice (even if opt-in) to be able to see footnote definitions from imenu.

**Comment by jrblevin** [comment]
Thanks for this suggestion. I just want to be sure I understand what you mean: this would be perhaps a "Footnotes" menu at the bottom of the "Index" menu with entries like "fn1", "fn2", etc. (corresponding to the footnote references)?

**Comment by blaenk** [comment]
Exactly, just to be sure, the actual name of the footnote would appear. So if I have:

```markdown
Some sentence containing a [^advisory] footnote within.

[^advisory]: Do this at your own risk.
```

Then imenu would show something like `Footnotes / advisory`.
