### ISSUE TITLE
Remove button overlays when exiting markdown-mode

### ISSUE THREAD

**Issue by rnkn** [jrblevin/markdown-mode#238]
Currently GFM checklists create buttons to toggle the value of the checkbox (which are really cool). The only problem is that these are overlays that persist when changing major mode, and can only be removed with `M-: (remove-overlays)`, which isn't user-friendly.

My suggestion is to add a hook to `after-change-major-mode-hook` to remove these overlays, which I think would be as simple as:
~~~elisp
(save-restriction
  (widen)
  (remove-overlays nil nil 'face 'markdown-gfm-checkbox-face))
~~~

I can submit a PR to fix this when I get the time.

**Comment by jrblevin** [comment]
Thanks for noticing this. Indeed, the overlays should be removed. What you proposed seems right to me, but maybe there is some other major mode we can look at for reference?
