### ISSUE TITLE
syntax highlighting issues

### ISSUE THREAD

**Issue by mclearc** [jrblevin/markdown-mode#24]
I'm thinking about making the switch from vim (and [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc)) to emacs. There are some noticeable differences in the way that Markdown mode (and pandoc minor mode) handles syntax highlighting in comparison to [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax). For example, markdown mode highlights only the first line of footnotes. This seems to be a problem for block quotes that don't have a `>` for every line as well. Emphasis and bold do not show in block quoted text. Markdown mode also fails to highlight raw latex. 

Unfortunately I know *nothing* about emacs lisp or how to write syntax highlighting in elisp, so I can't be of any immediate help. But is there any intention of trying to get markdown mode highlighting on par with vim-pandoc's highlighting? In any case, thanks for writing a great emacs mode!

**Comment by jrblevin** [comment]
Yes, the intention is to continue improving markdown-mode and this includes fixing the issues you mentioned. I was aware of the highlighting issue with hanging footnotes, but I always use `>` on each line of a blockquote so I had forgotten about the less explicit syntax. I prioritize supporting Gruber's original specification, which would include the blockquote issue, but as usual free time is the main limiting factor. Thanks for raising these issues.

**Comment by mclearc** [comment]
:+1: -- thanks!

**Comment by felker** [comment]
Just to be clear, the current version of markdown-mode still requires a `>` on each line of a blockquote to get proper highlighting, right?
