### ISSUE TITLE
middle-button mouse paste fails with "Point is not at a Markdown link or URL"

### ISSUE THREAD

**Issue by anarcat** [jrblevin/markdown-mode#240]
When writing drafts in Markdown-mode, it is sometimes impossible to paste content with the middle mouse button. I get the status bar error:

    Point is not at a Markdown link or URL

To reproduce this, start with this test file:

```
Test file
=========

https://example.com/
```

Then put the point right before the trailing slash (`/`) and hit enter a few times. Try to paste with the middle mouse button between the `.com` and the slash sign. You should reproduce the error.

I know this is a rather obtuse way of reproducing that issue, but it turns out I have that problem often in circumstances that are not always clear to me. It looks like the link detection code sometimes degenerates and covers more than actual links, which makes clicking around painful and broken. This is the best reproducer I could find... 

This is with markdown-mode `2.3-dev` from melpa (`20170823.1201).

Thanks!

**Comment by jrblevin** [comment]
Thanks for reporting this. I can see that there is some issue with the text properties. I think perhaps it has something to do with the "[stickiness](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sticky-Properties.html)" of the properties (the keymap in particular). I'll take a closer look when I have time, but if anyone sees the issue first feel free to chime in.

**Comment by jrblevin** [comment]
I think adding the `rear-nonsticky` property fixes this. Please check out the latest commit and let me know if it works for you now.

**Comment by anarcat** [comment]
looks great here - i'll reopen if the problem comes again - thanks!
