### ISSUE TITLE
markdown-edit-code-block should ensure trailing newline before returning

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jrblevin/markdown-mode#244]
When using `markdown-edit-code-block`, if you delete the trailing newline and then run `edit-indirect-commit`, you will end up with a broken code block, because the closing "```" will no longer be on its own line. I think a function needs to be added to `edit-indirect-before-commit-hook` to ensure a trailing newline.

**Comment by jrblevin** [comment]
Thanks for reporting this. I ran into this myself a few days ago.

I'm working on a fix, along the lines you suggested, but it's not quite working yet. The before-commit hook isn't running for some reason. I'm using the after-creation hook to set it up, and that one runs as expected. It's in the `feat/ensure-trailing-newline` branch of you have any suggestions.

**Comment by jrblevin** [comment]
That should fix it. I misread the edit-indirect code, which made things seem more complicated than it was. A simple `after-commit` hook local to the main buffer does the trick.
