### ISSUE TITLE
Reindenting line sometimes fails with error

### ISSUE THREAD

**Issue by kenmanheimer** [jrblevin/markdown-mode#245]
`markdown-indent-line` fails when trying to reindent a line with this error:

> let*: Wrong type argument: wholenump, -1

I am able to elicit the problem when trying to reindent the second line in a file that consists of just these two lines:

```
Stuff
  More
```

This is still a problem in today's Melpa release, markdown-mode-20170817.822.

**Comment by jrblevin** [comment]
Thanks. I can reproduce this and will take a closer look.
