### ISSUE TITLE
Add option to not raise footnote markers etc.

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#247]
The raised footnotes look pretty weird to me, they do look better with markup hidden but I'd rather not do that, so I was looking into simply disabling it on my end but it didn't seem immediately obvious to me how to accomplish that.

**Comment by blaenk** [comment]
It seems like it's just a matter of doing:

``` elisp
(defconst markdown-inline-footnote-properties nil)
```

I'll close this after getting some confirmation.

**Comment by jrblevin** [comment]
I think that should work for now, but it would be better for users I think if there was a `defcustom` for this (something I plan to add).

Coincidentally, @saf-dmitry also mentioned this as a comment to #130, so perhaps we should move any future discussion here.

**Comment by blaenk** [comment]
Sure thing.

**Comment by jrblevin** [comment]
I mean let's leave _this one_ open since the other one is a broader, already closed issue. :)

**Comment by jrblevin** [comment]
Footnotes are now only raised when markup hiding is enabled, and the display properties (raise amount, scaling) can now be customized via `markdown-footnote-display`. Sound good?

**Comment by blaenk** [comment]
Yeah that sounds reasonable.
