### ISSUE TITLE
Save buffer before executing `markdown-open-command`

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#248]
I would suggest some small improvements to the `markdown-open` command. The version below will first *save the buffer content* using `(save-buffer (buffer-file-name))` and then run the `markdown-open-command` on the file.

```elisp
(defun markdown-open ()
  "Open file for the current buffer with `markdown-open-command'."
  (interactive)
  (if (not markdown-open-command)
      (user-error "Variable `markdown-open-command' must be set")
    (if (not buffer-file-name)
        (user-error "Must be visiting a file")
      (save-buffer (buffer-file-name))
      (call-process markdown-open-command
                    nil nil nil buffer-file-name))))
```

For the time being you could advise the `markdown-open` function:

```elisp
(defadvice markdown-open (before my-markdown-save-and-open activate)
  "Save buffer before open file for the current buffer."
  (unless (buffer-file-name) (user-error "Must be visiting a file"))
  (save-buffer (buffer-file-name)))
```

**Comment by jrblevin** [comment]
Nice idea, thanks. I'll add this.

**Comment by saf-dmitry** [comment]
Sorry for being obtrusive @jrblevin: Any news on implementing this, or did you change your mind?

**Comment by jrblevin** [comment]
I didn't change my mind, I'm just behind. Thanks for reminding me about this.

From my reading of the `save-buffer` docstring, it looks like we don't need the `(buffer-file-name)` argument. It only takes numerical arguments. I'll add `(save-buffer)` before the `(call-process ...` line.

**Comment by saf-dmitry** [comment]
By the way, why the `markdown-open-command` is called synchronously using `call-process`? Wouldn't it be more appropriate to use `start-process-shell-command` for an asynchronous call? This way we can open the current file in a viewer, e.g. Marked, and continue editing text in Emacs buffer while Marked (or other similar viewer) will run in parallel with Emacs updating every time the buffer is saved.

**Comment by jrblevin** [comment]
That's exactly how I use `markdown-open-command`, with Marked ([see this post for details](https://jblevins.org/log/marked-2-command)). After reading the `call-process` docstring carefully, when the third argument (destination) is `nil` it does seem as if it should wait, but when used with `open` command on macOS the script returns. I think we can safely change the third argument to 0 instead to make it asynchronous in all cases. Any thoughts?

**Comment by saf-dmitry** [comment]
Yes, this works when used with `open` command on macOS. Actually I ask because I'm now working on a cross-platform Markdown viewer, conceptually similar to the Marked app for macOS, and it does not work asynchronously on Linux with Markdown mode v2.3. Maybe changing the third argument of `call-process` to `0` will help (according to docstring it should), but if not, I would consider `start-process-shell-command` as truly asynchronous solution.

**Comment by jrblevin** [comment]
Modifying `call-process` as discussed above works for me in my testing. Good luck with your Markdown viewer, and let me know if for some reason this doesn't work for you.
