### ISSUE TITLE
Font Lock for HTML tags

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#249]
Because HTML tags are generally part of Markdown markup syntax I would suggest highlighting them using `markdown-markup-face`.

**Comment by jrblevin** [comment]
I'm in favor of doing something with HTML tags and this is on my list. Actually, I took a shot at font-lock for HTML tags and attributes quite some time ago. As with many things, regular expressions aren't good enough but as I recall there were some limitations in the matching-function approach I took. It's in my `feat/html` branch if anyone wants to take a look.

**Comment by saf-dmitry** [comment]
My idea was actually simple: To highlight complete tag expressions using `markdown-markup-face` without distinguishing between tag names and attributes. I used following regular expression:

```elisp
(defconst markdown-regexp-html-tag
  "\\(?:^\\|[^\\]\\)\\(<[a-zA-Z0-9/]\\(?:\"[^\"]*\"\\|'[^']*'\\|[^'\">]\\)*>\\)"
  "Regular expression for (X)HTML tags.")
```

The limitation of this approach are multi-line tag expressions, i.e. tag expressions containing newlines.
