### ISSUE TITLE
Coloring miss

### ISSUE THREAD

**Issue by zonuexe** [jrblevin/markdown-mode#25]
![2015-09-19 18 28 56](https://cloud.githubusercontent.com/assets/822086/9975609/bb7645a0-5efc-11e5-8d09-4cd3b486f051.png)

https://github.com/supermomonga/darui.io/blob/master/README.mkd

```md
My personal website [だるい](#)'s source repository.
```

`#` is link target, but it seems to be colored as heading.

**Comment by jrblevin** [comment]
It highlights correctly on my system (Emacs 24.5, latest markdown-mode from Git). Can you verify that you're using the latest version of markdown-mode?
