### ISSUE TITLE
Can't set `markdown-code-face` with custom theme

### ISSUE THREAD

**Issue by danielmatz** [jrblevin/markdown-mode#250]
I configure faces using a custom theme.  I think my attempts to modify `markdown-code-face` are thwarted by the function `markdown-update-code-face`.  It doesn't override the face if a user has changed it with customize, but it doesn't check if a theme has set it.

Would it be possible to change the check to something like `(or (get 'markdown-code-face 'saved-face) (get 'markdown-code-face 'theme-face))`?

**Comment by jrblevin** [comment]
I think this was fixed in 7bf0736 (see #241). Can you please try updating?

I didn't know about `'theme-face`, thanks for that pointer. If I attempt the updating function approach again, I'll give that a try.

**Comment by danielmatz** [comment]
My apologies, I should have updated before posting an issue!  That did indeed fix it.  Thanks!
