### ISSUE TITLE
Error starting markdown-mode on Windows

### ISSUE THREAD

**Issue by dan-passaro** [jrblevin/markdown-mode#253]
In seemingly any Emacs buffer, running `M-x markdown-mode` gives this error:

> wrong-number-of-arguments (3 . 3) 0

Full traceback (from `M-: (markdown-mode) RET`):

```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 3) 0)
  color-rgb-to-hsl()
  apply(color-rgb-to-hsl nil)
  color-lighten-name("SystemWindow" -3)
  color-darken-name("SystemWindow" 3)
  byte-code("\300\301\302\303\304\305\304\306&<<<middle cut because it blocked copy paste>>> [custom-declare-group markdown-faces nil "Faces used in Markdown Mode" :group markdown faces custom-declare-face markdown-italic-face ((t (:inherit italic))) "Face for italic text." markdown-bold-face ((t (:inherit bold))) "Face for bold text." markdown-strike-through-face ((t (:strike-through t))) "Face for strike-through text." markdown-markup-face ((t (:inherit shadow :slant normal :weight normal))) "Face for markup elements." markdown-header-rule-face ((t (:inherit markdown-markup-face))) "Base face for headers rules." markdown-header-delimiter-face ((t (:inherit markdown-markup-face))) "Base face for headers hash delimiter." markdown-list-face ((t (:inherit markdown-markup-face))) "Face for list item markers." markdown-blockquote-face ((t (:inherit font-lock-doc-face))) "Face for blockquote sections." markdown-code-face face-background default "unspecified-bg" color-darken-name 3 color-lighten-name (default :inherit fixed-pitch) ((type graphic) (class color) (background dark)) :background ((type graphic) (class color) (background light)) "Face for inline code, pre blocks, and fenced code blocks." ((t (:inherit fixed-pitch))) markdown-inline-code-face ((t (:inherit markdown-code-face font-lock-constant-face))) "Face for inline code." markdown-pre-face ((t (:inherit (markdown-code-face font-lock-constant-face)))) ...] 14)
  (markdown-mode)
  eval((markdown-mode) nil)
  eval-expression((markdown-mode) nil)
  funcall-interactively(eval-expression (markdown-mode) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

markdown-mode: 20170830.2131
Emacs: 25.2.1
OS: Windows Version 6.1 (Build 7601: Service Pack 1)

**Comment by jrblevin** [comment]
Thanks for letting me know. There seems to be an issue in defining the background color for `markdown-code-face`.

**Comment by lauraperezcerrato** [comment]
I'm affected by this too.
markdown-mode: 20170320.1404
Emacs: 25.1.1 (x86_64-pc-linux-gnu) of 2017-03-29, modified by Debian
OS: Kubuntu Zesty

**Comment by jrblevin** [comment]
Thanks for the report, @lauraperezcerrato. I think fixed the issue for Unix console already (but at the time I wasn't aware of some different behavior on Windows). Can you try updating `markdown-mode` and let me know if it still doesn't work?

**Comment by lauraperezcerrato** [comment]
@jrblevin It's working now, thank you!

**Comment by lauraperezcerrato** [comment]
@jrblevin I'm using Arch linux on a different machine so I cannot access the Ubuntu package and I cannot get it to work from the repo. Is the code in the package different from the one in the repo?

**Comment by jrblevin** [comment]
I found a package named `emacs-markdown-mode` in the Arch user repository that is out of date.  There is another one, `emacs-markdown-mode-git`, that (based on the name) would seem to install the latest version from GitHub. Have you tried the latter?

**Comment by lauraperezcerrato** [comment]
That does it! Sorry to bother you

**Comment by jrblevin** [comment]
@dan-passaro Can you try updating now, after the new commit mentioned just above?

**Comment by jrblevin** [comment]
Can anyone using Emacs on Windows confirm if the above commit allows `markdown-mode` to load?

**Comment by kevinbirch** [comment]
I'm having this issue as well, but on a different platform:

    GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-09-26

For me I only see this error when using `emacs -nw` on the terminal (iTerm2 3.1.4), **not** when using the carbon GUI.

I'm using markdown-mode version 20171031.1725 installed from MELPA.

**Comment by jrblevin** [comment]
Thanks for reporting, @kevinbirch. This is after the above commit, which means there is still a remaining issue. I’ll look into it some more...

**Comment by kevinbirch** [comment]
@jrblevin that did the trick, I'm no longer seeing the error.  Thanks!

**Comment by jrblevin** [comment]
Awesome, thanks for confirming!

I haven't heard back from any Windows folks, but the original issue above should also be fixed now, so I'll close this.
