### ISSUE TITLE
Code fontification for Rmarkdown

### ISSUE THREAD

**Issue by ShuguangSun** [jrblevin/markdown-mode#265]
Is it possible to provide code fontification for Rmarkdown?

for example such kind of code block:

> {r fig-margin, fig.margin = TRUE, fig.cap = "MPG vs horsepower, colored by transmission.", fig.width=3.5, fig.height=3.5, cache=TRUE, message=FALSE}

where "r" is the mode and "fig-margin" is the name of the block.

**Comment by jrblevin** [comment]
Have you tried `M-x markdown-toggle-fontify-code-blocks-natively` (<kbd>C-c C-x C-f</kbd>)?

**Comment by ShuguangSun** [comment]
It works.
Sorry I wasn't aware the command before.

**Comment by jrblevin** [comment]
No problem—it's new in the most recent version.
