### ISSUE TITLE
Can't move backward by paragraph or block, only forward

### ISSUE THREAD

**Issue by neonnoodle** [jrblevin/markdown-mode#267]
I've been using markdown-mode for several years without issue, but recently have found myself unable to execute navigation commands in the backwards direction. Either by key-command or by M-x, the command "markdown-backward-paragraph" takes me to the first character of the current paragraph, no matter how many times invoked. I can go ahead by "markdown-forward-paragraph" without incident.

**Comment by jrblevin** [comment]
I can't replicate this: `markdown-backward-paragraph` moves back over subsequent paragraphs for me. There is also a (passing) unit test for the paragraph movement commands.

Can you provide some more information (version of markdown-mode and Emacs) and instructions to replicate this? Please check with `emacs --no-init` and load markdown-mode manually to make sure it's not a conflict with another package.

**Comment by neonnoodle** [comment]
OK, I reworked my init file and the reason appears to have been a conflict with another package. I'm still unsure which one, but the bug is not stemming directly from markdown-mode.

**Comment by jrblevin** [comment]
Thanks for letting me know. If you pinpoint the problem and there is something I should do on the `markdown-mode` side to help, just add a comment to this issue and I'll reopen it.
