### ISSUE TITLE
markdown-follow-link-at-point should be customizable for absolute filenames

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#268]
In a link such as `[a](/b)`, `markdown-follow-link-at-point` will find the file `/b`. That's typically not the correct file because such paths are relative to some serving root. I guess their should either be a variable such as `markdown-link-file-root` or a function variable such as `markdown-get-file-for-url-function` to customize the behavior.

**Comment by jrblevin** [comment]
Seems like a good idea to me. There is also the issue of file extensions, which comes up with wiki links as well. For wiki links, it is assumed that you want to open a source file with the same extension as the current file. I suppose the same would be preferred here, but it gets tricky when the URL might or might not have an extension. For example, either `[a](/b)` or `[a](/b.html)` might correspond to `b.md`. Given all the possibilities, maybe a function would be better here.
