### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by k-bx** [jrblevin/markdown-mode#269]
I don't have many details yet, but after doing `cask update` yesterday the usual file which I open quite frequently with my markdown notes became very laggy to work with, you can feel it every time you press the `C-v` to go one page down, it used to be snappy before. Due to my `zsh_history` last time I did `cask update` was on `2017-09-22 10:58:51 UTC`, so the degradation must have happened somewhere in-between.

Will try to bisect and update with more info here.

**Comment by jrblevin** [comment]
Thanks for letting me know. There hasn't been too much activity since 2017-09-22, and nothing stands out to me that would cause a performance hit. If you manage to narrow it down, please do add an update.

**Comment by k-bx** [comment]
Confirmed: rolling back markdown's version doesn't change anything, probably the lag comes from something else. I wonder what could that be.

**Comment by k-bx** [comment]
Oh, I forgot, I'm pretty sure I've updated my emacs since. Current one is `GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12`

**Comment by k-bx** [comment]
Had some time to bisect the issue, seems like projectile is the guilty one, and I've found a fresh issue created for them https://github.com/bbatsov/projectile/issues/1183

Sorry for a false alarm!
