### ISSUE TITLE
imenu is confused by GFM fenced code blocks

### ISSUE THREAD

**Issue by Wilfred** [jrblevin/markdown-mode#27]
Given the markdown:

    # Heading

    ## subheading

    ```
    foo
    # bar
    baz
    ```

    ## another subheading

Calling 'M-x imenu' erroneously shows 'bar' as a heading.

This makes imenu less useful, and is also causing https://github.com/ardumont/markdown-toc/issues/13

**Comment by jrblevin** [comment]
I think the new `markdown-collect-fm-code-blocks` function introduced in #40 could be used for font lock to fix this issue also. By identifying fenced code blocks first, then identifying headings that are not already marked as code blocks. I'll try to take a look soon, but if anyone can get to it sooner please submit a pull request.
