### ISSUE TITLE
Adding support for double-backslash math delimiters

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#270]
As fahr as I know, the current stable version of Markdown mode supports only `$$ ... $$` and `\[ ... \]` as delimiters for displayed LaTeX math. In order to support MultiMarkdown and Pandoc Markdown with `tex_math_double_backslash` option I would suggest adding `\\[ ... \\]` to math delimiters (using corresponding option). The important advantage of the double-backslash option is, that it does not preclude escaping of `(` and `[`.

**Comment by jrblevin** [comment]
Thanks, this is a good idea.

**Comment by jrblevin** [comment]
This is in the `master` branch now. Let me know if you see any issues.
