### ISSUE TITLE
variable mismatch

### ISSUE THREAD

**Issue by balalaXD** [jrblevin/markdown-mode#276]
when i customize variable `markdown-css-paths`, it shows that the variable is **mismatch**.

## Expected Behavior
    
make variable `markdown-css-paths` works.

## Actual Behavior

when i try to cutomize and save the modified variable `markdown-css-paths`, well, it doesnt work...

## Steps to Reproduce

> 1. emacs -Q --load path/to/markdown-mode.el test-case.md
> 2. M-x customize-mode
> 3. search `markdown-css-paths`

## Backtrace
	Debugger entered--Lisp error: (void-variable nill)
	  eval(nill)
	  custom-variable-set((custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #0 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #0 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #2 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #0 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #0 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil))
	  custom-variable-action((custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #0 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #0 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #2 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #0 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #0 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) nil)
	  widget-apply((custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #0 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #0 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) (custom-magic :args (nil) :parent #0 :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #2 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #0 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #0 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #0 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :action nil)
	  widget-parent-action((custom-magic :args (nil) :parent (custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic #0 :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #1 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #1 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) #0 (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #1 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #1 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #1 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #1 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #0 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) nil)
	  widget-apply((custom-magic :args (nil) :parent (custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic #0 :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #1 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #1 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) #0 (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #1 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #1 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #1 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #1 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #0 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :action nil)
	  widget-parent-action((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent (custom-magic :args (nil) :parent (custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic #1 :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #2 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #2 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) #1 (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #2 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #2 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :indent 0 :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) in no buffer> :to #<marker in no buffer> :children nil :buttons nil) nil)
	  widget-apply((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent (custom-magic :args (nil) :parent (custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic #1 :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #2 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #2 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) #1 (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #2 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #2 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :indent 0 :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) in no buffer> :to #<marker in no buffer> :children nil :buttons nil) :action nil)
	  widget-apply-action((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent (custom-magic :args (nil) :parent (custom-variable :documentation-shown t :custom-state modified :tag "Markdown Css Paths" :value markdown-css-paths :custom-form mismatch :custom-magic #1 :buttons ((custom-group-link :args nil :value markdown :tag "Markdown" :parent #2 :indent 0 :button-overlay #<overlay from 434 to 442 in *Customize Apropos*> :from #<marker (moves after insertion) at 434 in *Customize Apropos*> :to #<marker at 442 in *Customize Apropos*>) (documentation-string :args nil :value "URL of CSS file to link to in the output XHTML." :indent 3 :visibility-widget custom-visibility :parent #2 :doc-overlay #<overlay from 375 to 425 in *Customize Apropos*> :buttons nil :from #<marker (moves after insertion) at 375 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) #1 (custom-visibility :args nil :value t :help-echo "Hide the value of this option." :on "Hide" :off "Show" :on-glyph "down" :off-glyph "right" :action custom-toggle-hide-variable :parent #2 :indent 0 :suppress-face t :button-overlay #<overlay from 255 to 259 in *Customize Apropos*> :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 259 in *Customize Apropos*>)) :documentation-indent 3 :comment-widget (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>) :children ((sexp :button-face custom-variable-button-face :format "%v" :tag "markdown-css-paths" :parent #2 :value "nil" :indent 0 :field-overlay #<overlay from 280 to 284 in *Customize Apropos*> :from #<marker (moves after insertion) at 280 in *Customize Apropos*> :to #<marker at 285 in *Customize Apropos*>) (custom-comment :parent #2 :value "" :indent 0 :from #<marker at 426 in *Customize Apropos*> :to #<marker at 426 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 255 in *Customize Apropos*> :to #<marker at 443 in *Customize Apropos*> :comment-shown nil) :indent 0 :children ((choice-item :help-echo "Change the state of this item." :format "%[%t%]" :button-prefix widget-push-button-prefix :button-suffix widget-push-button-suffix :mouse-down-action widget-magic-mouse-down-action :tag " State " :parent #1 :indent 0 :button-overlay #<overlay from 288 to 295 in *Customize Apropos*> :from #<marker (moves after insertion) at 288 in *Customize Apropos*> :to #<marker at 295 in *Customize Apropos*>)) :from #<marker (moves after insertion) at 285 in *Customize Apropos*> :to #<marker at 375 in *Customize Apropos*> :buttons nil :value nil) :indent 0 :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) in no buffer> :to #<marker in no buffer> :children nil :buttons nil) nil)
	  Custom-newline(288)
	  funcall-interactively(Custom-newline 288)
	  call-interactively(Custom-newline nil nil)
	  command-execute(Custom-newline)

## Software Versions

- Markdown Mode: markdown-mode, version 2.3
- Emacs: GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-13
- OS: win10

**Comment by phst** [comment]
The type of that defcustom should be `(repeat string)`, not `list`.

**Comment by jrblevin** [comment]
Thanks @balalaXD for reporting this and @phst for the fix!
