### ISSUE TITLE
Feature Request: Allow customization of body wrapper

### ISSUE THREAD

**Issue by wyuenho** [jrblevin/markdown-mode#280]
Right now, the wrapper around the generated Markdown markup [isn't customizable](https://github.com/jrblevin/markdown-mode/blob/7a62259a22ccbf59b0132d077348ee489edf5d1e/markdown-mode.el#L7772), it would be nice if I could insert something after the open body tag and before the closing tag.

This would allow me to insert an article wrapper in order to apply a class name. This would allow me to use @sindresorhus's [github-markdown-css](https://github.com/sindresorhus/github-markdown-css) unmodified.

What do you think?

**Comment by jrblevin** [comment]
Adding these variables is fine with me, but for more general pre/post-processing let me also mention here that there are two hooks: `markdown-before-export-hook` and `markdown-after-export-hook`.

**Comment by wyuenho** [comment]
But the 2 hooks don't have access to the temp buffer? Even if there is, it's too big a hammer. I'll fix up the PR soon. Thanks for reviewing.

**Comment by jrblevin** [comment]
Just mentioning them here for the benefit of others searching for related problems. The after-export hook would work for these customizations, but indeed it is a big hammer.
