### ISSUE TITLE
markdown-edit-code-block errors with (void-function nil)

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#284]
## Expected Behavior

For an edit-indirect buffer to open with the contents of the codeblock.

## Actual Behavior

The following backtrace.

## Steps to Reproduce

Buffer like this with cursor in the middle of the codeblock:

    ``` ini
    [/Script/EngineSettings.GameMapsSettings]
    +GameModeMapPrefixes=(Name="DM",GameMode="/Script/UnrealTournament.UTDMGameMode")
    +GameModeClassAliases=(Name="DM",GameMode="/Script/UnrealTournament.UTDMGameMode")
    ```

This only seems to happen for languages that don't have obvious mappings between codeblock language marker and emacs mode, so I wonder if it's related to the changes made for #251 , something about this comment https://github.com/jrblevin/markdown-mode/issues/251#issuecomment-326777139 or the one after it. Sorry it's been a while since I wrote that.

## Backtrace

```
Debugger entered--Lisp error: (void-function nil)
  nil()
  #f(compiled-function (parent-buffer beg end) #<bytecode>)(#<buffer asdf> 11 218)
  edit-indirect--create-indirect-buffer(11 218 #<overlay from 11 to 218 in asdf>)
  edit-indirect--get-edit-indirect-buffer(11 218)
  edit-indirect-region(11 218 display-buffer)
  markdown-edit-code-block()
  funcall-interactively(markdown-edit-code-block)
  call-interactively(markdown-edit-code-block nil nil)
  command-execute(markdown-edit-code-block)
```

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: 26.0.50
- OS: archlinux 4.13.12-1-ARCH

**Comment by blaenk** [comment]
Please see https://github.com/jrblevin/markdown-mode/commit/3b926189fee01aa90680740f363dd0e6c9c80779#commitcomment-25598489 , I think it may be the cause of this issue.

**Comment by jrblevin** [comment]
Thanks for following up on this aspect. I forgot to address in from previous comments, but I think it is fixed now.

**Comment by blaenk** [comment]
It appears to be working 👍
