### ISSUE TITLE
Suboptimal failure modes for markdown-open and markdown commands

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#291]
## Expected Behavior

The commands `markdown-open` and `markdown` should provide a meaningful error message when `markdown-open-command` and `markdown-command` fail or don't exist, respectively.

## Actual Behavior

Both commands silently do nothing if the external subprocess fails. In addition, `markdown` silently does nothing if the program file doesn't exist.

## Steps to Reproduce

In a Markdown buffer:

```
(let ((markdown-command "/bin/false")) (markdown))
(let ((markdown-command "/does/not/exist")) (markdown))
(let ((markdown-open-command "/bin/false")) (markdown-open))
```

## Software Versions

- Markdown Mode: 2.3
- Emacs: 26.0.90
- OS: Debian testing

**Comment by jrblevin** [comment]
Thanks, I agree!
