### ISSUE TITLE
markdown-insert-gfm-code-block: error when LANG is nil

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#292]
I wanted to make a bind that was basically `markdown-insert-gfm-code-block` but with its `EDIT` param set to `t`, and have it still prompt me for the language with a completing read, so I passed `nil` for the `LANG` param as the documentation says:

> If LANG is nil, the language will be queried from user.

Instead it errors out because it seems to assume that it's a string.

## Expected Behavior

Insert a gfm code block after prompting me for the language and edit-indirect it.

## Actual Behavior

The following backtrace.

## Steps to Reproduce

Eval this:

``` elisp
(markdown-insert-gfm-code-block nil t)
```

## Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  #f(compiled-function (&optional lang edit) "Insert GFM code block for language LANG.\nIf LANG is nil, the language will be queried from user.  If a\nregion is active, wrap this region with the markup instead.  If\nthe region boundaries are not on empty lines, these are added\nautomatically in order to have the correct markup.  When EDIT is\nnon-nil (e.g., when \\[universal-argument] is given), edit the\ncode block in an indirect buffer after insertion." (interactive #f(compiled-function () #<bytecode>)) #<bytecode>)(nil t)
  apply(#f(compiled-function (&optional lang edit) "Insert GFM code block for language LANG.\nIf LANG is nil, the language will be queried from user.  If a\nregion is active, wrap this region with the markup instead.  If\nthe region boundaries are not on empty lines, these are added\nautomatically in order to have the correct markup.  When EDIT is\nnon-nil (e.g., when \\[universal-argument] is given), edit the\ncode block in an indirect buffer after insertion." (interactive #f(compiled-function () #<bytecode>)) #<bytecode>) (nil t))
  markdown-insert-gfm-code-block(nil t)
  eval((markdown-insert-gfm-code-block nil t) nil)
  pp-eval-expression((markdown-insert-gfm-code-block nil t))
  funcall-interactively(pp-eval-expression (markdown-insert-gfm-code-block nil t))
  call-interactively(pp-eval-expression nil nil)
  command-execute(pp-eval-expression)
```

**Comment by jrblevin** [comment]
When you call `markdown-insert-gfm-code-block` with explicit arguments, the interactive prompt for the language name is bypassed (and indeed, the string is nil).  I could put in a check for `nil` string `lang`, but you stated that you want to be prompted for the language, so that wouldn't work as you want.  Instead, try calling it interactively with a prefix argument (where `(4)` is the universal argument passed when you use <kbd>C-u</kbd>).  For example:

``` emacs-lisp
(global-set-key (kbd "C-c C")
                (lambda ()
                  (interactive)
                  (let ((current-prefix-arg '(4)))
                    (call-interactively 'markdown-insert-gfm-code-block))))
```

**Comment by blaenk** [comment]
Confirmed working, thanks.
