### ISSUE TITLE
Table fontification breaks inline formatting

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#295]
Because `markdown-table-face` takes precedence over some faces for inline formatting (e.g., `markdown-bold-face` or `markdown-italic-face`), it breaks the fontification of inline formatting inside a table.

## Expected Behavior

In the table below

    | 1   | 2     | 3 |
    | *4* | **5** | 6 |

all bold and italic elements should appear as bold and italic respectively.

## Actual Behavior

All bold and italic elements inside a table use `markdown-table-face` properties.

This issue can be fixed by setting some face attributes to `unspecified`:

    (set-face-attribute 'markdown-table-face nil :foreground 'unspecified :background 'unspecified :weight 'unspecified)

or by changing precedence for `markdown-table-face` in Font Lock.

## Software Versions

- Markdown Mode:  From Git on 2017-11-17
- Emacs: 24.3
- OS: Gnu/Linux (Ubuntu 14.4)

**Comment by dod38fr** [comment]
A similar problem shows up when a table contains a link:
```
| foo [foo link](http://foo.net) |
```

All the text outside of the parentheses is underlined. I would expect only `[foo link]` to be underlined.

HTH

Software Versions:
* Markdown Mode: 2.4-dev
* Emacs: 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-07, modified by Debian
* OS: Gnu/Linux (Debian sid amd64)

**Comment by badbob** [comment]
@dod38fr reproduce this bug on latest `markdown-mode` version:
```
;; Package-Version: 20181112.1529
```

**Comment by dod38fr** [comment]
@badbob I see the same behavior.

All the best

**Comment by syohex** [comment]
![a](https://user-images.githubusercontent.com/554281/129643274-08c42e81-dbfc-49da-b632-8ae78c28da82.png)

I suppose that this issue was already fixed.
