### ISSUE TITLE
New modes optimized for reading markdown content (as opposed to editing it)

### ISSUE THREAD

**Issue by vermiculus** [jrblevin/markdown-mode#296]
## Expected Behavior

I suggest a `{markdown,gfm}-view-mode` that derives from the normal editing modes. These would be optimized for reading, not editing.

## Actual Behavior

The naive approach is to enable `read-only-mode` in the buffer, but this puts all the navigation commands far out of reach.

I'm going to be including a very basic concept of `gfm-view-mode` in an upcoming version of Magithub, but it'd be nice if that definition could come from this package instead 😄

**Comment by jrblevin** [comment]
Thanks, I am on board with this idea. Something along these lines was also suggested in #130.

Just checking, do you know about hidden markup mode (`M-x markdown-toggle-markup-hiding` or <kbd>C-c C-x C-m</kbd>)? It seems that this could be solved simply by a mode that turns on `read-only-mode` and sets `markdown-hide-markup`. Perhaps some maintenance work to make sure the editing commands fail gracefully. Is there anything else it should do?

**Comment by vermiculus** [comment]
I'm on a subpar network right now so sorry I can't expand more, but putting more navigation at your fingertips. Even binding n/p to section movement proofed very beneficial. More careful thought could bring even greater benefit.

**Comment by vermiculus** [comment]
[I created such a mode for Magithub](https://github.com/vermiculus/magithub/commit/64bd2a4181edd6bb985987e1e1bc2f59e9ab6481#diff-75dc6d6dd459a25e982adb464f381c8dR136) and found it dramatically improved usability with just those two additional bindings. I don't use `markdown-mode` enough to know what else would be routinely useful.

I *did* know about `markdown-hide-markup` -- it's *very* cool 😄

**Comment by jrblevin** [comment]
Thanks for demonstrating with the `gfm-view-mode` in Magithub. Inspired by that, I added two view modes in the above referenced commit. Let me know if you have thoughts or suggestions...

**Comment by vermiculus** [comment]
Awesome! This is just the kind of thing I was looking for 😄 

Thanks!
