### ISSUE TITLE
infinite loop? by entering "[|"

### ISSUE THREAD

**Issue by iquiw** [jrblevin/markdown-mode#298]
## Expected Behavior

Emacs does not block input.

## Actual Behavior

When entering `|` character, Emacs blocks.

## Steps to Reproduce

1. Start Emacs.

   ```console
   $ emacs -Q --load path/to/markdown-mode.el
   ```

2. Delete buffer contents (<kbd>C-x h</kbd>, <kbd>C-w</kbd>).

3. Start `gfm-mode` (`M-x gfm-mode`).

4. Enter `[|`.

## Backtrace

N/A

## Software Versions

- Markdown Mode: current master 2052be55afb6382916f9d13b40eb92afe1d5eeb6
- Emacs: 25.3
- OS: Windows10, macOS High Sierra

Markdown Mode: v2.3 does not have the problem.

**Comment by iquiw** [comment]
By `git bisect`, 4c5e420eafddfa874c9f9bf053bace8812eec77b seems the first bad commit.

**Comment by jrblevin** [comment]
Thanks for reporting, and especially for bisecting. This is very helpful. I have confirmed the issue.

**Comment by jrblevin** [comment]
That should fix the issue, but please let me know if not.

**Comment by iquiw** [comment]
Thank you for fixing so fast!
