### ISSUE TITLE
remove markdown syntax highlight within html tags

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [jrblevin/markdown-mode#299]
## Expected Behavior

If I write something like

```html
<div>
|           processes             |
           |    virtual memory    |
                        |  files  |
processor  main memory  I/O devices
</div>
```

Expecting the words inside div tag without markdown syntax highlight

## Software Versions

- Markdown Mode: latest version
- Emacs: 25.3
- OS: macOS

**Comment by syohex** [comment]
It looks this is already fixed.
