### ISSUE TITLE
De-denting and lag 

### ISSUE THREAD

**Issue by jreeseue** [jrblevin/markdown-mode#30]
There are 2 issues I've noticed on Emacs 24.5.1 OS X 10.10.5. 

Take the file: 

# test #

    * item 1

1. When I hit enter at the end of the "item 1" line this will be de-dented to the beginning of the next line.

2. I have a markdown file with about 2300 lines and entering data into this file is pretty laggy.

**Comment by vyp** [comment]
I guess the first issue may be related to #28?

**Comment by jreeseue** [comment]
Yes, this is the same issue. Sorry I missed that.

**Comment by jrblevin** [comment]
Sorry for the slow response. Indeed, item 1 is a duplicate but I'm leaving this open as a reminder for item 2. I also experience some lag when editing large files. I am working to make parsing for font-locking more efficient, which I think is the root cause.

**Comment by jrblevin** [comment]
When you have time, please give the latest version a try with regards to item 2 (lag). Recent changes allow syntactic identification of code and pre blocks. I think the previous search-based approach to this may have been part of the problem.

**Comment by jreeseue** [comment]
Downloaded the newest version and lag still seems to be present.

josh

**Comment by jrblevin** [comment]
OK, thanks for checking. I will keep investigating the lag issue. The indentation issue seems to be fixed now at least!

**Comment by jrblevin** [comment]
Let's try once more. I just pushed commit acf7c5e which I think should essentially eliminate the lag when typing. For me, this makes any lag almost imperceptible in a 5000+ line file, but if it doesn't fix things for you let me know.

You may also want to see the related discussion in #44.

**Comment by jreeseue** [comment]
Looks like it’s working perfectly. Thanks!

josh

**Comment by jrblevin** [comment]
Excellent! Thanks again for this report.
