### ISSUE TITLE
orgalist

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#304]
Saw this and just thought it was worth mentioning. Not sure if markdown-mode should emulate, replace or use this, or do nothing. But at some point you'll probably get questions about it and should know about it.

orgalist replaces org-struct and is a minor-mode that gives org list management functions in non-org buffers.

https://lists.gnu.org/archive/html/emacs-orgmode/2017-12/msg00619.html

**Comment by syohex** [comment]
Thanks for information. However I do nothing.

> emulate

It makes maintenance hard

> replace or use

org-mode extension has many dependencies like org.el it is too big. markdown-mode has no dependency. I would not like to add any dependency.
