### ISSUE TITLE
single space between reference links breaks first link

### ISSUE THREAD

**Issue by RMBLRX** [jrblevin/markdown-mode#305]
## Expected Behavior

This:

```markdown
[notable][cd] [stand-outs][ce]

[cd]: https://github.com/gollum/gollum
[ce]: https://tiddlywiki.com/
```
... should have their respective links to follow on both, _notable_ and _stand-outs_.

## Actual Behavior

Instead, when attempting to follow the first link with my cursor over _notable_ and then using <kbd>C-c C-o</kbd>, I get the message, `Nothing to follow at point`, while _stand-outs_ does not issue this message.

## Steps to Reproduce

I first noticed this on spacemacs where I could hover my pointer over the link text and see the link displayed from its reference (in that case, getting the message, rather than the expected link, of course), but I was able to reproduce this bug as expected from entering this command into bash:

`emacs -Q --load .emacs.d/elpa/markdown-mode-20171222.927/markdown-mode.el test-case.md`

and using the following text:

```markdown
[notable][cd] [stand-outs][ce]

[cd]: https://github.com/gollum/gollum
[ce]: https://tiddlywiki.com/
```
... and of course using <kbd>C-c C-o</kbd> with the cursor over _notable_.

Interestingly, adding a double-space between the two links like so:

```markdown
[notable][cd]  [stand-outs][ce]`
```
... fixes the issue.

## Backtrace

I did not receive any error which would give any backtrace, as far as I could tell.

## Software Versions

- Markdown Mode: version 2.4-dev (a little confused, as I don't actually see that version in this repo)
- Emacs: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian
- OS: Ubuntu 16.04.3 LTS

**Comment by syohex** [comment]
```diff
diff --git a/markdown-mode.el b/markdown-mode.el
index 60f0a8e..1a14cd2 100644
--- a/markdown-mode.el
+++ b/markdown-mode.el
@@ -7657,13 +7657,17 @@ update this buffer's contents."
 (defun markdown-link-p ()
   "Return non-nil when `point' is at a non-wiki link.
 See `markdown-wiki-link-p' for more information."
-  (let ((case-fold-search nil))
-    (and (not (markdown-wiki-link-p))
-         (not (markdown-code-block-at-point-p))
-         (or (thing-at-point-looking-at markdown-regex-link-inline)
-             (thing-at-point-looking-at markdown-regex-link-reference)
-             (thing-at-point-looking-at markdown-regex-uri)
-             (thing-at-point-looking-at markdown-regex-angle-uri)))))
+  (save-excursion
+    (let ((case-fold-search nil))
+      (when (eq (get-text-property (point) 'face) 'markdown-link-face)
+        (skip-chars-backward "^[")
+        (forward-char -1))
+      (and (not (markdown-wiki-link-p))
+           (not (markdown-code-block-at-point-p))
+           (or (thing-at-point-looking-at markdown-regex-link-inline)
+               (thing-at-point-looking-at markdown-regex-link-reference)
+               (thing-at-point-looking-at markdown-regex-uri)
+               (thing-at-point-looking-at markdown-regex-angle-uri))))))
 
 (make-obsolete 'markdown-link-link 'markdown-link-url "v2.3")
 
@@ -7679,6 +7683,9 @@ Value is a list of elements describing the link:
  6. bang (nil or \"!\")"
   (save-excursion
     (goto-char pos)
+    (when (eq (get-text-property (point) 'face) 'markdown-link-face)
+      (skip-chars-backward "^[")
+      (forward-char -1))
     (let (begin end text url reference title bang)
       (cond
        ;; Inline or reference image or link at point.
```

I suppose above patch fixes this issue. However I don't test well

**Comment by syohex** [comment]
```diff
diff --git a/markdown-mode.el b/markdown-mode.el
index 60f0a8e..bb240cd 100644
--- a/markdown-mode.el
+++ b/markdown-mode.el
@@ -634,7 +634,7 @@ Group 7 matches the title (optional).
 Group 8 matches the closing parenthesis.")
 
 (defconst markdown-regex-link-reference
-  "\\(!\\)?\\(\\[\\)\\([^]^][^]]*\\|\\)\\(\\]\\)[ ]?\\(\\[\\)\\([^]]*?\\)\\(\\]\\)"
+  "\\(!\\)?\\(\\[\\)\\([^]^][^]]*\\|\\)\\(\\]\\)\\(\\[\\)\\([^]]*?\\)\\(\\]\\)"
   "Regular expression for a reference link [text][id].
 Group 1 matches the leading exclamation point (optional).
 Group 2 matches the opening square bracket for the link text.
```

`markdown-mode` regexp allows one space between `]` and `[` like `[foo] [bar]`. However common-mark specification does not allow it. And all tests are passed after applying above patch. It looks removing space from above regexp is no problem

**Comment by syohex** [comment]
https://daringfireball.net/projects/markdown/syntax#link

This document says

```
You can optionally use a space to separate the sets of brackets:

This is [an example] [id] reference-style link.
```

**Comment by syohex** [comment]
Thanks for reporting issue. Please check latest version.
