### ISSUE TITLE
why # foo # instead of # foo

### ISSUE THREAD

**Issue by azzamsa** [jrblevin/markdown-mode#318]
## Expected Behavior
In this template and your README.md you use `# foo` instead of `# foo #` in heading.
But why when I invoke `C-c C-s` then choose number or `h`, I got `# foo #` or `### foo ###`

I try to read and read the documentation, but I can't find a solution.

## Steps to Reproduce
I have run ` emacs -Q ` and it still the same.

## Software Versions

- Markdown Mode: 20180124.138
- Emacs: GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
- OS: Debian 9

**Comment by jrblevin** [comment]
You'll want to customize the `markdown-asymmetric-header` variable, setting it to `t` to get the behavior you prefer.

**Comment by azzamsa** [comment]
I just hear about it today :)

Thanks for your contribution to community. thank you.
