### ISSUE TITLE
Wrong fontification of inline emphasis

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#325]
Current fontification of inline emphasis is not consistent with Markdown convention.

## Expected Behavior

Markdown treats both asterisks (`*`) and underscores (`_`) as indicators of emphasis but the same character must be used to open and close an emphasis span. So this is a proper syntax for bold emphasis

    __bold__
    **bold**

but this is not

    _*bold_*
    *_bold*_

## Actual Behavior

Following examples will be fontified as bold in Markdown Mode:

    _*bold_*
    *_bold*_

## Software Versions

- Markdown Mode: From Git on 2018-04-04
- Emacs: 24.3
- OS: Ubuntu Linux

## Suggested Solution

`markdown-regex-bold` should be modified to match the emphasis indicators correctly:

```elisp
(defconst markdown-regex-bold
  "\\(^\\|[^\\]\\)\\(\\(\\*\\*\\|__\\)\\([^ \n\t\\]\\|[^ \n\t]\\(?:.\\|\n[^\n]\\)*?[^\\ ]\\)\\(\\3\\)\\)"
  "Regular expression for matching bold text.
Group 1 matches the character before the opening asterisk or
underscore, if any, ensuring that it is not a backslash escape.
Group 2 matches the entire expression, including delimiters.
Groups 3 and 5 matches the opening and closing delimiters.
Group 4 matches the text inside the delimiters.")
```

**Comment by syohex** [comment]
I have merged #472. Please check latest version
