### ISSUE TITLE
markdown-toggle-inline-image: error if document contains links to local files

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#334]
## Expected Behavior

`markdown-toggle-inline-images` ignores files that are not images and non-image links.

## Actual Behavior

`markdown-toggle-inline-images` treats every link, even non-image links, as images and tries to load them, causing errors.

## Steps to Reproduce

Create files such as

```none
$ cat /tmp/a.md 
[b](b.md)
$ cat /tmp/b.md
```

Content of `b.md` is irrelevant, but it has to exist. Note that `a.md` doesn't contain any images.
Now open `a.md`:

```shell
$ emacs -Q -L . -l markdown-mode /tmp/a.md
```

Then hit <kbd>C-c C-x TAB</kbd>. You get an error 

> image-type: Cannot determine image type

The non-image link should be ignored entirely. Also broken image files should at most display a warning, not a hard error; i.e. `markdown-mode` should catch errors from `create-image`.

## Backtrace

```none
Debugger entered--Lisp error: (error "Cannot determine image type")
  signal(error ("Cannot determine image type"))
  error("Cannot determine image type")
  image-type("/tmp/b.md" nil nil)
  create-image("/tmp/b.md")
  markdown-display-inline-images()
  markdown-toggle-inline-images()
  funcall-interactively(markdown-toggle-inline-images)
  call-interactively(markdown-toggle-inline-images nil nil)
  command-execute(markdown-toggle-inline-images)
```

Note that `markdown-mode` tried to load `b.md` as image.

## Software Versions

- Markdown Mode: markdown-mode, version 2.4-dev
- Emacs: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.24) of 2018-02-13, modified by Debian
- OS: Debian GNU/Linux testing

**Comment by jrblevin** [comment]
Thanks for catching this. The commit above addresses ignoring non-image links. It doesn't catch errors from `create-image` yet, however.
