### ISSUE TITLE
markdown-mode registers keybindings I don't want.

### ISSUE THREAD

**Issue by m-cat** [jrblevin/markdown-mode#336]
I'm just going to copy what I wrote in [another issue](https://github.com/mnuessler/jira-markup-mode/issues/5):

> I'm guessing this mode is based on markdown-mode (I'll have to raise an issue over there...) which is a mode that also steals keybindings (I'd like to keep M-n and M-p, thank you very much), but I would rather we be able to set our own bindings, if we want to do so, rather than having them be forced on us.
> 
> You can also put registration of keybindings into a separate, optional command, which a few modes do.

And now I'll add that, hey, this is *just markdown*. Literally, plaintext. Even most programming language modes don't have as many mandatory keybindings forced on us. I don't need extra functionality, I can already edit plaintext just fine with Emacs, and I just want the goddamn (pardon my French) syntax highlighting.

Not trying to be rude, but please allow us to initialize the keybindings with an optional command if someone's strange enough to actually want them.

**Comment by m-cat** [comment]
Everyone hates the Emacs default behavior, so not sure if the official recommendations should trump common sense (or be given much weight at all).

If every major mode decided to steal a bunch of keys, it would be a huge cognitive load to remember which modes register which keys, and you'd have to constantly keep in mind which mode the current buffer is. Personally, I switch between different programming modes all the time, and I'm glad most have the sense and goodwill not to register any keybindings by default. I can't imagine the nightmare otherwise.

For something like `markdown-next-link`, instead of remembering that it's `M-n`, I would do `M-x markdown-next-link` (helm would autocomplete it). As it stands, `markdown-mode` is the fifth mode where I've had to go and manually override this particular keybinding. Not sure why `markdown-next-link` even deserves its own keybinding as I've never used this command.

Anyway, I just searched and found out about [`bind-key.el`](https://emacs.stackexchange.com/a/360) which has brought sanity back into my Emacs :) Globally consistent behavior and no more manual overrides, whoo!

**Comment by m-cat** [comment]
Some more thoughts on the above:

`C-s ](` is better because it's more universal than `markdown-next-link`, as it operates on the actual plain text. In other words, it doesn't rely on some hidden state tracked by `markdown-mode` and you don't need to know which mode you're in. You can even switch between `markdown-mode` and `fundamental-mode` and continue using the same keypresses without any mental context switches.

When possible, it is ALWAYS better to treat text as text. Yes, sometimes the text will be in code blocks or otherwise semantically different -- I *still* prefer using globally-consistent keypresses in these situations.

Found an example of a nice mode that doesn't steal keys [here](https://github.com/enoson/eno.el). Instead, it has a big list of suggested keybindings. This is the optimal way to handle this kind of thing as you can remove the keybindings you don't want and edit the rest if you wish to do so.

**Comment by jrblevin** [comment]
There is plenty of precedence for using <kbd>M-n</kbd> and <kbd>M-p</kbd> in this manner and, as referred to above, the [Major Mode Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Mode-Conventions.html) even address this:

> A major mode can also rebind the keys <kbd>M-n</kbd>, <kbd>M-p</kbd> and <kbd>M-s</kbd>. The bindings for <kbd>M-n</kbd>, <kbd>M-p</kbd> should normally be some kind of moving forward and backward, but this does not necessarily mean cursor motion.

If you want to use them for user keybindings instead, then of course you're free to unbind them.
