### ISSUE TITLE
HTML preview is not UTF-8

### ISSUE THREAD

**Issue by Louson** [jrblevin/markdown-mode#340]
If I export the md file with 'markdown-preview', the specials characters are not correctly read on my browser (firefox 60.0.1)

## Expected Behavior
Export a md file containing letters with accents should be read in a browser supporting UTF-8.

## Actual Behavior
The html output should support UTF-8

## Steps to Reproduce
1. Create a markdown file containing letters with accents 
```markdown
This is special letter é
```
2. Export with 'markdown-preview' command
3. Open with firefox

## Software Versions
Markdown v2.1
Emacs 25.3.1

## Possible solution
I don't know much about HTML but I guess it misses a line before the title (markdown-mode.el:markdown-add-xhtml-header-and-footer :
```html
<meta charset=\"UTF-8\"/>
```
Also, I don't know why the html starts with an xml header specifing the UTF-8...

**Comment by jrblevin** [comment]
This should be fixed by #350, but please reopen if not.
