### ISSUE TITLE
Infloop in jit-lock on emacs 27

### ISSUE THREAD

**Issue by vspinu** [jrblevin/markdown-mode#349]
When pasted into an empty markdown buffer the following sample cause an infloop:

------------------------

```
reg y x1 x2 x3, \\\
    vce(robust) \\\
    nocon
```
**Get**

```
reg y x1 x2 x3, \\\
vce(robust) \\\
nocon
```
----------------------

- Markdown Mode: ELPA/markdown-mode-20180707.1255
- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-26
- OS: Ubuntu 18.04

First reported as part of vermiculus/magithub#353

**Comment by jrblevin** [comment]
Thanks, but I wasn’t able to reproduce this. I copied the text between the horizontal rules when viewing the Markdown source of your comment. In case the spaces or newlines are important, perhaps you could email the test case to me as an attachment, upload it somewhere, or create a [Gist](https://gist.github.com/)?

**Comment by jrblevin** [comment]
I just noticed you wrote Emacs 27, but I tested on Emacs 26.1. Does the version seem to be important?

**Comment by vspinu** [comment]
Yes. It seems emacs 27. I cannot reproduce it on emacs 25. I will build emacs 26 and will check there as well.


And yet, copy pasting from the md source of my comment is what should trigger the error.

**Comment by vspinu** [comment]
No, it's actually not emacs27 specific. i could reproduce it with emacs 25 as well, I just didn't notice the jit-lock error in the message buffer. 

I can reproduce it with the bare minimum emacs -q and:

```el
 (setq package-load-list '((markdown-mode t)))
 (package-initialize)
```

**Comment by vspinu** [comment]
This is the minimal example I see it with:

-------
```
foo
```
**bar**
-----------------

**Comment by jrblevin** [comment]
Thanks, now I also see the error in *Messages*.

**Comment by vspinu** [comment]
I figured out the reason for this, in a nutshell it infolops because the position at the end of the fenced block is considered part of the code. I don't think this is right.  Let's say that I have an empty block `---\n---| ` where `|` stands for point. That's position 8 but the block has only 7 characters. 

Fine with changing this semantics?

**Comment by vspinu** [comment]
Given that emacs buffer positions is forward-oriented (think of `get-text-property` and `put-text-property`) I think the only coherent semantics here is to consider the point after last fence outside of the code block.

FWIW polymode uses this semantics and would be nice to have some synchronization across tools here. Otherwise very funny things will happen :)
