### ISSUE TITLE
Markdown-mode treats '_' in fomulas as italic

### ISSUE THREAD

**Issue by PhoenixStarEclipse** [jrblevin/markdown-mode#351]
## Expected Behavior

I'm editing a fomula inside a pair of '$'s. Markdown-mode should do nothing with my '_'.

## Actual Behavior

Characters between '_'s gets underlined, as if they were italic.

## Steps to Reproduce

Just install markdown-mode, edit a whatever markdown file, and type
```$a_1b_1$```
and `1b` will get underlined.

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-22
- OS: Gentoo Linux

**Comment by jrblevin** [comment]
Are you using math mode? `M-x markdown-toggle-math` or <kbd>C-c C-x C-e</kbd>.

**Comment by PhoenixStarEclipse** [comment]
Oh, sorry. I forgot it.
