### ISSUE TITLE
HowTo: Only syntax highlighting?

### ISSUE THREAD

**Issue by prenaux** [jrblevin/markdown-mode#357]
I'd like to have only the syntax highlighting, is there a way to enable markdown-mode so that there's no magic happening - turn off all the automagic completions.

One thing that is causing me constant frustration is the auto complete of "```" is there a way to least turn that off, if nothing else?

**Comment by jrblevin** [comment]
You can turn off GFM code block completion with `markdown-gfm-use-electric-backquote`.

I’m not sure what other completions you’re referring to. If you can give more examples then perhaps I can find the settings for them, or you can browse through `M-x customize-mode` or search the README. There is no “master switch” for all non-don’t-lock-related functions though.
