### ISSUE TITLE
Wrong fontification of bold and italic text in the presence of punctuations

### ISSUE THREAD

**Issue by theGreatWhiteShark** [jrblevin/markdown-mode#359]
On commit 74c0a06 

Whenever a punctuation symbol follows the delimiters of bold font and an italic section is present afterwards, the rendering in between is slightly off. For a change in order (first italic, then bold) the problem does not occur.

```
**Fat**, normal *italic*, normal **fat**
```

This is probably related to issue #223 . In addition, it does **not** occur in `gfm-mode`

**Comment by syohex** [comment]
I have merged #473. Please check latest version.

**Comment by theGreatWhiteShark** [comment]
nice. Thanks a lot!
