### ISSUE TITLE
Can't install by preferred procedure

### ISSUE THREAD

**Issue by autonomousapps** [jrblevin/markdown-mode#364]
## Expected Behavior

Following the install instructions works.

## Actual Behavior

Attempting to follow the preferred instructions and install `markdown-mode` results in that package not being found. The only package I can find that begins with `mark` is `markchars`

## Software Versions

- Emacs: 25.2.2
- OS: Ubuntu 18.04

> GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian

**Comment by raxod502** [comment]
Did you run `M-x package-refresh-contents`? This is required before running package management operations, and it is not done automatically.

**Comment by autonomousapps** [comment]
The documentation says (my emphasis)
> Then, **after restarting Emacs** or evaluating the above statements, issue the following command

However, having said that, `M-x package-refresh-contents` does work.

**Comment by raxod502** [comment]
You are correct; the instructions in the documentation are incomplete. Perhaps they should be updated.
