### ISSUE TITLE
Feature request: syntax highlighting of fenced code blocks

### ISSUE THREAD

**Issue by cpitclaudel** [jrblevin/markdown-mode#372]
org-mode has good infrastructure for syntax-highlighting subregions of a buffer; the code is fairly simple

## Expected Behavior

Code blocks delimited by GFM triple-backticks should be highlighted with the appropriate mode.

## Actual Behavior

Code blocks look sad an plain.

A key binding to edit the code block in a separate buffer would also be very nice.

**Comment by jrblevin** [comment]
See `markdown-fontify-code-blocks-natively` and <kbd>C-c C-x C-f</kbd> (`markdown-toggle-fontify-code-blocks-natively`). Unless I misunderstood, this does what you want.

**Comment by vspinu** [comment]
@cpitclaudel also have a look at [poly-markdown](https://github.com/polymode/poly-markdown/).
