### ISSUE TITLE
Pipe escape sequence in table

### ISSUE THREAD

**Issue by malthe** [jrblevin/markdown-mode#374]
The following example doesn't format correctly:
```markdown
| Column 1       | Column 2     | Column 3     |
| :------------- | :----------: | -----------: |
|  Cell Contents | More Stuff   | And Again    |
| You Can Also   | Put Pipes In | Like this \| |
```
The pipe escape sequence seems to be ignored.

**Comment by saf-dmitry** [comment]
Please see https://github.com/jrblevin/markdown-mode/issues/308#issuecomment-357877118

**Comment by jrblevin** [comment]
Thanks for the report. Closing as a duplicate of #308.
