### ISSUE TITLE
Hide backslash escapes when markdown-hide-markup

### ISSUE THREAD

**Issue by fbergroth** [jrblevin/markdown-mode#377]
It would be nice if backslash escapes got hidden when enabling markup hiding.

For instance, `\*abc\*` would be rendered as `*abc*`.

See https://daringfireball.net/projects/markdown/syntax#backslash

**Comment by jrblevin** [comment]
Thanks—nice suggestion.

**Comment by panteleimon-a** [comment]
any updates?

**Comment by syohex** [comment]
I have merged #756. Is there still a problem about this ?
