### ISSUE TITLE
Ability to disable markdown-insert-gfm-code-block prompt

### ISSUE THREAD

**Issue by mcandre** [jrblevin/markdown-mode#38]
I appreciate the option to specify a language name for gfm triple backticks pre-formatted code blocks, but 99% of the time, I always want to skip it.

Could we introduce a configurable variable for whether the prompt is raised, or nil, or some preferred default language name is used?

**Comment by jrblevin** [comment]
This sounds good to me. I envision a minibuffer prompt with completion based on previously used language keywords in the current buffer (using `read-from-minibuffer` with the `hist` and `default-value` arguments). A global fallback default (for the first code block in a buffer) could be defined in a custom variable. There are other things I need to work on first, so if anyone else wants to write a patch in the meantime that would speed things up.

As a workaround for now you could re-bind <kbd>\`</kbd> to `self-insert-command` in the `gfm-mode-hook` (just added today).

**Comment by cosmicexplorer** [comment]
I would think it'd be more appropriate to have a list of all the recognized languages gfm provides (which we'd have to update every so often) and do a `completing-read` (with history and default-value, and global default like you said) from that list instead of just `read-from-minibuffer`.

**Comment by jrblevin** [comment]
Having a pre-specified list of languages is a great idea. I agree that completion would be preferred. I actually thought `read-from-minibuffer` did that, but I given the names I suppose it only provides history, not history _and_ completion. If you could take a look at this, that would be great!

**Comment by jrblevin** [comment]
We now have completion for programming language names as described above with some additional enhancements. Also see the new variable `markdown-gfm-use-electric-backquote`, which determines whether to use `markdown-electric-backquote` when backquote is pressed three times (default: `t`). Thanks to @cosmicexplorer for implementing this!
