### ISSUE TITLE
`markdown-preview` should at least render <pre> for GFM- triplebackticks

### ISSUE THREAD

**Issue by edburns** [jrblevin/markdown-mode#381]
## Expected Behavior

Executing C-c C-c p to run `markdown-preview` helpfully shows a quick
HTML rendering of the markdown.  I would expect text inside of GFM
triple-backticks to be rendered at least within a &lt;pre&gt;.

## Actual Behavior

The content of GFM triple-backticks are not rendered as &lt;pre&gt;.  Rather, they are rendered as

&lt;p&gt;```

## Steps to Reproduce

Put some text inside GFM triple-backticks and run `M-x markdown-preview`.

Ensure that the issue is reproducible using `emacs -Q`.

Yes.

## Backtrace

NA

## Software Versions

- Markdown Mode: From Git on 2019-02-05, 2.4-dev
- GNU Emacs 25.2.2 (x86_64-apple-darwin15.6.0, GTK+ Version 2.18.9) of 2017-04-22
- Emacs: 25.3.2
- OS: Darwin ejburns-mac 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

**Comment by edburns** [comment]
FWIW, IntelliJ Idea's Markdown rendering is really great.

**Comment by jrblevin** [comment]
Thanks for the report. `markdown-mode` doesn't generate this preview itself, rather it hands off the Markdown source to your installed Markdown processor. See the variable `markdown-command`. By default it just looks for something called `markdown`. I'd guess that command on your system doesn't support GFM code block syntax. You might want to give MultiMarkdown or Pandoc a try.

**Comment by edburns** [comment]
Thanks, I installed `multimarkdown` and it solves my problem.  I appreciate it.
