### ISSUE TITLE
No table editing capabilities

### ISSUE THREAD

**Issue by tim-hilt** [jrblevin/markdown-mode#390]
## Expected Behavior

Table Formatting capabilities are present (Auto- alignment; expanding with |- [TAB]; markdown-insert-table with C-c C-s t ...)

## Actual Behavior

Table formatting capabilities seem to be not present at all. Neither shortcuts nor actual commands with M-x work

## Steps to Reproduce

Installation via Melpa; setup:

```
(use-package markdown-mode
	:ensure t
	:mode (("README\\.md\\'" . gfm-mode)
				 ("\\.md\\'" . markdown-mode)
				 ("\\.markdown\\'" . markdown-mode))
	:init (setq markdown-command "multimarkdown"))

```

## Software Versions

- Markdown Mode: v 2.3 (Melpa)
- Emacs: 26.2
- OS: Arch Linux

**Comment by saf-dmitry** [comment]
Markdown Mode as of v2.3 has no table editing functionality. To use table editing functions you need a more recent version.

**Comment by tim-hilt** [comment]
So, would directly installing from GitHub take me to the most recent version?

**Comment by saf-dmitry** [comment]
> So, would directly installing from GitHub take me to the most recent version?

Yes, though I think MELPA version should be quite up-to-date too.

**Comment by tim-hilt** [comment]
I upgraded to the GitHub-Version and it works the way I expected it to. Thanks for all your work! markdown-mode was a great experience for me so far!
