### ISSUE TITLE
cleanup-list-numbers doesn't work when there's leading space

### ISSUE THREAD

**Issue by legends2k** [jrblevin/markdown-mode#392]
When there're leading spaces in a numbered lists' numbers, `markdown-cleanup-list-numbers` renumbers the items incorrectly.

## Steps to Reproduce
Have a buffer in `markdown-mode` and the following text

```
Shortcuts
---------
  2. Horizontal rule: `C-c C-s -`
  3. Underlined header `C-c C-s !`
 10. Convert to HTML: `C-c C-c m`
```

Press  <kbd>C-c C-c n</kbd> to reorder numbers.

## Expected Output
```
  1. Horizontal rule: `C-c C-s -`
  2. Underlined header `C-c C-s !`
  3. Convert to HTML: `C-c C-c m`
```
## Actual Output

```
Shortcuts
---------
  1. Horizontal rule: `C-c C-s -`
  2. Underlined header `C-c C-s !`
 1. Convert to HTML: `C-c C-c m`
```
## Software Versions

- Markdown Mode: markdown-mode, version 2.4-dev
- Emacs: 26.2
- OS: Archlinux

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #459. Please check latest version.
