### ISSUE TITLE
Bug in markdown-split-window-direction

### ISSUE THREAD

**Issue by dchenbecker** [jrblevin/markdown-mode#396]
According to the defcustom for markdown-split-window-direction, 'vertical
and 'right are equivalent, and 'horizontal and 'below are equivalent, but
the point of use had the meaning of 'vertical and 'horizontal reversed.

A fix has been PRd in #394 

## Expected Behavior

Setting `markdown-split-window-direction` to `right` should result in a vertical split

## Actual Behavior

It produces a horizontal split

## Steps to Reproduce

`(setq markdown-split-window-direction 'right)`

Then enable live preview for the buffer. The window will split horizontally

## Software Versions

- Markdown Mode: 2.4-dev, from Melpa
- Emacs: 26.1
- OS: macOS Sierra

**Comment by syohex** [comment]
No. It is correct in emacs terms. Please see document `split-window-vertically` and `split-window-horizontally` and check those behaviors.
