### ISSUE TITLE
Visiting a .md file: (wrong-type-argument syntax-table-p nil)

### ISSUE THREAD

**Issue by manuel-uberti** [jrblevin/markdown-mode#398]
## Expected Behavior

When I visit a `.md` file, I expect `markdown-mode` to be activated.

## Actual Behavior

See Backtrace.

## Steps to Reproduce

1. `emacs -Q`
2. `M-x package-initialize`
3. `C-x C-f ~/test.md`

## Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument syntax-table-p nil)
  set-syntax-table(nil)
  syntax-propertize(1)
  markdown-mode()
  set-auto-mode-0(markdown-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer test.md> "~/test.md" nil nil "~/test.md" nil)
  find-file-noselect("~/test.md" nil nil t)
  find-file("~/test.md" t)
  funcall-interactively(find-file "~/test.md" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

## Software Versions

- Markdown Mode: version 2.4-dev
- Emacs: 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30) of 2019-06-05
- OS: Ubuntu 18.04

**Comment by manuel-uberti** [comment]
One more note: I built my Emacs version from trunk, (commit: `0b3982b1a3892486fd9e4916b9cfafa12ddd9137`), which involves `syntax.el`.

**Comment by manuel-uberti** [comment]
I rebuilt without that commit, and everything works fine. Feel free to close this if you feel it's not a problem with `markdown-mode`.

**Comment by aplanas** [comment]
Also makes the buffer uneditable

```
Error during redisplay: (internal--syntax-propertize 305) signaled (wrong-type-argument syntax-table-p nil)
```

**Comment by manuel-uberti** [comment]
It was a bug on Emacs `master`. Pulling the latest commit now and rebuilding fixes this. 

Sorry for the noise.
