### ISSUE TITLE
Warning (bytecomp): ‘flymake-mode-off’ is an obsolete function (as of 26.1); use ‘flymake-mode’ instead.

### ISSUE THREAD

**Issue by aplanas** [jrblevin/markdown-mode#399]
## Actual Behavior

When byte compiling markdown-mode from melpa, this warning is shown in the *Compile-Log* buffer.

```
Warning (bytecomp): ‘flymake-mode-off’ is an obsolete function (as of 26.1); use ‘flymake-mode’ instead.
Warning (bytecomp): ‘flymake-mode-on’ is an obsolete function (as of 26.1); use ‘flymake-mode’ instead.
Warning (bytecomp): Alias for ‘markdown-mode-font-lock-keywords’ should be declared before its referent [2 times]
```

- Markdown Mode: markdown-mode-20190305.319
- Emacs: 27.0.50
- OS: openSUSE Tumbleweed

**Comment by syohex** [comment]
- markdown-mode.el never uses flymake functions
- `markdown-mode-font-lock-keywords` issue is already fixed.
- There are no byte-compile warnings
