### ISSUE TITLE
C-u M-RET doesn't preserve list type

### ISSUE THREAD

**Issue by jrblevin** [jrblevin/markdown-mode#4]
Putting the point after "AAA" in the following sample and pressing C-u M-RET inserts "1." (properly deindented) instead of "*":

```
1. A
    * AA
        1. AAA
```

That is, it produces

```
1. A
    * AA
        1. AAA
    1.
```

instead of

```
1. A
    * AA
        1. AAA
    *
```

Thanks to @cpitclaudel for reporting this.

**Comment by cpitclaudel** [comment]
Thanks!
