### ISSUE TITLE
Bug - markdown-cycle misbehaves with markup hiding

### ISSUE THREAD

**Issue by contrapunctus-1** [jrblevin/markdown-mode#400]
1. Create a buffer with markdown-mode, with markup hiding enabled
2. Create two headings, each with some content.
3. With point on the second heading, run markdown-cycle. The cycling occurs once, and point goes back to the previous line (!). Running markdown-cycle will now indent the previous line. Thus, cycling of headings breaks.

Emacs v25.1.1, markdown-mode commit 115f77d (latest at the time of writing).

**Comment by syohex** [comment]
I cannot reproduce this issue. Please check latest version. If you still have issue, then please show how to reproduce the issue in more detail.
