### ISSUE TITLE
markdown-css-paths  not work ?

### ISSUE THREAD

**Issue by zhangjie2012** [jrblevin/markdown-mode#402]
## Expected Behavior

emacs markdown mode preview set css file render.

## Actual Behavior

    (setq markdown-css-paths `(,(expand-file-name "~/.emacs.d/markdown.css")))

not work, I remember worked for me last year.

## Software Versions

- Markdown Mode: 2.3
- Emacs: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0) of 2018-05-29

**Comment by uherbstsolace** [comment]
Same here (also on Mac, if this is important)

**Comment by zhangjie2012** [comment]
@uherbstsolace 

I had moved to `org-mode` :dog:

**Comment by syohex** [comment]
I cannot reproduce

```
(require 'markdown-mode)
(setq markdown-command "pandoc")
(setq markdown-css-paths `(,(expand-file-name "~/.emacs.d/markdown.css")))
```

And `M-x markdown-preview` and check its source then It contains above css tag. If you still have this issue, please show us how to reproduce in more detail.
