### ISSUE TITLE
Non-default markdown-list-indent-width is not well-supported

### ISSUE THREAD

**Issue by raxod502** [jrblevin/markdown-mode#405]
## Expected Behavior

With `(setq markdown-list-indent-width 2)`, this fontification:

![image](https://user-images.githubusercontent.com/6559064/60764156-f2956300-a038-11e9-93d6-08a88c68f343.png)

## Actual Behavior

With `(setq markdown-list-indent-width 2)`, this fontification:

![image](https://user-images.githubusercontent.com/6559064/60764157-0771f680-a039-11e9-854a-869ba36898ef.png)

## Steps to Reproduce

Evaluate `(setq markdown-list-indent-width 2)` and then paste into a `markdown-mode` buffer:

```md
* level 1
  * level 2
    * level 3
      * level 4
        * level 5
```

## Software Versions

- Markdown Mode: revision 115f77df9755c6a453f3e5d9623ff885d207ea82 of 2019-07-06 via `straight.el`
- Emacs: 26.2
- OS: Manjaro Linux

## Diagnosis

Applying [this diff](http://ix.io/1NU6/diff) fixes the issue. I have no idea what causes the specific problem above, but it seems that any value of `markdown-list-indent-width` other than the default cannot possibly be well-supported given how many places the number 4 is hardcoded.

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #446. Please check latest version
