### ISSUE TITLE
Links with escaped brackets are not handled properly. 

### ISSUE THREAD

**Issue by yyoncho** [jrblevin/markdown-mode#409]
## Expected Behavior

Links like that should be rendered(like github does):

[run(Class, String \[\])](http://foo.com)

## Actual Behavior

```
[run(Class, String \[\])](http://foo.com)
```

## Steps to Reproduce

have a document with such link

## Backtrace

N/A
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: fix-company-lsp (rev. 2c905a0e8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

**Comment by ideasman42** [comment]
Noted this issue here: https://emacs.stackexchange.com/q/55056/2418

Any info on displaying plain docs as plain text would be an improvement.

**Comment by syohex** [comment]
I have merged #484. Please check latest version.
