### ISSUE TITLE
Invalid matching of emphasize in html

### ISSUE THREAD

**Issue by jo-so** [jrblevin/markdown-mode#410]
## Expected Behavior

In HTML blocks no matching of `*`, `_` or `` ` `` should happen.

## Actual Behavior

In
```
<html>
<head>
  <meta name="twitter:site" content="@jo_so7">
  <meta name="twitter:creator" content="@jo_so7">
</head>
<body>
```

the `twitter:creator` and all around becomes highlighted as emphasized.

## Steps to Reproduce

1. Open a file with the above code `emacs -Q --load path/to/markdown-mode.el /tmp/test.md`
2. Move point to `twitter:creator`
3. Press `C-u C-x =`
1. The line `  face                 (markdown-html-attr-name-face markdown-italic-face)` contains `italic`

## Software Versions

- Markdown Mode: `2.4-dev`
- Emacs: `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-07-22, modified by Debian`
- OS: Debian

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged PR #441. Please check latest version.

**Comment by jo-so** [comment]
Does the PR #441 also address code spans like this?
```
<meta abc="`..." def="`..." />
```

**Comment by syohex** [comment]
> Does the PR #441 also address code spans like this?

No

However is there any use case with such attribute value(starts with backtick)?

**Comment by jo-so** [comment]
Maybe this:

```
<pre><code>
% echo `date -s`
</code></pre>
```

**Comment by syohex** [comment]
It looks backticks  are not in HTML tag attribute field.

**Comment by jo-so** [comment]
Shohei YOSHIDA hat am Mo 13. Apr, 05:59 (-0700) geschrieben:
> It looks backticks  are not in HTML tag attribute field.

Yes, but they are in an HTML block and become highlighted, while they
don't match a Markdown element. This becomes annoying if they span
multiple lines.

<head>
  <title>This is about backticks `</title>
  <meta name="twitter:site" content="@jo_so7">
  <meta name="twitter:creator" content="@jo_so7">
  <meta name="twitter:domain" content="alea.gnuu.de">
  <meta name="og:title" content="This is about backticks `" />
</head>

**Comment by syohex** [comment]
I see however I suppose fixing that issue is very difficult with current implementation. I suppose you can use decimal/hexadecimal reference like `&#96;` for avoiding this issue or use html-mode instead of markdown-mode for writing such HTML or write patch.
