### ISSUE TITLE
Make 'markdown-code-face' scale when font size gets changed

### ISSUE THREAD

**Issue by mrkkrp** [jrblevin/markdown-mode#412]
## Expected Behavior

When I scale font size with e.g. `text-scale-adjust` font size of code snippets should also change.

## Actual Behavior

It stays at its original value so that prose gets displayed with bigger font, while code remains relatively small:

![markdown-font-bug](https://user-images.githubusercontent.com/8165792/66271007-8dc8ef00-e859-11e9-8cc2-4d4644a07218.png)

## Steps to Reproduce

1. Open a buffer with markdown document.
2. Start increasing font size with e.g. `C-x C-+`.
3. Note the bug.

## Software Versions

* Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-08-10
* Markdown mode version: 2.4-dev
* OS: NixOS

**Comment by syohex** [comment]
![markdown-412](https://user-images.githubusercontent.com/554281/81709693-05749180-94ad-11ea-9697-1e1f206eac2c.gif)

Does this issue still happen ? I cannot reproduce this issue with latest version.

**Comment by mrkkrp** [comment]
Seems to work correctly now.
