### ISSUE TITLE
function `markdown-display-buffer-other-window` reinvents display-buffer facilities

### ISSUE THREAD

**Issue by bymoz089** [jrblevin/markdown-mode#413]
## function `markdown-display-buffer-other-window` reinvents display-buffer facilities but in a bad way.

Standard function `display-buffer` can be configured by variable `display-buffer-alist` to open new buffers in a way the user expects and whishes (e.g. open in a new frame, open in a side window, replace current buffer, open in a new window etc.).       

Function `markdown-display-buffer-other-window` reinvents those facilities, but can not be configured in any way. The result is, that `markdown-live-preview-mode` behaves in a weird and completely ignores user settings for `display-buffer`.

Calls to `markdown-display-buffer-other-window` should be replaced by calls to `display-buffer`.

## As a quickfix it is posible to define a function alias:

    (defalias 'markdown-display-buffer-other-window 'display-buffer)

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: 25.1.1 and newer
- OS: all

**Comment by syohex** [comment]
I have merged #465. If user sets `display-buffer-alist` then `markdown-down-display-buffer-other-window` uses `display-buffer` instead of own implementation.
