### ISSUE TITLE
Make `markdown-back-to-heading` interactive

### ISSUE THREAD

**Issue by miguelmorin** [jrblevin/markdown-mode#415]
I would like to bind the function `markdown-back-to-heading` to a keypress. The function is non-interactive, so I have to wrap it in an interactive function.

## Expected Behavior

The following command should work:

```
(define-key markdown-mode-map (kbd "C-c C-h") 'markdown-back-to-heading)
```

## Actual Behavior

Instead, pressing `C-c C-h` throws an error: `Wrong type argument: commandp, markdown-back-to-heading`.

## Steps to Reproduce

1. Evaluate `(define-key markdown-mode-map (kbd "C-c C-h") 'markdown-back-to-heading)`
2. Open a buffer with Markdown mode
3. Press `C-c C-h`

## Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument commandp markdown-back-to-heading)
  call-interactively(markdown-back-to-heading nil nil)
  command-execute(markdown-back-to-heading)
```

## Software Versions

- Markdown Mode: markdown-mode, version 2.4-dev
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
- OS: macOS Mojave 10.14.6

**Comment by syohex** [comment]
I have merged #458 please check latest version
