### ISSUE TITLE
Commit 23113fa broke fenced code blocks

### ISSUE THREAD

**Issue by zmwangx** [jrblevin/markdown-mode#42]
Currently, trying to edit anything immediately after a fenced code block (in either `markdown-mode` or `gfm-mode`) only results in Emacs completely freezing up. Try this:

    > cat hello.md
    ```
    hello
    ```
    > emacs --no-init-file --load markdown-mode.el hello.md

Now go to the end of the file and try to insert anything. Nothing happens (except for 100% CPU usage).

Bisecting reveals that the problematic commit is 23113fa13292712899ad66c355dcd44c0ee9055c.

**Comment by jrblevin** [comment]
Thanks for this detailed report. I also encountered this issue yesterday and bisected, leading me to the same commit. I *thought* I had fixed it already though, but apparently not. I'll look into it again.

**Comment by jrblevin** [comment]
I think this is fixed now. Can you verify with the latest commit?

**Comment by zmwangx** [comment]
:+1: Works now (running 1541a097b572899edb30a5b207dee03ed332888f).

**Comment by jrblevin** [comment]
Great—thanks for confirming!
