### ISSUE TITLE
Following wiki link in gfm-mode switches to markdown-mode

### ISSUE THREAD

**Issue by tom-bowles** [jrblevin/markdown-mode#427]
The last thing `markdown-follow-wiki-link` does after opening the target file is to switch the buffer to `markdown-mode`. I'm not sure why this is necessary, as opposed to just leaving the buffer in whatever mode it ends up in after `find-file`, but it's awkward if you have `.md` files set up to open in `gfm-mode` rather than `markdown-mode`. If it is necessary to set the mode, could it detect the current mode in the buffer containing the link and use that rather than being hardcoded to `markdown-mode`?

## Steps to Reproduce

1. Configure `.md` files to open in `gfm-mode`: `(add-to-list 'auto-mode-alist '("\\.md\\'" . gfm-mode))
`.
2. Open a `.md` file containing a wiki link.
2. Follow the wiki link to another `.md` file.
3. Observe that the opened file is now in `markdown-mode`, rather than `gfm-mode` as it is when opened directly with `find-file`.

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: 26.3
- OS: Arch linux

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #444. Please check latest version.
