### ISSUE TITLE
Cannot follow link: Point is not at a Markdown link or URL

### ISSUE THREAD

**Issue by cyrus-and** [jrblevin/markdown-mode#430]
## Expected Behavior

The link should open.

## Actual Behavior

An error is generated:

    Point is not at a Markdown link or URL

## Steps to Reproduce

1. Create a `.md` file with:

    ```
    ---

    [link](https://example.com)

    ---
    ```
2. Click on `link` or `C-c C-o` while the point is on it (the error is `Nothing to follow at point` in this case).

## Software Versions

- Markdown Mode: From MELPA 2.4-dev
- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-12-04
- Emacs: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian
- OS: Debian GNU/Linux 10

**Comment by saf-dmitry** [comment]
I think the problem is that your link is in a YAML metadata block.

**Comment by cyrus-and** [comment]
I think too, but the example is a perfectly fine Markdown file where `---` is the horizontal rule.

**Comment by saf-dmitry** [comment]
If you have `---` at the BOF, it starts a YAML metadata block continuing until the next line containing only `---` or `...`.

**Comment by cyrus-and** [comment]
Yes, what I meant was that links in YAML metadata block should behave as regular links IMHO because there is no mention of YAML in the Markdown specs AFAIK.

**Comment by syohex** [comment]
I have merged #456. Please check latest version.

**Comment by cyrus-and** [comment]
@syohex the `C-c C-o` part is now fixed, thanks! But clicking on the link still yields the same behavior.

**Comment by syohex** [comment]
@cyrus-and I have merged #463. Please check latest version.

**Comment by cyrus-and** [comment]
@syohex great! Everything works fine now, thank you.
