### ISSUE TITLE
pandoc: getCurrentDirectory:getWorkingDirectory: permission denied (Operation not permitted)

### ISSUE THREAD

**Issue by saura8h** [jrblevin/markdown-mode#434]
## Expected Behavior

Rendered output of `.md` file on the browser

## Actual Behavior

When executing `C-c C-c p` to preview the markdown file, web browser open with message:

"pandoc: getCurrentDirectory:getWorkingDirectory: permission denied (Operation not permitted)"

Browser URL starts with:
`file:///private/var/folders/ww/`

[Screenshot](https://ibb.co/VmQdBch)

## Steps to Reproduce

1. Kill all open buffers (to ensure no read-only related issues)
2. Open `.md` file (located in ~/Desktop/project_root/directory)
3. Evaluate the markdown file with `C-c C-c p`

## Software Versions

- Markdown Mode: melpa-stable 2.3
- Emacs: 26.3 (9.0)
- OS: macOS 10.15.3

**Comment by syohex** [comment]
I suppose your temporary directory has no write permission, please check it. And it looks you change temporary directory path(`temporary-file-directory`) from default. I suppose it is better to use default value if you have no problem.

**Comment by saura8h** [comment]
I have made no changes in `temporary-file-directory`. Was able to get around by providing [full disk access to Emacs]  (https://emacs.stackexchange.com/questions/53026/how-to-restore-file-system-access-in-macos-catalina)
