### ISSUE TITLE
Electric backquote and fenced code block inserts extra backtick

### ISSUE THREAD

**Issue by hartzell** [jrblevin/markdown-mode#436]
## Expected Behavior

In a buffer that is in GFM mode, I expect to be able to hit three back quotes, select a language and have a fenced code block be inserted for that language, e.g.

Sadly, I can't figure out how to include an example, it keeps getting rendered instead.

## Actual Behavior

I end up with the expected fenced code block, then a blank line,  and then a lone single back quote.

## Steps to Reproduce

Open a buffer in markdown/GFM mode and insert a fenced code block.

## Software Versions

- Markdown Mode: version 2.4-dev
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
  - installed via Homebrew cask.
- OS: OS X 10.15.4

**Comment by syohex** [comment]
Could you tell us you configuration for reproducing this issue ? Do you enable `electric-pair-mode` or similar packages ? gfm-mode default behavior is as below. hit tree back quotes then markdown-mode queries you, then insert fence code block.

![sample](https://user-images.githubusercontent.com/554281/83140799-9bedb780-a129-11ea-8361-26192bfb97f8.gif)

 Sorry I'm not sure what is your issue.

**Comment by hartzell** [comment]
Ah, got it.  Thanks for your suggestion about electric-pair-mode.

It turns out that I'm using `smartparens-mode`, which has special sub-modes (better term?) which fine-tunes its behavior in for various modes.

There's one for markdown mode that has [a bit of code that helps it get along with markdown/GFM mode](https://github.com/Fuco1/smartparens/blob/6329f779792441b7d1157dfc8646a8b3e49b3a33/smartparens-markdown.el#L54).

I was enabling smartparens with a simple call to use-package that was neither wiring in those special sub-modes nor calling `(require smartparens-config)` so the "collaborate with markdown-mode" support wasn't being used.

Requiring `smartparens-config` has set things right.  FWIW, here's the config that I'm using that is working.  

```lisp
;; smartparens
(use-package smartparens
  :config
  (require 'smartparens-config)
  :hook
  (after-init . (lambda ()
                  (smartparens-global-mode t)
                  (show-smartparens-global-mode t)))
  :delight " ()"
  :bind
  ((:map sp-keymap)
   ("C-M-f" . sp-forward-sexp)
   ("C-M-b" . sp-backward-sexp)
   ("C-M-n" . sp-next-sexp)
   ("C-M-p" . sp-previous-sexp)
   ("C-M-k" . sp-kill-sexp)
   ("C-M-w" . sp-copy-sexp)))
```

**THANKS!**

**Comment by untoreh** [comment]
I have the same problem, but `(require 'smartparens-config)` doesn't solve it.
Smartparens like `electric-pair-mode` has the option `sp-autoinsert-pair` which if toggled on gives this problem with the extra backtick
