### ISSUE TITLE
smarter parsing of bare link end

### ISSUE THREAD

**Issue by VladimirAlexiev** [jrblevin/markdown-mode#439]
Exclude punctuation from the end of a link, followed by space. 
But don't break a link if punctuation appears in the middle of a link.

## Expected Behavior

- When I click on `https://jblevins.org/projects/markdown-mode: nice software` it should go to https://jblevins.org/projects/markdown-mode .
- same for `?!.`
- When I click on `https://jblevins.org/projects/markdown-mode:whatever` it should use the full link

## Actual Behavior

It tries to go to [https://jblevins.org/projects/markdown-mode:](https://jblevins.org/projects/markdown-mode:) and fails

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: 26.1
- OS: Windows 10

**Comment by syohex** [comment]
In [RFC](https://tools.ietf.org/html/rfc3986), `:` is valid character for URL. I suppose you should use link syntax(`[]()`) instead of bare URL in such case.

**Comment by VladimirAlexiev** [comment]
@syohex Have you ever seen a real URL **ending** in `?!.:` ? Such chars can be part of a URL but if followed by space, they should be excluded from the URL.

**Comment by syohex** [comment]
> Have you ever seen a real URL **ending** in `?!.:`

No. However it is valid URL.

memo
- VSCode markdown extension handles colon as part of URL even if URL ends with `:`
- Gist markdown viewer does not handles colon as part of URL if URL ends with `:`.
