### ISSUE TITLE
After updating the markdown-mode using spacemacs, I restarted spacemans and found an error

### ISSUE THREAD

**Issue by yuanzhhh** [jrblevin/markdown-mode#457]
![截屏2020-04-29下午10 13 05](https://user-images.githubusercontent.com/9876819/80606626-224da580-8a67-11ea-98e5-53a3fe6572aa.png)
@jrblevin

**Comment by syohex** [comment]
It looks your mirror melpa server issue. I cannot reproduce by using official melpa server. Please check your mirror server status.
