### ISSUE TITLE
markdown-hide-markup-in-view-modes doesn't work

### ISSUE THREAD

**Issue by cpitclaudel** [jrblevin/markdown-mode#468]
# Expected Behavior

When `markdown-hide-markup-in-view-modes` is set (the default), markup should be hidden in view-mode buffers.

## Actual Behavior

Markup is not hidden in view-mode buffers.

## Steps to Reproduce

1. Turn on markdown-view-mode

The problem is that the body of `markdown-view-mode` runs after that of its parent mode, so copying the value of markdown-hide-markup-in-view-modes doesn't to anything.

(also, that page: https://www.lunaryorn.com/posts/reproduce-bugs-in-emacs-q#section-how-do-you-reproduce-a-bug-in-emacs--q is 404 now; I usually use this stackexchange question instead: https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems )

- Markdown Mode: 2.4dev
- Emacs: 26.3

**Comment by syohex** [comment]
I have merged #469. Please check latest version

**Comment by cpitclaudel** [comment]
Thanks a lot! Works for me, though that's now 4 places places where the same code manipulating buffer specs is present.  Maybe it would be simpler to add a single set-visibility function and call that from markdown-mode, from -toggle, from mardown-view-mode, and from gfm-view-mode? ^^

**Comment by syohex** [comment]
I don't suppose such refactoring is not necessary.
