### ISSUE TITLE
Column grows wider every markdown-cycle if a cell ends in `\|`

### ISSUE THREAD

**Issue by tspiteri** [jrblevin/markdown-mode#489]
##  Steps to Reproduce

1. In a markdown file insert the text `| x \| |` which is a table with one cell.
2. Cycle to the next cell using <kbd>TAB</kbd>.

An extra space is added to the cell while it shouldn't.

## Software Versions

```
;; Version: 2.4-dev
;; Package-Version: 20200514.16
```

**Comment by syohex** [comment]
I have merged #490. Please check latest version.
