### ISSUE TITLE
Fold the content when markdown buffer has created

### ISSUE THREAD

**Issue by idanko** [jrblevin/markdown-mode#503]
Hello,
I try to make org and md buffers look the same when they have opened. In particular, I would make them folded from the highest level up to the lowest one just for showing the headers. I can do this manually with a few strokes: put the cursor to the first `#` tag and press TAB, but I'm curious may I do this automatically after the buffer just opened?

**Comment by syohex** [comment]
How about a following hook setting ?

```lisp
(defun my/markdown-mode-hook ()
  ;; Note: your markdown files always have level one header
  (outline-hide-sublevels 1))

(add-hook 'markdown-mode-hook 'my/markdown-mode-hook)
```

Or this ?

```lisp
(defun my/markdown-mode-hook ()
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward "^#" nil t)
      (outline-hide-subtree))))

(add-hook 'markdown-mode-hook 'my/markdown-mode-hook)
```

**Comment by idanko** [comment]
It works, was easy, though. Thanks!

**Comment by idanko** [comment]
@syohex on the last example you probably meant `while` instead of `when`, otherwise it will fold only the first occurrence:
```emacs-lisp
(defun my/markdown-mode-hook ()
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "^#" nil t)
      (outline-hide-subtree))))
```

BTW, the first example (using `(outline-hide-sublevels 1)`) leads to some weird results: all the document is folded with only three dots and generic unfolding method (binds to TAB) doesn't work.

**Comment by syohex** [comment]
Ah, I assumed there is a only one level 1 section in a document.
