### ISSUE TITLE
Images linked with `raw=true` don't render

### ISSUE THREAD

**Issue by KarthikNayak** [jrblevin/markdown-mode#511]
## Expected Behavior

So when images are linked via markdown and the link ends with `?raw=true` they fail to render. 
Often this is added to refer to relative paths in Github: https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository

## Actual Behavior

Images with the following syntax `![Alt text](./relative/path/to/img.jpg?raw=true "Optional Title")` don't render.

## Steps to Reproduce

1. Add an image ./relative/path/to/img.jpg 
2. Create markdown a.md with `![Alt text](./relative/path/to/img.jpg?raw=true "Optional Title")`

## Software Versions

- Markdown Mode: 20200622.20
- Emacs: 26.3
- OS: Linux

**Comment by syohex** [comment]
I have merged #513. Please check latest version.
