### ISSUE TITLE
Whitespace in link URLs confuses markdown--browse-url

### ISSUE THREAD

**Issue by cpcallen** [jrblevin/markdown-mode#514]
To keep line lengths within a fixed limit (e.g., 80 characters), it is occasionally useful to insert a `\n` after the `](` when linking to a long URL.  This whitespace is stripped out by many markdown processors (notably: GitHub), so it does not affect how the markdown is rendered to HTML.

Unfortunately, this extra newline causes `markdown-mode` to behave erroneously when the link is clicked.

## Steps to Reproduce

1. With the following text in a Markdown buffer,
```
[Works](http://example.com)
[Broken](
http://example.com)
```
2. …click the links "Works" and "Broken".

## Expected Behaviour

Clicking on either "Works" or "Broken" will cause one's web browser to open `http://example.com`
 
## Actual Behaviour

The "Works" link behaves as expected, but the "Broken" link causes emacs to find a file named `example.com` in a non-existent directory; `M-x make-directory` causes a directory named `\nhttp:` to be created (yes: directory name starts with a newline character AFAICT; this causes all manner of strange behaviour from emacs, Finder, `ls`, etc.)

## Software Versions

- Markdown Mode: From MELPA, version 2.5-dev
- Emacs: 26.3 (Build 18D109)
- OS: macOS Mojave 10.14.6

**Comment by syohex** [comment]
I have merged #515. Please check latest version.
