### ISSUE TITLE
Feature request: theme markdown-metadata-value-face

### ISSUE THREAD

**Issue by manuel-uberti** [jrblevin/markdown-mode#516]
Sorry, I am skipping the issue template because this is not an issue. It's more of a feature request.

Over at @protesilaos's Modus Themes repository, we are discussing whether it would be possible to specify a `default` or `fixed-pitch` font face for `markdown-metadata-value-face`.

You can read the discussion [here](https://gitlab.com/protesilaos/modus-themes/-/issues/62), but the gist of it is that I'd like to turn on `variable-pitch-mode` when writing my prose in `markdown-mode`, and I'd like to see the metadata themed with a monospaced font.

What do you think?

**Comment by syohex** [comment]
Is it enough to set such configuration in your configuration file instead of changing default font configurations? I'm not sure every markdown-mode users prefer such configuration.

**Comment by manuel-uberti** [comment]
Sure thing, or maybe making it customizable via a `defcustom`.

**Comment by syohex** [comment]
> maybe making it customizable via a `defcustom`.

I suppose it is not a good idea. markdown-mode has a lot of faces and we need to introduce such flags for each faces if we adopt this approach.

So please set fixed font configuration in your configuration file if you want to use monospace font for some faces.

**Comment by manuel-uberti** [comment]
I will. Thank you for the suggestion.
