### ISSUE TITLE
Markup can break sentence commands

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#517]
I find some markdown markup can break Emacs' sentence commands.  The sentence commands (e.g., `forward-sentence` on `M-e`) account for closing delimiters at the end of a sentence like parenthesis.  In these examples (assuming using two spaces after sentences) `M-e` will move to the start of each sentence:

    Sentence one.  Sentence two.  Sentence three.
    (Sentence four.)  "Sentence five."  Sentence six.

But these don't work, `M-e` will skip over the end of some sentences:

    *Sentence one.*  **Sentence two.**  Sentence three.
    _Sentence four._  Sentence five.  Sentence six.

I'd like `M-e` to stop at the end of each of those sentences.  If it does then the other sentence commands should work too.

I believe the solution is in the option `sentence-end-base` which is where the delimiters skipped are listed.  I think adding * and _ to the second grouping solves it.  So "[.?!…‽][]\"'”’)}\*_]*".  You may need to change that to support other similar markup like ~.

- Markdown Mode: 2.5-dev
- Emacs: 26.3
- OS: macOS 10.14.6

**Comment by syohex** [comment]
Thanks for issuing. I have merged #518. Please check latest version
