### ISSUE TITLE
GFM mode italics fontification incorrect for single characters

### ISSUE THREAD

**Issue by rriegs** [jrblevin/markdown-mode#524]
## Expected Behavior

This issue is related to #448, which modified fontification in GFM mode such that underscores (`_`) within tokens did not fontify while asterisks (`*`) did, i.e. such that

    em*pha*sis

    no_emph_asis

were fontified or not as suggested by their text.  Further, asterisks and underscores at edges of words should continue to function as expected, such that each of

    *abc*

    _abc_

    *a*

    _b_

are emphasized.

## Actual Behavior

The new detection regex seems to be missing the latter two cases, i.e. `*a*` and `_b_` are not getting emphasized.  Worse, the leading asterisk or underscore is available to match a later trailing such symbol, such that the entire string

    *a* other text *abc*

is emphasized, when only the first and last token should be.

## Software Versions

markdown-mode version 2.5-dev (installed via MELPA)
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
Ubuntu 20.04.1 LTS

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #526. Please check latest version.
