### ISSUE TITLE
GFM mode bold fontification incorrect for within-token underscores

### ISSUE THREAD

**Issue by rriegs** [jrblevin/markdown-mode#525]
## Expected Behavior

This issues is essentially the same as #448 but for bold fontification via double underscore (`__`).  In GFM mode, like single asterisk and underscore, within-token double asterisk should fontify as bold while within-token double underscore should not fontify, i.e.

    **strong**

    st**ro**ng

    **str**ong

    str**ong**

    **still strong**

    **still str**ong

    sti**ll strong**

    sti**ll str**ong

    __strong__

    not__str__ong

    __not__strong

    not__strong__

    __still strong__

    no__t strong__

    __not str__ong

    no__t str__ong

should be (at least partially) fontified as their respective text suggests.

## Actual Behavior

Like double asterisk, double underscore fontifies in all of the above cases.

Note: See also #524, which observes a bug when just one character is surrounded by single asterisks or underscores.

## Software Versions

markdown-mode version 2.5-dev (installed via MELPA)
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
Ubuntu 20.04.1 LTS

**Comment by syohex** [comment]
I have merged #528. Please check latest version
