### ISSUE TITLE
Prefix of markdown-cycle doesn't work

### ISSUE THREAD

**Issue by jo-so** [jrblevin/markdown-mode#530]
The [`(eq arg t)`](https://github.com/jrblevin/markdown-mode/blob/ef2cb4d94af68908a4963afa492afba876725128/markdown-mode.el#L6694) never matches a prefix argument of `C-u TAB`. Maybe `(arg)` as check would be enough.

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #531. Please check latest version.
