### ISSUE TITLE
GFM font-lock issue with two bold terms

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#534]
The text `**Falemur** and **Sam**` is rendered differently in `gfm-mode` and `markdown-mode`.  In both the names are correctly shown in `markdown-bold-face`.  In `markdown-mode` the word "and" is shown correctly in the default face, but in `gfm-mode` it is incorrectly shown in `markdown-italic-face`

- Markdown Mode: 2.5dev 20200826.42
- Emacs: 27.1
- OS: macOS Catalina

**Comment by syohex** [comment]
I have merged #535. Please check latest version.
