### ISSUE TITLE
`markdown-insert-link` does not accept spaces in "Link text" field

### ISSUE THREAD

**Issue by omnicr0n** [jrblevin/markdown-mode#537]
## Expected Behavior
After invoking `markdown-insert-link` with `C-c C-l`, it accepts a URL, Link Text, and Title. Upon filling out the fields, it should create a link for whatever was entered in Link Text.

## Actual Behavior
Bug: While I can fill out the URL without trouble, Link Text doesn't seem to accept spaces. That is, if I want to call Link Text "foo bar", I can get as far as "foo". Trying to enter a space returns `[No match]`.

## Steps to Reproduce
1. Invoke `markdown-insert-link`.
2. Enter URL.
3. Try to enter anything in Link Text with a space.

## Software Versions

- Markdown Mode: Version 2.5-dev
- Emacs: GNU Emacs 27.1
- OS: macOS Catalina 10.15.6

**Comment by syohex** [comment]
https://github.com/jrblevin/markdown-mode/issues/509#issuecomment-653780485

Please see above comment. This is `completing-read` specification.
