### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by telephon** [jrblevin/markdown-mode#541]
Accrding to https://daringfireball.net/projects/markdown/syntax we should be able to use relative links:

>If you’re referring to a local resource on the same server, you can use relative paths:

>`See my [About](/about/) page for details.  `

## Actual Behavior

I try to use a file link with this syntax, in the same folder as the other markdown files, the link won't open that file. In my case, it'll suggest creating that file.

## Steps to Reproduce

Add a file in the folder with the name `initial.md`. Add another file with this link:

```
[test](/initial.md/)
```

The link doesn't lead to `initial.md`.

Neither does any the following: `[test](/initial/)`, `[test](/initial)`, `[test](/initial.md)`

## Software Versions

-   Markdown Mode: 2.5-dev
-  Emacs: GNU Emacs 26.3
-  OS: macOS 10.15.6

**Comment by syohex** [comment]
Please write as below for using relative path(Remove `/`)


```markdown
[test](initial.md)
```

See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files.

`/about/` is a relative path in HTML context but it means the path is located at the root of the current web. In markdown context, there is no root and we cannot resolve where `/about/` is.

**Comment by telephon** [comment]
dahh! precisely the only combination I didn't think of. Thanks a lot, @syohex !
