### ISSUE TITLE
Should replace special white space \x00A0 with " " to avoid it shown in view mode

### ISSUE THREAD

**Issue by wztdream** [jrblevin/markdown-mode#545]
Hi,
This case is originally reported in  [lsp-mode](https://github.com/emacs-lsp/lsp-mode/issues/2190), if there is special white space \x00A0 in a string, markdown-mode will show it, which is noisy, you can type this special white space in emacs by `C-x 8 SPC`. See bellow example:

In this case I use **pyls** as python language server in **lsp-mode**, lsp-mode use markdown to render the help doc, so it is better to report this case here too as a reference. It is better to replace it with normal space. By something like `(s-replace "\x00A0" " " str)` in markdown as well.
![noisy](https://user-images.githubusercontent.com/39213018/93568299-834c2a80-f9c2-11ea-9eb2-28eee759c652.png)

**Comment by syohex** [comment]
markdown-mode should not modify buffer content.

If you are worried about `\x00A0` (non breaking space), please try to disable `nobreak-space` face attributes as below.

```lisp
(set-face-attribute 'nobreak-space nil
                    :background nil
                    :underline nil)
```

Or add replacing character code to lsp-mode.
