### ISSUE TITLE
Don't use completing-read when prompting for link texts

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#546]
Markdown-mode uses completing-read when prompting for link texts (https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L3787). This causes the space key to attempt a completion instead of inserting a space in the minibuffer. However, many link texts contain spaces, so this behavior is annoying.

## Expected Behavior

It's possible to input link texts containing spaces without hassle.

## Actual Behavior

Hitting Space at the link text prompt attempts a completion, which typically fails.

## Steps to Reproduce

1. emacs -Q -l markdown-mode /tmp/test.md
2. C-c C-l
3. Enter any URL
4. RET
5. Try entering a link text containing spaces, such as "hello world"

## Software Versions

- Markdown Mode: 2.5-dev
- Emacs: 27.1.50
- OS: Debian testing

**Comment by syohex** [comment]
Please see this comment https://github.com/jrblevin/markdown-mode/issues/509#issuecomment-653780485
