### ISSUE TITLE
Adjacent inline markup mis-recognized

### ISSUE THREAD

**Issue by dabrahams** [jrblevin/markdown-mode#548]
Put this in a file and enable markdown-mode.

```markdown
`(`*italic*`)` plain text
*italic*
```

## Expected Behavior

The word “italic” is rendered in italics (twice) and the “plain text” is rendered in non-italics.

## Actual Behavior

The word “italic” is rendered in non-italics (twice) and the “plain text” is rendered in italics.

## Software Versions

- Markdown Mode: markdown-mode, version 2.5-dev
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-08-16
- OS: MacOS Catalina

**Comment by syohex** [comment]
@dabrahams thanks for reporting issue. I have merged #549. Please check latest version.
