### ISSUE TITLE
why re-read from init-buf-string in markdown-export?

### ISSUE THREAD

**Issue by cosmicexplorer** [jrblevin/markdown-mode#55]
I'm puzzling over some of the code in `markdown-export`. After running `markdown-after-export-hook`, if the buffer is modified by any of the hooks or `markdown-standalone`, it is re-read from that initial state `init-buf-string`. Why is that? snip [here](https://github.com/jrblevin/markdown-mode/blob/c0bb1c9ff6ff80e15e89237527ed4271629008ea/markdown-mode.el#L5120):

``` emacs-lisp
      (run-hooks 'markdown-before-export-hook)
      (markdown-standalone output-buffer-name)
      (with-current-buffer output-buffer
        (run-hooks 'markdown-after-export-hook)
        (save-buffer))
      ;; if modified, restore initial buffer
      (when (buffer-modified-p init-buf)
        (erase-buffer)
        (insert init-buf-string)
        (save-buffer)
        (goto-char init-point))
```

Is there any reason why this is happening? It doesn't seem to affect anything normally, but I'm working on an asynchronous-export feature for fun (#56) and this erases any input the user has entered from the time export begins to the time the process ends.

**Comment by jrblevin** [comment]
This was mostly added in commit ae0aeb3. I had to look back at the description to refresh my memory (but the motivation wasn't really written down there). The idea is that functions that run with `markdown-before-export-hook` are preprocessors of a sort that need to modify the raw Markdown source before being sent to the Markdown processor. For example, one might run a script to carry out automatic equation numbering in a mathematical document. We wouldn't want to actually modify the Markdown document for this, rather, just make the changes temporarily before running Markdown.

**Comment by cosmicexplorer** [comment]
That makes perfect sense. I'll find a way around it for the async thing.
