### ISSUE TITLE
Wrong fontification of emphasis using underscores in GFM mode

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#553]
Emphasis in GFM mode is not recognized when using underscores directly followed by a punctuation mark.

## Expected Behavior

In the example below

     _One_, _two_, or _three_.

_One_, _two_, and _three_ should be emphasized (GitHub behavior).

## Actual Behavior

In the example below

     _One_, _two_, or _three_.

_One_, _two_, and _three_ are not emphasized.

## Software Versions

- Markdown Mode: From Git on 2020-10-15
- Emacs: 26.3
- OS: macOS Mojave v10.14.6

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #554. Please check latest version.
