### ISSUE TITLE
markdown-mode, visual-line-mode, and mwim interaction for line start/end movement

### ISSUE THREAD

**Issue by lyndondrake** [jrblevin/markdown-mode#558]
## Expected Behavior

With `mwim` and `visual-line-mode` enabled, `mwim-beginning-of-code-or-line` should move to the start of the visual line.

## Actual Behavior

Instead, in `markdown-mode` only, it moves to the beginning of the logical line. This only occurs in `markdown-mode` and other text modes such as `org-mode` behave as expected (i.e. movement based on visual lines).

## Software Versions

- markdown-mode, version 2.5-dev
- GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2)) of 2020-10-24
- OS: MacOS 10.15.7

**Comment by syohex** [comment]
`mwim` uses `beginning-of-line` function as default except `message-mode` and `org-mode`. So you need to configure `mwim-beginning-of-line-function` as below for your desirable behavior. Please see document of `mwim-beginning-of-line-function`.

```lisp
(require 'mwim)
(add-to-list 'mwim-beginning-of-line-function '(markdown-mode . beginning-of-visual-line))
(add-to-list 'mwim-beginning-of-line-function '(gfm-mode . beginning-of-visual-line))
```

**Comment by lyndondrake** [comment]
apologies - I'm still learning emacs. Thank you for point me towards this and that fixed it instantly.
