### ISSUE TITLE
Clicking on GFM checkboxes does not work for deeply nested list items

### ISSUE THREAD

**Issue by gabrielmdeal** [jrblevin/markdown-mode#569]
Clicking on deeply nested Github Flavored Markdown checkboxes toggles the wrong checkbox.

## Expected Behavior
It should toggle the checkbox I click.

## Actual Behavior
For deeply nested checkboxes, it toggles an ancestor checkbox.

## Steps to Reproduce

* [ ] One
  * [ ] Two
    * [ ] Three
      * [ ] Four
        * [ ] Five (clicking this checks & unchecks Four)
          * [ ] Six (clicking this checks & unchecks Four)

Click the checkbox for Five or Six.  When I do this, it toggles Four.

## Backtrace

None

## Software Versions

- Markdown Mode: 2.5-dev
- Emacs: 26.1
- OS: Ubuntu 16 LTS

**Comment by gabrielmdeal** [comment]
Fastest bug fix ever! :rocket: 

I just tested your fix and it works perfectly. Thanks! @syohex

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #570.
