### ISSUE TITLE
User-preferred case in GFM language names

### ISSUE THREAD

**Issue by jrblevin** [jrblevin/markdown-mode#59]
For the first GFM fenced code block inserted in a file, the capitalization in the pre-specified language list seems to dominate what is typed by the user. For example, if one enters "Fortran" as the language name the empty code block will be inserted as

    ``` FORTRAN

    ```

while one would have expected to instead see

    ``` Fortran

    ```

(This was previously discussed in #54, but since that PR was merged I am just opening a new issue as a reminder.)

**Comment by cosmicexplorer** [comment]
Yeah, I didn't think about this too long before I implemented it. I wanted to avoid having miscapitalized versions of languages alongside the real ones, so `markdown-add-language-if-new` won't add it to the corpus, and will instead return the element of the corpus that does have the "appropriate" capitalization, if the result of `completing-read` ("Fortran" in this case) is a differently-capitalized version of a language in the corpus.

I'm thinking let's just drop the attempt to squash capitalization and instead add all capitalizations of a language to the buffer-local corpus as they are added, and then return the unmodified language string that the user entered (as you would expect in this case). Do we want to `(let ((completion-ignore-case nil))` then so the user has to confirm a different capitalization? Or no?

**Comment by jrblevin** [comment]
I think I misread your comments/commit messages regarding capitalization. I thought you meant for it to do this already. In any case, I think it would be good to add all capitalizations used. I suppose it should ask for confirmation (once) for the sake of consistency within a file.

**Comment by cosmicexplorer** [comment]
Cool, so if the user enters a capitalization of a language it hasn't seen before, it'll ask to confirm (once) and add it to the corpus just as if it was a new language.
