### ISSUE TITLE
Inserting two spaces after a sentence an "underline character" appears

### ISSUE THREAD

**Issue by Knusper** [jrblevin/markdown-mode#621]
When composing, I usually insert two white spaces after a sentence ended. Thus I can use `M-a` and `M-e` to navigate between sentences.  Now I started using markdown mode, and I am very irritated that after two spaces a underline character appears (see screenshot)
![Screenshot_20210627_131226](https://user-images.githubusercontent.com/4704406/123553479-585ce700-d749-11eb-9953-7ca0e6fe390a.png)

These disappear when I start typing the next sentence.

What is there purpose, and can I turn them off?

## Expected Behavior

No underline character appears when a sentence is finished with two white spaces.

- Markdown Mode: 2.5-dev 
- Emacs: 26.1 
- OS:  Debian 10

**Comment by syohex** [comment]
Sorry for late response.

> What is there purpose

In markdown specification, if a line ends with two or more spaces, then insert `<br /`>. `markdown-mode` highlights such spaces.

- https://spec.commonmark.org/0.30/#hard-line-breaks
- https://daringfireball.net/projects/markdown/syntax#p

> can I turn them off?

Sorry there is no way to disable this feature in current implementation. However you can turn it invisible as below snippet. Could you try this ?

```lisp
(set-face-underline 'markdown-line-break-face nil)
```

**Comment by Knusper** [comment]
I just found the explanation in Sect. 3.12 of the handbook. Ok, but then it seems it is not  correctly implemented, because the line break should only be highlighted if there is an actual line break. For now I stick to turning it invisible. Thanks 😊

**Comment by syohex** [comment]
> Ok, but then it seems it is not correctly implemented, because the line break should only be highlighted if there is an actual line break.

Ah, thanks for information. I'll check it later.

**Comment by pjheslin** [comment]
The treatment by markdown-mode of trailing whitespace is annoying when you have markup-hiding activated.  At the end of a line you type one space and one space appears.  Type another space and the first space disappears.  Type another space and the single space reappears, except your file has three spaces at the end of the line, not one.

To fix this problem, and to use an alternative method to highlight trailing whitespace which represents its quantity accurately, this is what I have done:

    (add-hook 'markdown-mode-hook (lambda ()
                                (setq  markdown-line-break-properties nil)
                                (setq show-trailing-whitespace t)))

I put this here in case anyone else is looking for a fix.
