### ISSUE TITLE
Allow disabling auto-align when traversing tables

### ISSUE THREAD

**Issue by nigredo-tori** [jrblevin/markdown-mode#625]
## Expected Behavior

There should be an option to opt out of reformatting tables when moving between cells.

## Actual Behavior

Moving between cells (`TAB` or `S-TAB`) realigns the whole table

## Steps to Reproduce

1. Create a markdown-mode buffer with this content (note that the table is not aligned):

    ```md
    | foo | bar |
    | qux | quux |
    ```
1. Put the cursor into any cell, and press `TAB`.
1. Observe that the table was realigned.

## Software Versions

- Markdown Mode: markdown-mode, version 2.5-dev
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2021-01-18, modified by Debian
- OS: Ubuntu Linux 21.04

## Motivation

My workflow happens to include editing large markdown tables (containing descriptions of configuration files), versioned under Git. At the moment, adding new rows often leads to reformatting the whole table, which results in a diff that is larger than I would like. These diffs are annoying to review, since the diff shows that  the whole table has changed, rather than a few rows. I think there should be a way to opt out of this behavior.

## Possible implementation

Guarding the `markdown-table-align` calls in `markdown-table-forward-cell` and `markdown-table-backward-cell` with a flag should probably do the trick.

**Comment by syohex** [comment]
@nigredo-tori Thanks for suggestion. How about #626 ?

**Comment by nigredo-tori** [comment]
> @nigredo-tori Thanks for suggestion. How about #626 ?

LGTM

**Comment by syohex** [comment]
Thanks for checking. I have merged.
