### ISSUE TITLE
The code is displayed in a different font

### ISSUE THREAD

**Issue by john-cj** [jrblevin/markdown-mode#633]
For some reason, еhe code is displayed in a different (and quite unattractive) font.

```
* foo1: `key1: value2`
* bar2: `key3: value4`
```

![image](https://user-images.githubusercontent.com/18004961/127931423-c617a04e-5c8f-4382-b861-5aefaccec527.png)

This is especially bad when you type the text inside fenced code block. Not only the font itself changes, but the line height as well (when you typing the closing backticks), two times, so the whole text below it will jump up and down.

![emacs](https://user-images.githubusercontent.com/18004961/127932094-9c0d1567-ef97-4180-9eb0-0ea04524cfc0.gif)

- markdown-mode: 2.4 (installed from melpa-stable)
- Emacs: 27.1
- OS: Windows 7

**Comment by syohex** [comment]
I suppose that it is difficult to fix this problem by emacs highlighting system and current markdown mode implementation.

**Comment by john-cj** [comment]
OK, I figured out how to fix it:

1. Type `M-x customize`
2. Select **Faces**
3. Select **Basic Faces**
4. Scroll down to **Fixed Pitch face**, click the triangle to expand it, and clear the checkbox.

   ![image](https://user-images.githubusercontent.com/18004961/128342797-321e4ed1-c1ac-497c-b467-11438d1e8d0b.png)

5. And then save changes, of course.

So it seems this issue is related to Emacs itself and not `markdown-mode`. Does anybody know why Emacs uses such a weird font? The look of this font is familiar to me: as far as I know, it is used by Windows to render Chinese text, but some applications (including Emacs, it seems) use it as a general-purpose fallback for some reason. Or may be this problem is actually related to Windows itself. Anyway, any investigations will be useful.
