### ISSUE TITLE
`markdown-fill-paragraph` needs to respect setext headings

### ISSUE THREAD

**Issue by Knusper** [jrblevin/markdown-mode#638]
## Expected Behavior

For this

```
Heading
=======
```

When the cursor is somehwere in there `markdown-fill-paragraph` should do nothing.

## Actual Behavior

But after `markdown-fill-paragraph` we have

```
Heading =======
```

- Markdown Mode: 2.5-dev
- Emacs: 26.1
- OS: debian 10

**Comment by syohex** [comment]
I have merge #645. Could you try to latest version ?

**Comment by Knusper** [comment]
This works.
