### ISSUE TITLE
Feature request: ==highlight== text highlighting

### ISSUE THREAD

**Issue by agisga** [jrblevin/markdown-mode#652]
Many markdown writing applications are using double equal signs to show text highlighting, for example, Obsidian, Quilt, logseq, iA Writer. Is it possible to implement or enable ==highlight== text highlighting for markdown-mode, so that it shows as highlighted text in the emacs window (i.e., background and foreground colors changed relative to rest of text)?

## Expected Behavior

For example, text highlighting with two equal signs in Obsidian: https://help.obsidian.md/How+to/Format+your+notes#Highlighting

**Comment by syohex** [comment]
How about #654 ?

**Comment by agisga** [comment]
Thank you, that's awesome!

**Comment by syohex** [comment]
Thanks for checking and suggestion the feature. I have merged it. Please report issue if you have any issue.
