### ISSUE TITLE
"Stable" version link goes to 2017 version on jblevins.org/projects/markdown-mode/

### ISSUE THREAD

**Issue by hackerb9** [jrblevin/markdown-mode#656]
## Expected Behavior

I don't use MELPA, so I followed the instructions on https://jblevins.org/projects/markdown-mode/ for downloading the "latest stable version" of markdown-mode.el to my emacs lisp directory. 

I expected it was the latest stable version.

## Actual Behavior

The link goes to version 2.3 (2017). The actual stable version is 2.4 (2020). 

## Steps to Reproduce

1. Click on the link labeled "latest stable version" under the section "Direct Download" on https://jblevins.org/projects/markdown-mode/.
2. Notice that markdown-mode.el is from 2017

## Software Versions

- GNU Emacs 27.1
- markdown-mode, version 2.3
- Debian GNU/Linux 11 (bullseye)
 
## Side note

While this bug may make you think that web pages are obsolete and everyone should just use MELPA/github, please do not go that route. The old ways are still valuable. In fact, I hope you will go even further and include a version of markdown-mode.el within GNU Emacs. Your mode has existed for fourteen years and works great. It's just a shame it doesn't come out of the box with Emacs.

**Comment by hackerb9** [comment]
P.S. I just noticed you have a [markdown-mode book](https://leanpub.com/markdown-mode) on leanpub.com. It let me set my own price, so I paid the maximum. I want to encourage Emacs lisp hackers, especially ones who recognize the value of good documentation.

**Comment by syohex** [comment]
@jrblevin Could you update your home page document or change this repository URL from http://jblevins.org/projects/markdown-mode/ to https://github.com/jrblevin/markdown-mode/blob/master/README.md or remove it ?

**Comment by hackerb9** [comment]
> @jrblevin Could you update your home page document or change this repository URL from http://jblevins.org/projects/markdown-mode/ to https://github.com/jrblevin/markdown-mode/blob/master/README.md or remove it ?

There is no home page document to update or remove. I found it by googling.

Do the developers no longer have the ability to edit jblevins.org? Is Jason Blevins no longer with us? 

Also, it looks like the README.md you suggested is just a copy of the jblevins.org page, but lacking the CSS formatting that makes jblevins.org easy to read. The README.md even has the same error, with a link named "latest stable version" that goes to the 2017 version.

**Comment by syohex** [comment]
> Do the developers no longer have the ability to edit jblevins.org? Is Jason Blevins no longer with us?

He is busy. I am main maintainer of markdown-mode and I can't modify his homepage.

> The README.md even has the same error, with a link named "latest stable version" that goes to the 2017 version.

I'll update later.

**Comment by jrblevin** [comment]
I will update my site for the latest version. It has been on my todo list too long.

**Comment by jrblevin** [comment]
Many thanks to @syohex for picking up my slack on markdown-mode.

**Comment by hackerb9** [comment]
> Many thanks to @syohex for picking up my slack on markdown-mode.

Yes, thank you, @syohex. The improvements and maintenance are greatly appreciated. 

And, I am glad to see you are still with us, @jrblevin! Will you be updating your book for version 2.4? (Yes, I know I could just look at the website for the info, but the XeTeX pdf is aesthetically enjoyable to read.)
