### ISSUE TITLE
Dynamicly generate `defface` will make `markdown-header-face-1` not config-able in `.emacs`.

### ISSUE THREAD

**Issue by xieyuheng** [jrblevin/markdown-mode#660]
```
error: Invalid face, markdown-header-face-1
```

**Comment by syohex** [comment]
It's not dynamic generated. They are generated by macro at compile. You can get such error when you reference faces before you load it. You should reference symbols, faces after loading library as below.

```lisp
(with-eval-after-load 'markdown-mode
  (set-face-foreground 'markdown-header-face-1 "green"))
```
