### ISSUE TITLE
multiline italics face when not wanted

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#67]
I'm using Package-Version: 20160109.957 with the mac homebrew emacs-24.5-mac-5.15 (which is  24.5.1).

I have a list as follows:
- something about function foo_bar
- something else about foo_bar

Everything between the two _ is in markdown-italic-face. I don't think it should be. Marked 2 doesn't display it as italics and neither does GitHub.

markdown-italic-underscore is nil.

**Comment by jrblevin** [comment]
This is indeed a bug. Thanks for the report. For now, I've added a test case in 8eca1ff (which is expected to fail until this is fixed).

**Comment by jrblevin** [comment]
OK, I believe this is fixed now. (See the discussion in PR #68 for additional details.)
