### ISSUE TITLE
Link containing underscores is not rendered correctly

### ISSUE THREAD

**Issue by umanwizard** [jrblevin/markdown-mode#671]
## Expected Behavior

Underscores in links should not cause the characters in between to be italicized.

## Actual Behavior

![image](https://user-images.githubusercontent.com/1893159/145122136-a91d3f55-97c9-4131-99b0-4d2dcb95f4ac.png)

## Software Versions

- Markdown Mode: 2.5-dev
- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-12-07
- OS: Debian 11.1

**Comment by syohex** [comment]
Did you use `markdown-mode`, not `gfm-mode` ? If so, please use `gfm-mode` instead. Original markdown specification does not say anything about bold and italic markup in link text. While CommonMark(also GFM) specifies it explicitly. So `gfm-mode` highlights as a below screenshot. I suppose it is just as you expected.

![markdown-mode](https://user-images.githubusercontent.com/554281/145142085-12883e8f-cb93-44b0-972b-e2245b90be4d.png)
