### ISSUE TITLE
Bug in syntax-highlighting

### ISSUE THREAD

**Issue by dssjoblom** [jrblevin/markdown-mode#684]
## Expected Behavior

Correct syntax-highlighting.

## Actual Behavior

See screenshot. Text after the triple quote line gets wrong highlighting.

![markdown-bug](https://user-images.githubusercontent.com/12595797/153164474-c1d5a4f4-437d-4275-9050-8539e18b3ca6.png)

## Software Versions

2.5-dev and 27.2 (Ubuntu)

**Comment by syohex** [comment]
Could you give us bug reproduce text instead of screenshot ?

**Comment by dssjoblom** [comment]
I'm attaching a partial file, should be reproducible with this.
[test2.md](https://github.com/jrblevin/markdown-mode/files/8031644/test2.md)

**Comment by syohex** [comment]
I have merged #685. Please check latest version.

**Comment by dssjoblom** [comment]
Works for me, thanks :)
