### ISSUE TITLE
Recommended installation method does not work

### ISSUE THREAD

**Issue by j18ter** [jrblevin/markdown-mode#688]
## Expected Behavior

README.md recommends installing from melpa-stable.

## Actual Behavior

Package is not found in the melpa archive.

This happens because markdown-mode was removed from the melpa archive. See this pull request:

[https://github.com/melpa/melpa/pull/7551](https://github.com/melpa/melpa/pull/7551)

## Steps to Reproduce

Follow melpa installation instructions in README.md.

## Software Versions

Any

**Comment by syohex** [comment]
https://stable.melpa.org/#/markdown-mode
https://melpa.org/#/markdown-mode

You can download markdown-mode from melpa and melpa-stable. Your link refers to `markdown-mode+` and that is not this repository.
