### ISSUE TITLE
Markdown mode does not follow global indent-tabs-mode (I want to use TAB but it uses SPC)

### ISSUE THREAD

**Issue by AlynxZhou** [jrblevin/markdown-mode#689]
I have following code in my `init.el`:

```
(defvar indent-tabs-mode-hooks)
(setq indent-tabs-mode-hooks '((prog-mode-hook . 8)
                               (markdown-mode . 8)
                               (gfm-mode . 8)))

(dolist (pair indent-tabs-mode-hooks)
  (add-hook (car pair) (lambda ()
                         (setq-default indent-tabs-mode t)
                         (setq-default tab-width (cdr pair)))))
```

## Expected Behavior

When I open `.md` files, markdown mode should follow my `indent-tabs-mode` and `tab-width` settings like other modes (C/python/js) to use TAB for indentation. `M-x describe-variable RET indent-tabs-mode` should be `t`， `M-x describe-variable RET tab-width` should be `8`.

## Actual Behavior

Markdown mode always set `indent-tabs-mode` to `nil` by itself and ignore my global settings. `M-x describe-variable RET indent-tabs-mode` is `nil` and `M-x describe-variable RET tab-width` is `4` this buffer.

## Steps to Reproduce

1. Install markdown-mode.
2. Add `(setq-default indent-tabs-mode t)` and `(setq-default tab-width 8)` in `init.el`.
3. Restart emacs and switch to `gfm-mode`, then run `M-x describe-variable RET indent-tabs-mode` and `M-x describe-variable RET tab-width`.

## Software Versions

- Markdown Mode: 2.5-dev
- Emacs: GNU Emacs 28.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-02-03 (I am using pgtk and native comp)
- OS: Arch Linux

**Comment by syohex** [comment]
`markdown-mode` does not set `indent-tabs-mode` value.

I suppose you could write your settings as below.

```lisp
(setq indent-tabs-mode-hooks '((prog-mode-hook . 8)
                               (markdown-mode-hook . 8)
                               (gfm-mode-hook . 8)))
```

**Comment by AlynxZhou** [comment]
Ah, sorry, it's my mistake.

However after I added `-hook`, `indent-tabs-mode` works fine, but `tab-width` is set to 4 buffer locally. Does markdown mode set `tab-width`?

**Comment by syohex** [comment]
> Does markdown mode set `tab-width`?

Yes. I'm not sure why the original author set `tab-width` to 4. I suppose that's why the original markdown specification uses 4 spaces for indent. It's difficult to change its value for compatibility. So if you want to modify its value, please change its value by `markdown-mode-hook` or `gfm-mode-hook`.

BTW you should not use `setq-default` because it modifies global value. Instead you can use `setq` because both `indent-tabs-mode` and `tab-width` are declared as buffer local variables.

**Comment by AlynxZhou** [comment]
> > Does markdown mode set `tab-width`?
> 
> Yes. I'm not sure why the original author set `tab-width` to 4. I suppose that's why the original markdown specification uses 4 spaces for indent. However it's difficult to change its value for compatibility. So if you want to modify its value, please change its value by `markdown-mode-hook` or `gfm-mode-hook`.

OK, I see. Maybe we can have a customization value to prevent markdown-mode set tab-width to 4 and disable it by default.

> BTW you should not use `setq-default` because it modifies global value. Instead you can use `setq` because both `indent-tabs-mode` and `tab-width` are declared as buffer local variables.

Yes! :laughing:  I just noticed it that if I use `setq-default` and open two files with different modes, the latter one will cover the former one's default value. I am changing to `setq` now. Thank you!
