### ISSUE TITLE
visit foo.md when hitting [foo](foo)

### ISSUE THREAD

**Issue by anarcat** [jrblevin/markdown-mode#713]
I'm using markdown-mode to edit a lot of wiki-like documentation written in Markdown. Typically GitLab wikis, where a link from page `bar.md` to `foo.md` takes a form of `[text](foo)`. It would be nice for this to work in markdown-mode.

## Expected Behavior

Visiting `[test](foo)` should open buffer `foo.md`.

## Actual Behavior

Instead it visits buffer `foo`, no extension.

## Steps to Reproduce

 1. visit buffer `bar.md`
 2. insert `[test](foo)`
 3. hit <kbd>C-c C-o</kbd> AKA `(markdown-follow-thing-at-point`)
 4. visits `foo` instead of `foo.md`

## Backtrace

This is not a crash.

## Software Versions

- Markdown Mode: 2.4
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-03-27, modified by Debian
- OS: Debian GNU/Linux 11 bullseye

## Possible fix

I'm considering making a PR to add a customizable "default extension" for links that would add a default value to the `extension` variable in `markdown-convert-wiki-link-to-filename`.

specifically here:

https://github.com/jrblevin/markdown-mode/blob/f7cbc960d76b4b6a605a0675a1330959bfb99ed1/markdown-mode.el#L8045

would that be acceptable?

**Comment by syohex** [comment]
markdown-mode provides the file name traslating function for links. How about using it as below ?

```elisp
(setq markdown-translate-filename-function
      (lambda (file)
        (if (file-exists-p file)
            file
          (cl-loop for extension in '("mdown" "mkd" "md" "markdown")
                   for md-file = (concat file "." extension)
                   when (file-exists-p md-file)
                   return md-file
                   finally return file))))
```

**Comment by anarcat** [comment]
oh wow, that's amazing. it even works! i didn't find that hook digging around the code, it's pretty much exactly what i need!

seems to me we should make default, although i can't help but think that `cl-loop` looks a little odd there. ;)

or at least that function should be available as an example in markdown-mode.el.

could this be considered as a PR instead?

**Comment by anarcat** [comment]
> [...] although i can't help but think that `cl-loop` looks a little odd there. ;)

i've been battling with elisp and only came up with nameless horrors involving [throw in dolist](https://emacs.stackexchange.com/a/53708/11929) or `mapcan` which looks way uglier than what you came up with. so: apologies for picking on cl there, that looks absolutely fine. :)

**Comment by syohex** [comment]
> could this be considered as a PR instead?

No. I suggest that add it to your configuration file(`init.el`)

**Comment by syohex** [comment]
Because it's not a markdown specification. We think that we should not implement non-specification features as possible for maintenance. And markdown-mode has already provides features(`markdown-translate-filename-function`) for your needs. If it is impossible to realize your needs, we should implement something to do it. But markdown-mode has `markdown-translate-filename-function` and it's a more flexible solution than hard-coded version like #714. So please use it.

**Comment by anarcat** [comment]
> it's a more flexible solution than hard-coded version like #714. So please use it.

but that's what i'm trying to say here: nothing is hardcoded in #714 in the sense that it's not enabled by default, it's just a suggestion. we could support multiple patterns through such functions, none enabled by default... 

wiki links are also not in the markdown specification (in fact, there is no unambiguous markdown specification, unless you're talking about common mark), yet it's in markdown-mode. so i am not sure i see why this is getting refused for lack of a specification...

anyways, i guess I shouldn't complain, you found a great solution to my problem and i'll use it! it's just a shame others won't benefit from it. :)
