### ISSUE TITLE
`save-some-buffers` wants to save `eldoc` generated markdown files because the ` markdown-code-fontification` buffers are being set to modified

### ISSUE THREAD

**Issue by granitrocky** [jrblevin/markdown-mode#719]
This is an issue brought up in the `rustic` package.
https://github.com/brotzeit/rustic/issues/253

The generated markdown file from `markdown-fontify-code-block-natively` is being grabbed by `save-some-buffers`.

I have a fix, but I need to create a pull request. 

Adding `(set-buffer-modified-p nil)` to the code that writes the markdown to the file stops `save-some-buffers` from asking to save `markdown-code-fontification`

**Comment by syohex** [comment]
Could you tell us how to reproduce this issue ?

**Comment by granitrocky** [comment]
Minimum reproducible steps (on my machine)

* Create a new file
* Switch to `markdown-mode`
* Make sure that `markdown-fontify-code-blocks-natively` is set to `t`
* Add any kind of code block. (Actually upon testing this looks like it's rust specific. That might be something to investigate) For this example I will do
```rust
fn test_function(){}
```
* Run `M-x save-some-buffers`. On my machine this is bound to `C-x s`
* emacs will prompt to save the new file AND the generated markdown buffer

**Comment by granitrocky** [comment]
Welp I think I figured out what is the ACTUAL bug here in setting up `rustic` as a package for emacs I followed a tutorial that said to set `buffer-save-without-query` to `t` every time rust mode runs. This should not be setup. I don't think this bug actually exists and it was a problem with my configuration. 

I am going to close this and the associated PR
