### ISSUE TITLE
incorrect word count compared to wc -w

### ISSUE THREAD

**Issue by anarcat** [jrblevin/markdown-mode#726]
Markdown mode doesn't seem to support telling Emacs to skip certain characters to make sure word counts are accurate. An example of a recent text I wrote counts almost a thousand more words than `wc`.

## Expected Behavior

```
anarcat@curie:anarc.at$ wc -w blog/2022-08-26-nationalize-internet.md
4475 blog/2022-08-26-nationalize-internet.md
anarcat@curie:anarc.at$ wc  blog/2022-08-26-nationalize-internet.md
  613  4475 34316 blog/2022-08-26-nationalize-internet.md
```

## Actual Behavior

<kbd>M-x count-words</kbd> gives me:

```
Buffer has 613 lines, 5459 words, and 34267 characters.
```

Kind of fascinating that the byte count is different as well. I suspect *that* might be a bug in `wc`, where it would count UTF-8 characters as multiple characters instead of single ones.

## Steps to Reproduce

1. load [this file](http://source.anarcat.wiki.orangeseeds.org/?p=source.git;a=blob_plain;f=blog/2022-08-26-nationalize-internet.md;hb=92498b989ac1ec21768885cc097cf1348dd85c5a) in an emacs buffer with `markdown-mode` enabled
2. <kbd>M-x count-words</kbd>

## Backtrace

N/A

## Software Versions

- Markdown Mode:  2.4, from Debian stable packages
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-03-27, modified by Debian
- OS: Debian GNU/Linux stable "bullseye"

**Comment by syohex** [comment]
I suppose that `wc -w` treats only spaces as  a word separator. While emacs treats spaces, punctuations, quotes etc as a word separator. For example, 

```markdown
title="How"
```

`wc -w` counts this as 1 word, while emacs counts this as 2 words. 

You can change emacs behavior through syntax-table configuration. Please modify your syntax-table configuration in markdown-mode, if you want emacs to work same as `wc`

Reference
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.htmll

**Comment by anarcat** [comment]
i understand where the bug comes from, what I am saying is i think markdown-mode should ship with such a syntax table. is there a table that i missed?

**Comment by syohex** [comment]
> markdown-mode should ship with such a syntax table

This is impossible. If markdown-mode uses such a syntax table, then many markdown commands and highlighting don't work as expected. And it also changes behaviors of many other commands such as word moving commands(`M-f`, `M-b` etc), symbol moving commands(`C-M-f`, `C-M-b` etc) and so on.

You can modify syntax-table personally . Please check `markdown-mode-syntax-table` and modify it as you expected in your configuration file. (You can see the current buffer syntax by `M-x describe-syntax`.)
