### ISSUE TITLE
Changing background color in code block

### ISSUE THREAD

**Issue by jcborras** [jrblevin/markdown-mode#729]
Hi there,
I've updated the version I'm using to 2.3 and the background color in the code blocks is different from the rest of the buffer.

I think it is beautiful feature but it does not mix well with my [solarized](https://github.com/bbatsov/solarized-emacs) theme settings: the font color is too light for the sand color background which happens to be the same than the cursor color.

Any hints on how to configure `markdown-mode` so that to prevent this issue?
Thanks in advance,

Using versions:

- Markdown Mode: v2.3 from MELPA (or elpa, not sure, installed using `package.el`).
- Emacs: 26.3
- OS: Ubuntu 20.04.

**Comment by syohex** [comment]
You can changing color via the face `markdown-pre-face`. For example

```lisp
(set-face-background 'markdown-pre-face "red")
```

**Comment by jcborras** [comment]
Got it. Thank-you very much.
