### ISSUE TITLE
Fontification issue with underscore bold followed by italic

### ISSUE THREAD

**Issue by denisw** [jrblevin/markdown-mode#731]
When using underscores marking a word as bold and, later on the same line, another word as italic, like this:

```markdown
__ONE__ TWO _THREE_
```

then the text between the bold and italic text is errornously fontified as italic.

## Expected Behavior

In the above example, only "THREE" should be displayed in italics.

## Actual Behavior

Both "TWO" and "THREE" are displayed in italics. For other combinations of bold / italics forms, all is well.

<img width="261" alt="Screenshot 2022-10-21 at 16 24 47" src="https://user-images.githubusercontent.com/1032624/197221064-14bf0906-a2b6-4da7-8504-dd5947b797a8.png">

## Steps to Reproduce

In a `markdown-mode` buffer, type `__ONE__ TWO _THREE_`.

## Software Versions

- Markdown Mode: 2.6-dev
- Emacs: 28.2
- OS: macOS Monterey

**Comment by syohex** [comment]
@denisw Thanks for reporting issue. I have merged #732. Please check latest version.

**Comment by denisw** [comment]
@syohex Thank you for the quick fix! This solved the issue for me. 👍
