### ISSUE TITLE
README.md: Specified Arch (AUR) package (`emacs-goodies-el`) does not exist

### ISSUE THREAD

**Issue by ronalde** [jrblevin/markdown-mode#74]
The arch (AUR) package `` for `markdown-mode` does not exist at the specified location https://aur.archlinux.org/packages/emacs-goodies-el/ in README.md. (And could not locate anywhere else).

Regards,
Ronald

**Comment by vyp** [comment]
That's probably because noone packaged it for the switch to the new AUR. FWIW, here's the old PKGBUILD: <http://pkgbuild.com/git/aur-mirror.git/tree/emacs-goodies-el/PKGBUILD>.

**Comment by jrblevin** [comment]
Thanks for letting me know. Perhaps I remove the link for now? Or do you think there is a chance the package will get rebuilt soon?

**Comment by vyp** [comment]
> Or do you think there is a chance the package will get rebuilt soon?

It doesn't happen automatically or something, because the AUR is not officially supported by Arch Linux. So someone *has* to package it for the new AUR. So maybe it's best to remove the link for now?

**Comment by jrblevin** [comment]
Thanks, will do. Some other distributions (Debian/Ubuntu) have begun packaging markdown-mode directly, so perhaps that's an option for Arch (if there are any takers).

There were a lot of other nice packages in `emacs-goodies-el` (color-theme.el, if I recall correctly), but maybe some are beginning to become obsolete now...

**Comment by jrblevin** [comment]
Removed link in a54a060. Please let me know if a package for Arch becomes available again.
