### ISSUE TITLE
Links in angle brackets <urlscheme://example>

### ISSUE THREAD

**Issue by vibrog** [jrblevin/markdown-mode#743]
Highlight links in angle brackets `<urlscheme://example>`, according to
https://spec.commonmark.org/0.30/#link-destination
https://www.markdownguide.org/basic-syntax#urls-and-email-addresses

**Comment by syohex** [comment]
I suppose `markdown-mode` already implements highlighting links in angle brackets. Could you show us reproduce markdown text of your issue ?

**Comment by vibrog** [comment]
- https://example.com/ // <https://example.com/>
- test://example.com // <test://example.com>
- geo:59.5,11.0 // <geo:59.5,11.0>
- tel:+555 // <tel:+555>
- sip:+555 // <sip:+555>
- mailto:nobody@example.com // <mailto:nobody@example.com>

<img width="475" alt="Screenshot 2023-02-26 at 14 19 52" src="https://user-images.githubusercontent.com/67639/221412873-f85a45cc-63d1-490c-bf46-da847d64fb17.png">

**Comment by syohex** [comment]
I have merged #751
