### ISSUE TITLE
Using which-function-mode with markdown-mode uses headings from other buffers

### ISSUE THREAD

**Issue by slinkp** [jrblevin/markdown-mode#765]
## Expected Behavior

`which-function` should display the current heading from the current markdown file.

## Actual Behavior

Sometimes it displays headings from an entirely different file in a different buffer, or even one that's from a buffer that I've killed.

I have not noticed which-function misbehaving with other modes.

## Steps to Reproduce

0. Close any markdown files and exit emacs (sometimes seems I need to do this to get a clean slate with which-function mode, don't know why)
1. Create a new markdown file and add some section headings using eg the `## foo` syntax. Save it.
(Sometimes which-function doesn't start working unless I close and re-open the file. Do that.)
2. Create a second markdown file in another buffer with some other sections. Save it. Notice that which-function may be displaying sections from the _first_ file.
3. In general it seems like which-function is keeping stale heading state from markdown files.

This seems somewhat inconsistent but I'm usually able to repro.

Video:

https://github.com/jrblevin/markdown-mode/assets/98610/1ef1a5ef-37e2-441b-a971-189b9e2ec2af

## Software Versions

- Markdown Mode: 2.6-alpha, rev `ad3a816f7be97deb83fc0a7fa41305c79009bac5`, installed via `straight` 
- Emacs: GNU Emacs 28.2 (build 2, x86_64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-02-26
- OS: MacOS 13.3.1 (22E261)

**Comment by syohex** [comment]
`markdown-mode` does nothing for `which-function-mode`. If it is updated, please rescan imenu or try to use `imenu-auto-rescan` variable.

Reference
- https://www.emacswiki.org/emacs/WhichFuncMode
- https://www.gnu.org/software/emacs/manual/html_node/emacs/Imenu.html

**Comment by slinkp** [comment]
Thanks. `imenu-auto-rescan` does not seem to help, but I'll keep investigating.
