### ISSUE TITLE
Backslash escapes inside math and code are fontified as Markdown markup

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#766]
Backslashes inside math and code are fontified as Markdown markup.

## Expected Behavior

Backslashes as part of math or code are fontified according to the type of content (i.e., LaTeX or corresponding code language).

## Actual Behavior

Backslashes inside math or code are fontified and propertized as Markdown markup:

![Screen Shot 2023-05-21 at 18 18 36](https://github.com/jrblevin/markdown-mode/assets/30050534/f430c96a-c99b-492e-a656-404712f438f7)

![Screen Shot 2023-05-21 at 18 38 47](https://github.com/jrblevin/markdown-mode/assets/30050534/7f7bb220-61e6-4f3b-a4e6-13cb97f472d4)

This is especially misleading when hiding Markdown syntax is enabled.

## Steps to Reproduce

See the examples above.

## Software Versions

- Markdown Mode: From Git on 2023-05-21
- Emacs: 28.2.1
- OS: macOS 10.15

## Note

Commit ae1085a

**Comment by jimporter** [comment]
I think this would just need to add an extra check to not fontify backslash escapes when fontification has already added one of the following faces to the backslash:
* `markdown-inline-code-face`
* `markdown-pre-face`
* `markdown-math-face`

That should be pretty straightforward with some new `markdown-match-escape` function that checks the backslash's face before returning whether it matched.

**Comment by saf-dmitry** [comment]
> I think this would just need to add an extra check to not fontify backslash escapes when fontification has already added one of the following faces to the backslash:
> 
> - `markdown-inline-code-face`
> - `markdown-pre-face`
> - `markdown-math-face`
>
> That should be pretty straightforward with some new `markdown-match-escape` function that checks the backslash's face before returning whether it matched.

Yes, that is how I would approach this. Another point to consider is, it should fontify only backslashes not preceding by another backslashes, i.e., in `\\` only the first backslash should be fontified because the second backslash stands for itself. Generally speaking, in something like `\\\\\\` only odd, i.e., 1, 3, and 5 backslash positions should be fontified.

**Comment by jimporter** [comment]
> Yes, that is how I would approach this. Another point to consider is, it should fontify only backslashes not preceding by another backslashes, i.e., in `\\` only the first backslash should be fontified because the second backslash stands for itself. Generally speaking, in something like `\\\\\\` only odd, i.e., 1, 3, and 5 backslash positions should be fontified.

This part should already work. The regexp is (approximately) `\\.`, so it'll match a backslash followed by anything. That means it'll see the first backslash, then skip past the next one before trying again. If you type a bunch of backslashes in a row into a `markdown-mode` buffer, it should do the right thing.

**Comment by jimporter** [comment]
@saf-dmitry Ok, hopefully [my PR](https://github.com/jrblevin/markdown-mode/pull/768) fixes this. Can you try it out to see?

**Comment by saf-dmitry** [comment]
I just played with it a little bit and it looks good.

The `markdown-literal-faces` variable can be used for various other purposes as well, so I would consider adding following faces to the list:

- `markdown-url-face`
- `markdown-plain-url-face`
- `markdown-language-keyword-face`
- `markdown-language-info-face`
- `markdown-metadata-key-face`
- `markdown-metadata-value-face`
- `markdown-html-entity-face`
- `markdown-html-tag-name-face`
- `markdown-html-tag-delimiter-face`
- `markdown-html-attr-name-face`
- `markdown-html-attr-value-face`
- `markdown-link-title-face`
- `markdown-reference-face`
- `markdown-footnote-marker-face`
- `markdown-line-break-face`
- `markdown-comment-face`

**Comment by jimporter** [comment]
> `markdown-link-title-face`

Link titles look like they support escape sequences, so I think they should be excluded from `markdown-literal-faces`. The others make sense though (I think...)

**Comment by saf-dmitry** [comment]
It seems that the current solution works only if native fontification of code block is disabled (which is the default).  If the variable `markdown-fontify-code-blocks-natively` is set to `t`, the backslash fontification issue comes again:

![Screen Shot 2024-07-14 at 08 16 04](https://github.com/user-attachments/assets/acf9db44-582d-4104-b6e4-3db785309d1d)

**Comment by jimporter** [comment]
> It seems that the current solution works in code blocks only if native fontification is disabled (which is the default). If the variable `markdown-fontify-code-blocks-natively` is set to `t`, the backslash fontification issue comes again:

@saf-dmitry Thanks for noticing, here's a fix: https://github.com/jrblevin/markdown-mode/pull/836

**Comment by saf-dmitry** [comment]
Thank you for the prompt fix. It works.
