### ISSUE TITLE
how to customize markdown-split-window-direction command

### ISSUE THREAD

**Issue by thefonso** [jrblevin/markdown-mode#769]
Greetings,

instructions state "...If you want to force the preview window to appear at the bottom or right, you can customize markdown-split-window-direction."

Can someone please tell me "how" to get the preview on the right side?

Much appreciated (thank you for making this tool)

**Comment by thefonso** [comment]
Ok, figured it out...for any other emacs newbie like me that comes along just add this to your config.el...

```
;; Set the split window direction for Markdown mode
(setq markdown-split-window-direction 'right)
```

Side note / suggestion...could this simple line be added to the readme

**Comment by syohex** [comment]
How about #770 ?
