### ISSUE TITLE
Extensible link-opening system similar to Org's? (volunteering to implement)

### ISSUE THREAD

**Issue by alphapapa** [jrblevin/markdown-mode#780]
Hi,

I'm one of the maintainers of [hyperdrive](https://git.sr.ht/~ushin/hyperdrive.el), a peer-to-peer filesystem in Emacs.  One of our features is allowing links in Org files to point to other files within a "hyperdrive."  This is done easily in Org by adding to `org-open-at-point-functions` so that links are handled by `hyperdrive` functions in a buffer where `hyperdrive-mode` is active.

We'd like to add similar support for Markdown files in `markdown-mode`.  However, looking at the `markdown-mode` code, I don't see a similarly extensible system that we could plug in to.

So, I'm volunteering to implement such a system in `markdown-mode`, if the maintainers are willing to accept it.  Probably it would be best to imitate Org's system, which would make it easy for packages that already extend Org in that way to extend `markdown-mode` similarly.  Of course, I'll be glad to write the code in a way that meets the maintainers' expectations and work to integrate the feature in the way they deem best.

Please let me know if this is a feature that you'd be willing to consider merging.  If so, I'll begin developing it right away.  Thanks.

**Comment by josephmturner** [comment]
Would you be open to extending `markdown-mode` in this way? @jrblevin @syohex

Thank you!!

**Comment by alphapapa** [comment]
@syohex I saw that you've been merging some PRs on this repo recently.  Thanks for that.  Would you be willing to merge a PR that implements this feature?  Thanks.

**Comment by syohex** [comment]
If the change does not break existing features, we'd merge it.

**Comment by alphapapa** [comment]
@syohex Thanks.
