### ISSUE TITLE
Fill-paragraph treats lines starting with italics as bullets

### ISSUE THREAD

**Issue by schuster** [jrblevin/markdown-mode#79]
Just ran into this today, and it's admittedly a bit of an edge case. If a bullet list item stretches over multiple lines (through the use of fill-paragraph), and one of those lines starts with a word marked with asterisks for italics, later uses of fill-paragraph will treat those asterisks as bullets rather than italic markers.

To reproduce: copy the following into a markdown-mode buffer in emacs and do a fill-paragraph (Meta-q) on it twice. The second time it will add bullet markers to 3rd and 4th lines.

`* foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo bar baz foo *bar* baz foo bar baz foo bar baz baz foo bar baz foo bar baz baz foo bar baz foo bar baz baz foo bar baz foo bar baz baz foo bar baz foo bar baz baz foo bar baz foo bar baz`

I don't know if this is fixable, but I'm reporting it in case anyone can think of a good solution.

**Comment by syohex** [comment]
Could you try again after setting `adaptive-fill-regexp` as below ?

```lisp
(defun my-markdown-mode-hook ()
  (set (make-local-variable 'adaptive-fill-regexp) "\\s-*"))
(add-hook 'markdown-mode-hook #'my-markdown-mode-hook)
```

Or evaluate s-exp in markdown buffer as below steps.
- Open markdown file
- `M-: (set (make-local-variable 'adaptive-fill-regexp) "\\s-*")`

**Comment by jrblevin** [comment]
Thanks, @syohex! Your patch fixed the problem for me. Thanks for the report, @schuster. I am closing this, but feel free to re-open if this didn't solve the issue for you.
