### ISSUE TITLE
Update MacPorts links in README

### ISSUE THREAD

**Issue by contextnerror** [jrblevin/markdown-mode#809]
## Expected Behavior
The MacPorts package should no longer be listed as pending, and the link to the port should be current. This would be either https://ports.macports.org/port/markdown-mode.el/ or https://github.com/macports/macports-ports/blob/master/editors/markdown-mode.el/Portfile depending on if a link directly to the source is desired.

## Actual Behavior
The port is currently described as pending. The link also leads to trac, which is several years behind the latest change. 

## Steps to Reproduce

N/A
## Backtrace
N/A

## Software Versions

N/A

**Comment by syohex** [comment]
Fixed at #852
