### ISSUE TITLE
resurrect emacs-26 support?

### ISSUE THREAD

**Issue by robohack** [jrblevin/markdown-mode#821]
I wonder if it would be possible to reduce the required emacs dependency (as listed on MELPA) for `markdown-mode` from emacs-27.1 back to at least emacs-26, if not emacs-25?

I support and use a few environments where updating emacs is not an option, yet I would dearly like to be able to install and use some packages which have markdown-mode as a pre-requisite, and of course to do this with `package-install`.  So far `markdown-mode` is one of the few packages I regularly need which has so aggressively updated its emacs dependency.

**Comment by syohex** [comment]
I'm afraid that no it does. We cannot afford to maintain markdown-mode for older Emacs versions. I'm not sure whether current markdown-mode works on older emacs but if there is a bug on such a older emacs, it could be difficult to reproduce bug and it costs much time for us. So we only maintain for latest three major versions.

**Comment by robohack** [comment]
That's too bad -- leaves a lot of people out on a limb with no resort but to run older versions, buggy or not.  Luckily none of the other packages I need are requiring the most recent markdown-mode.

I must say though that your attitude to this problem is still rather rare in the emacs community, at least if the number of still-compatible packages is any indication.
