### ISSUE TITLE
"_" character in a variable name turns on underline

### ISSUE THREAD

**Issue by worikgh** [jrblevin/markdown-mode#823]
If I have a sentence like: "The foo_bar frobnicates an_then" underlining is turned on between the two "_" characters
  

Underlining should not be turned on in that case.  

Checking https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet underlining is when " _\w"  and "\w_ "  are used around a section of text.  The spaces matter.

In my example there are no spaces, so there should be no underlining

## Steps to Reproduce

1. Step A
2. Step B
3. Step C

## Software Versions

- Markdown Mode: 
- Emacs: 
- OS: 

Emacs 30.0.50
Markdown mode: 20231028.853
OS: Debian 12

**Comment by syohex** [comment]
markdown-mode implements [the original markdown specification](https://daringfireball.net/projects/markdown/syntax) and it does not mention about this use case unlike GFM, CommonMark. gfm-mode supports this use case so please check gfm-mode(`M-x gfm-mode`).

```lisp
(add-to-list 'auto-mode-alist '("\\.md\\'" . gfm-mode))
```
