### ISSUE TITLE
`gfm-mode`: Syntactic support for Alerts 

### ISSUE THREAD

**Issue by iwahbe** [jrblevin/markdown-mode#838]
Enhancement: I would like `gfm-mode` to support GFM Alerts. I would really like this to work for `fill-paragraph`, but it would be nice if syntax highlighting was also supported.

## Expected Behavior

In `gfm-mode`, I expect that `fill-paragraph` does not flow text to invalidate [GFM Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts):

If I run `fill-paragraph` in a alert block, it should preserve the alert block on the first line:

```md
> [!TIP]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

To 

```md
> [!TIP]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
> incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
> exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
> dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
> pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
> deserunt mollit anim id est laborum.
```

## Actual Behavior

Currently, it goes from:

State 1
```md
> [!TIP]
> This is a tip.
```

To this:

State 2
```md
> [!TIP] This is a tip.
```

The rendered markdown goes from 

BEGIN_SRC

> [!TIP]
> This is a tip.

END_SRC

to 

BEGIN_SRC

> [!TIP] This is a tip.

END_SRC

## Steps to Reproduce

Run `fill-paragraph` on a text block that begins with `> [!NOTE]\n> ...`.

## Backtrace

NA: This is a feature request, not a bug.

## Software Versions

- Markdown Mode: 2.6
- Emacs: 30.0.50
- OS: macOS 14.5

I'd be willing to take a crack at resolving this if you would take the change.

**Comment by syohex** [comment]
Merged #853. `fill-paragraph` in `gfm-mode` considers GFM alert syntax now.
