### ISSUE TITLE
Live export (preview): code blocks are rendered on a single line 

### ISSUE THREAD

**Issue by sphakka** [jrblevin/markdown-mode#867]
It looks like the live export/preview mode renders code blocks as single lines, stripping all newline characters.

Take this MWE which is supposed to live-render the code block on several lines:
~~~
Pseudo code:
```
foo() {
    bar
    quux
}
```
~~~

## Expected Behavior

The code block is live-rendered as:
```
foo() {
    bar
    quux
}
```

## Actual Behavior

The code block is live-rendered as:
```
foo() { bar quux } 
```

Indeed, the HTML5 live code is rendered with a `<code>` element which has inline semantics (newlines are ignored). As [suggested by MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes), the code block could be wrapped in a `<pre>` element. 

## Steps to Reproduce

1. Open a buffer with the above MWE
2. Activate "live export"
3. Save the buffer

## Software Versions

- Markdown Mode: 2.7-alpha
- Emacs: GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.2) of 2024-12-08
- OS: GNU/Linux

**Comment by syohex** [comment]
I'm afraid that I cannot reproduce this.

- It seems you use very old markdown-mode. Does this issue reproduce with the latest version ?
- Which executable did you use to export ? (I use pandoc and I cannot reproduce this)

> Activate "live export"

What command should I do in this step ?

**Comment by sphakka** [comment]
Thanks for the hint about `markdown-command`.

Indeed, my emacs config had an old setting `markdown-command "markdown2"` (from https://github.com/trentm/python-markdown2/). So the bug is upstream.

Everything is fine with the default pandoc-based setting. Cheers ^^

**Comment by sphakka** [comment]
Closing...
