### ISSUE TITLE
(GFM): Options to disable triple backtick automation

### ISSUE THREAD

**Issue by mcandre** [jrblevin/markdown-mode#88]
I would appreciate options to disable:

* the which-language-would-you-like prompt
* automatic closing of triple backticks

**Comment by syohex** [comment]
You can disable it by following configuration.

```
(define-key gfm-mode-map (kbd "`") nil)
```

**Comment by mcandre** [comment]
Works for me, thanks!

**Comment by jrblevin** [comment]
There is a new custom variable named `markdown-gfm-use-electric-backquote` that achieves what you want.
