### ISSUE TITLE
unexpected test failure:  test-markdown-ext/live-preview-exports

### ISSUE THREAD

**Issue by bremner** [jrblevin/markdown-mode#96]
running "make test" on Debian testing (emacs 24.5), I get

> Test test-markdown-ext/live-preview-exports backtrace:
  #[nil \306P\307\310\311\312#\311313 \314\216\315\216\316\n!\
  #[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\317\320%DC
  funcall(#[0 "\306\307!r\211q\210\310\311\312\313\314\315!\316\"\31
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  #[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\316%DC\2
  funcall(#[0 "r\304 q\210\305 )\306\307\310\311\312\313!\314\"\315\
  ert-run-test([cl-struct-ert-test test-markdown-ext/live-preview-expo
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test t
  ert-run-tests(t #[385 "\306\307\"\203D\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "ert" "-l" "../markdown-mode.elc" "-l" "markdow
  command-line()
  normal-top-level()
Test test-markdown-ext/live-preview-exports condition:
    (ert-test-failed
     ((should-error
       (markdown-live-preview-mode))
      :form
      (markdown-live-preview-mode)
      :value t :fail-reason "did not signal an error"))

It seems to have something to do with the state of what libraries are loaded (maybe eww?) since if I run the tests interactively it succeeds on repeating the test.

**Comment by syohex** [comment]
I cannot reproduce this issue. And Travis-CI does not report such error.

I wonder why you got such error. Emacs 24.5 bundles eww and following condition `(require 'eww nil t)` returns non-nil. So `(should-error (markdown-live-preview-mode))` part is evaluated.

```
(unless (require 'eww nil t)
  (should-error (markdown-live-preview-mode)))
```

**Comment by bremner** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> I cannot reproduce this issue. And Travis-CI does not report such error.
>
> I wonder why you got such error. Emacs 24.5 bundles eww and following condition `(require 'eww nil t)` returns non-nil. So `(should-error (markdown-live-preview-mode))` part is evaluated.
>
> ```
> (unless (require 'eww nil t)
>   (should-error (markdown-live-preview-mode)))
> ```

Yes, I left out an important detail. The test failure occurs on v2.1,
but not on master.

d

**Comment by bremner** [comment]
David Bremner <david@tethera.net> writes:

> Syohei YOSHIDA <notifications@github.com> writes:
>
>> I cannot reproduce this issue. And Travis-CI does not report such error.
>>
>> I wonder why you got such error. Emacs 24.5 bundles eww and following condition `(require 'eww nil t)` returns non-nil. So `(should-error (markdown-live-preview-mode))` part is evaluated.
>>
>> ```
>> (unless (require 'eww nil t)
>>   (should-error (markdown-live-preview-mode)))
>> ```
>
> Yes, I left out an important detail. The test failure occurs on v2.1,
> but not on master.
>
> d

I can confirm cherry-picking facc168d on top of v2.1 causes the the
test to pass.

d

**Comment by jrblevin** [comment]
Thanks for reporting this and again for confirming that it's an issue only with 2.1 not master. Since it's not a user-visible issue, I think we can just let 2.1 remain as is.
