### ISSUE TITLE
Ordered list renumbering freeze

### ISSUE THREAD

**Issue by allencch** [jrblevin/markdown-mode#98]
When I have such content

```
a

1. a
3. c
2. b
```
And invoke the "C-c C-c n", Emacs will freeze.

But if I remove the empty line after "a" (the second line), then the renumbering works fine.

**Comment by cosmicexplorer** [comment]
This happens to me too. I'm gonna look at this later today.

**Comment by syohex** [comment]
@allencch Thanks for reporting issue. This issue is fixed by #100(Thanks @cosmicexplorer). Please check latest version. And please report us if you still have problem about this.

**Comment by allencch** [comment]
@syohex @cosmicexplorer , thank you. It works fine now.
